// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/bridge_rt.dart';
import 'api/create_stream.dart';
import 'api/mint.dart';
import 'api/rc_runner.dart';
import 'api/shed.dart';
import 'api/simple.dart';
import 'api/watcher.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_BridgeCreateHandlePtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeCreateHandle;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_BridgeWatcherHandlePtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeWatcherHandle;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  BridgeCreateHandle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeCreateHandle(
    dynamic raw,
  );

  @protected
  BridgeWatcherHandle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeWatcherHandle(
    dynamic raw,
  );

  @protected
  BridgeCreateHandle
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeCreateHandle(
    dynamic raw,
  );

  @protected
  BridgeWatcherHandle
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeWatcherHandle(
    dynamic raw,
  );

  @protected
  BridgeCreateHandle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeCreateHandle(
    dynamic raw,
  );

  @protected
  BridgeWatcherHandle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeWatcherHandle(
    dynamic raw,
  );

  @protected
  RustStreamSink<BridgeCreateUpdate>
  dco_decode_StreamSink_bridge_create_update_Sse(dynamic raw);

  @protected
  RustStreamSink<BridgeMintRequest>
  dco_decode_StreamSink_bridge_mint_request_Sse(dynamic raw);

  @protected
  RustStreamSink<BridgeWatcherUpdate>
  dco_decode_StreamSink_bridge_watcher_update_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  BridgeMintOutcome dco_decode_box_autoadd_bridge_mint_outcome(dynamic raw);

  @protected
  BridgeMintRequest dco_decode_box_autoadd_bridge_mint_request(dynamic raw);

  @protected
  BridgeControlBundle dco_decode_bridge_control_bundle(dynamic raw);

  @protected
  BridgeCreateUpdate dco_decode_bridge_create_update(dynamic raw);

  @protected
  BridgeLiveCounters dco_decode_bridge_live_counters(dynamic raw);

  @protected
  BridgeMintOutcome dco_decode_bridge_mint_outcome(dynamic raw);

  @protected
  BridgeMintRequest dco_decode_bridge_mint_request(dynamic raw);

  @protected
  BridgeRcInvocation dco_decode_bridge_rc_invocation(dynamic raw);

  @protected
  BridgeRcSession dco_decode_bridge_rc_session(dynamic raw);

  @protected
  BridgeWatcherUpdate dco_decode_bridge_watcher_update(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<BridgeRcSession> dco_decode_list_bridge_rc_session(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  BridgeCreateHandle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeCreateHandle(
    SseDeserializer deserializer,
  );

  @protected
  BridgeWatcherHandle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeWatcherHandle(
    SseDeserializer deserializer,
  );

  @protected
  BridgeCreateHandle
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeCreateHandle(
    SseDeserializer deserializer,
  );

  @protected
  BridgeWatcherHandle
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeWatcherHandle(
    SseDeserializer deserializer,
  );

  @protected
  BridgeCreateHandle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeCreateHandle(
    SseDeserializer deserializer,
  );

  @protected
  BridgeWatcherHandle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeWatcherHandle(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<BridgeCreateUpdate>
  sse_decode_StreamSink_bridge_create_update_Sse(SseDeserializer deserializer);

  @protected
  RustStreamSink<BridgeMintRequest>
  sse_decode_StreamSink_bridge_mint_request_Sse(SseDeserializer deserializer);

  @protected
  RustStreamSink<BridgeWatcherUpdate>
  sse_decode_StreamSink_bridge_watcher_update_Sse(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  BridgeMintOutcome sse_decode_box_autoadd_bridge_mint_outcome(
    SseDeserializer deserializer,
  );

  @protected
  BridgeMintRequest sse_decode_box_autoadd_bridge_mint_request(
    SseDeserializer deserializer,
  );

  @protected
  BridgeControlBundle sse_decode_bridge_control_bundle(
    SseDeserializer deserializer,
  );

  @protected
  BridgeCreateUpdate sse_decode_bridge_create_update(
    SseDeserializer deserializer,
  );

  @protected
  BridgeLiveCounters sse_decode_bridge_live_counters(
    SseDeserializer deserializer,
  );

  @protected
  BridgeMintOutcome sse_decode_bridge_mint_outcome(
    SseDeserializer deserializer,
  );

  @protected
  BridgeMintRequest sse_decode_bridge_mint_request(
    SseDeserializer deserializer,
  );

  @protected
  BridgeRcInvocation sse_decode_bridge_rc_invocation(
    SseDeserializer deserializer,
  );

  @protected
  BridgeRcSession sse_decode_bridge_rc_session(SseDeserializer deserializer);

  @protected
  BridgeWatcherUpdate sse_decode_bridge_watcher_update(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<BridgeRcSession> sse_decode_list_bridge_rc_session(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeCreateHandle(
    BridgeCreateHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeWatcherHandle(
    BridgeWatcherHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeCreateHandle(
    BridgeCreateHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeWatcherHandle(
    BridgeWatcherHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeCreateHandle(
    BridgeCreateHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeWatcherHandle(
    BridgeWatcherHandle self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_bridge_create_update_Sse(
    RustStreamSink<BridgeCreateUpdate> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_bridge_mint_request_Sse(
    RustStreamSink<BridgeMintRequest> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_bridge_watcher_update_Sse(
    RustStreamSink<BridgeWatcherUpdate> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bridge_mint_outcome(
    BridgeMintOutcome self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_mint_request(
    BridgeMintRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_control_bundle(
    BridgeControlBundle self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_create_update(
    BridgeCreateUpdate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_live_counters(
    BridgeLiveCounters self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_mint_outcome(
    BridgeMintOutcome self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_mint_request(
    BridgeMintRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_rc_invocation(
    BridgeRcInvocation self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_rc_session(
    BridgeRcSession self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_watcher_update(
    BridgeWatcherUpdate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bridge_rc_session(
    List<BridgeRcSession> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeCreateHandle(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeCreateHandle(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeCreateHandle(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeCreateHandle(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeWatcherHandle(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeWatcherHandle(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeWatcherHandle(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeWatcherHandle(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeCreateHandle(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeCreateHandle(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeWatcherHandle(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeWatcherHandle(
    int ptr,
  );
}
