// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.5.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/bridge_rt.dart';
import 'api/client.dart';
import 'api/create_stream.dart';
import 'api/dto.dart';
import 'api/dto_rc.dart';
import 'api/error.dart';
import 'api/local_sse.dart';
import 'api/mint.dart';
import 'api/rc_runner.dart';
import 'api/shed.dart';
import 'api/simple.dart';
import 'api/watcher.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_BridgeClientPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeClient;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_BridgeCreateHandlePtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeCreateHandle;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_BridgeTestSsePtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeTestSse;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_BridgeWatcherHandlePtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeWatcherHandle;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  BridgeClient
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeClient(
    dynamic raw,
  );

  @protected
  BridgeCreateHandle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeCreateHandle(
    dynamic raw,
  );

  @protected
  BridgeTestSse
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeTestSse(
    dynamic raw,
  );

  @protected
  BridgeWatcherHandle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeWatcherHandle(
    dynamic raw,
  );

  @protected
  BridgeClient
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeClient(
    dynamic raw,
  );

  @protected
  BridgeCreateHandle
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeCreateHandle(
    dynamic raw,
  );

  @protected
  BridgeTestSse
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeTestSse(
    dynamic raw,
  );

  @protected
  BridgeWatcherHandle
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeWatcherHandle(
    dynamic raw,
  );

  @protected
  Map<String, BridgeRcAgentInfo>
  dco_decode_Map_String_bridge_rc_agent_info_None(dynamic raw);

  @protected
  Map<String, BridgeRcKindFeatures>
  dco_decode_Map_String_bridge_rc_kind_features_None(dynamic raw);

  @protected
  BridgeClient
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeClient(
    dynamic raw,
  );

  @protected
  BridgeCreateHandle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeCreateHandle(
    dynamic raw,
  );

  @protected
  BridgeTestSse
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeTestSse(
    dynamic raw,
  );

  @protected
  BridgeWatcherHandle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeWatcherHandle(
    dynamic raw,
  );

  @protected
  RustStreamSink<BridgeCreateUpdate>
  dco_decode_StreamSink_bridge_create_update_Sse(dynamic raw);

  @protected
  RustStreamSink<BridgeMintRequest>
  dco_decode_StreamSink_bridge_mint_request_Sse(dynamic raw);

  @protected
  RustStreamSink<BridgeWatcherUpdate>
  dco_decode_StreamSink_bridge_watcher_update_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  BridgeCreateShedRequest dco_decode_box_autoadd_bridge_create_shed_request(
    dynamic raw,
  );

  @protected
  BridgeMintOutcome dco_decode_box_autoadd_bridge_mint_outcome(dynamic raw);

  @protected
  BridgeMintRequest dco_decode_box_autoadd_bridge_mint_request(dynamic raw);

  @protected
  BridgeRcActivity dco_decode_box_autoadd_bridge_rc_activity(dynamic raw);

  @protected
  BridgeRcCapabilities dco_decode_box_autoadd_bridge_rc_capabilities(
    dynamic raw,
  );

  @protected
  BridgeRcEvent dco_decode_box_autoadd_bridge_rc_event(dynamic raw);

  @protected
  BridgeRcFeedTool dco_decode_box_autoadd_bridge_rc_feed_tool(dynamic raw);

  @protected
  BridgeRcState dco_decode_box_autoadd_bridge_rc_state(dynamic raw);

  @protected
  BridgeSessionRc dco_decode_box_autoadd_bridge_session_rc(dynamic raw);

  @protected
  BridgeShed dco_decode_box_autoadd_bridge_shed(dynamic raw);

  @protected
  BridgeSystemDiskUsage dco_decode_box_autoadd_bridge_system_disk_usage(
    dynamic raw,
  );

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  BridgeControlBundle dco_decode_bridge_control_bundle(dynamic raw);

  @protected
  BridgeCreateShedRequest dco_decode_bridge_create_shed_request(dynamic raw);

  @protected
  BridgeCreateUpdate dco_decode_bridge_create_update(dynamic raw);

  @protected
  BridgeDiskEntry dco_decode_bridge_disk_entry(dynamic raw);

  @protected
  BridgeDiskSize dco_decode_bridge_disk_size(dynamic raw);

  @protected
  BridgeDiskTotals dco_decode_bridge_disk_totals(dynamic raw);

  @protected
  BridgeError dco_decode_bridge_error(dynamic raw);

  @protected
  BridgeLiveCounters dco_decode_bridge_live_counters(dynamic raw);

  @protected
  BridgeMintOutcome dco_decode_bridge_mint_outcome(dynamic raw);

  @protected
  BridgeMintRequest dco_decode_bridge_mint_request(dynamic raw);

  @protected
  BridgeOverlayEntry dco_decode_bridge_overlay_entry(dynamic raw);

  @protected
  BridgeOverview dco_decode_bridge_overview(dynamic raw);

  @protected
  BridgeOverviewServer dco_decode_bridge_overview_server(dynamic raw);

  @protected
  BridgeOverviewShed dco_decode_bridge_overview_shed(dynamic raw);

  @protected
  BridgeRcActivity dco_decode_bridge_rc_activity(dynamic raw);

  @protected
  BridgeRcAgentInfo dco_decode_bridge_rc_agent_info(dynamic raw);

  @protected
  BridgeRcCapabilities dco_decode_bridge_rc_capabilities(dynamic raw);

  @protected
  BridgeRcEvent dco_decode_bridge_rc_event(dynamic raw);

  @protected
  BridgeRcFeedMessage dco_decode_bridge_rc_feed_message(dynamic raw);

  @protected
  BridgeRcFeedTool dco_decode_bridge_rc_feed_tool(dynamic raw);

  @protected
  BridgeRcInvocation dco_decode_bridge_rc_invocation(dynamic raw);

  @protected
  BridgeRcKind dco_decode_bridge_rc_kind(dynamic raw);

  @protected
  BridgeRcKindFeatures dco_decode_bridge_rc_kind_features(dynamic raw);

  @protected
  BridgeRcMessagesPage dco_decode_bridge_rc_messages_page(dynamic raw);

  @protected
  BridgeRcSession dco_decode_bridge_rc_session(dynamic raw);

  @protected
  BridgeRcSessionDto dco_decode_bridge_rc_session_dto(dynamic raw);

  @protected
  BridgeRcState dco_decode_bridge_rc_state(dynamic raw);

  @protected
  BridgeSession dco_decode_bridge_session(dynamic raw);

  @protected
  BridgeSessionRc dco_decode_bridge_session_rc(dynamic raw);

  @protected
  BridgeShed dco_decode_bridge_shed(dynamic raw);

  @protected
  BridgeShedImage dco_decode_bridge_shed_image(dynamic raw);

  @protected
  BridgeShedStatus dco_decode_bridge_shed_status(dynamic raw);

  @protected
  BridgeSystemDiskUsage dco_decode_bridge_system_disk_usage(dynamic raw);

  @protected
  BridgeWatcherUpdate dco_decode_bridge_watcher_update(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<BridgeDiskEntry> dco_decode_list_bridge_disk_entry(dynamic raw);

  @protected
  List<BridgeOverlayEntry> dco_decode_list_bridge_overlay_entry(dynamic raw);

  @protected
  List<BridgeOverviewShed> dco_decode_list_bridge_overview_shed(dynamic raw);

  @protected
  List<BridgeRcFeedMessage> dco_decode_list_bridge_rc_feed_message(dynamic raw);

  @protected
  List<BridgeRcKind> dco_decode_list_bridge_rc_kind(dynamic raw);

  @protected
  List<BridgeRcSession> dco_decode_list_bridge_rc_session(dynamic raw);

  @protected
  List<BridgeRcSessionDto> dco_decode_list_bridge_rc_session_dto(dynamic raw);

  @protected
  List<BridgeSession> dco_decode_list_bridge_session(dynamic raw);

  @protected
  List<BridgeShed> dco_decode_list_bridge_shed(dynamic raw);

  @protected
  List<BridgeShedImage> dco_decode_list_bridge_shed_image(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(String, BridgeRcAgentInfo)>
  dco_decode_list_record_string_bridge_rc_agent_info(dynamic raw);

  @protected
  List<(String, BridgeRcKindFeatures)>
  dco_decode_list_record_string_bridge_rc_kind_features(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  BridgeRcActivity? dco_decode_opt_box_autoadd_bridge_rc_activity(dynamic raw);

  @protected
  BridgeRcCapabilities? dco_decode_opt_box_autoadd_bridge_rc_capabilities(
    dynamic raw,
  );

  @protected
  BridgeRcFeedTool? dco_decode_opt_box_autoadd_bridge_rc_feed_tool(dynamic raw);

  @protected
  BridgeRcState? dco_decode_opt_box_autoadd_bridge_rc_state(dynamic raw);

  @protected
  BridgeSessionRc? dco_decode_opt_box_autoadd_bridge_session_rc(dynamic raw);

  @protected
  BridgeSystemDiskUsage? dco_decode_opt_box_autoadd_bridge_system_disk_usage(
    dynamic raw,
  );

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  (String, BridgeRcAgentInfo) dco_decode_record_string_bridge_rc_agent_info(
    dynamic raw,
  );

  @protected
  (String, BridgeRcKindFeatures)
  dco_decode_record_string_bridge_rc_kind_features(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  BridgeClient
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeClient(
    SseDeserializer deserializer,
  );

  @protected
  BridgeCreateHandle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeCreateHandle(
    SseDeserializer deserializer,
  );

  @protected
  BridgeTestSse
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeTestSse(
    SseDeserializer deserializer,
  );

  @protected
  BridgeWatcherHandle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeWatcherHandle(
    SseDeserializer deserializer,
  );

  @protected
  BridgeClient
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeClient(
    SseDeserializer deserializer,
  );

  @protected
  BridgeCreateHandle
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeCreateHandle(
    SseDeserializer deserializer,
  );

  @protected
  BridgeTestSse
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeTestSse(
    SseDeserializer deserializer,
  );

  @protected
  BridgeWatcherHandle
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeWatcherHandle(
    SseDeserializer deserializer,
  );

  @protected
  Map<String, BridgeRcAgentInfo>
  sse_decode_Map_String_bridge_rc_agent_info_None(SseDeserializer deserializer);

  @protected
  Map<String, BridgeRcKindFeatures>
  sse_decode_Map_String_bridge_rc_kind_features_None(
    SseDeserializer deserializer,
  );

  @protected
  BridgeClient
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeClient(
    SseDeserializer deserializer,
  );

  @protected
  BridgeCreateHandle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeCreateHandle(
    SseDeserializer deserializer,
  );

  @protected
  BridgeTestSse
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeTestSse(
    SseDeserializer deserializer,
  );

  @protected
  BridgeWatcherHandle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeWatcherHandle(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<BridgeCreateUpdate>
  sse_decode_StreamSink_bridge_create_update_Sse(SseDeserializer deserializer);

  @protected
  RustStreamSink<BridgeMintRequest>
  sse_decode_StreamSink_bridge_mint_request_Sse(SseDeserializer deserializer);

  @protected
  RustStreamSink<BridgeWatcherUpdate>
  sse_decode_StreamSink_bridge_watcher_update_Sse(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  BridgeCreateShedRequest sse_decode_box_autoadd_bridge_create_shed_request(
    SseDeserializer deserializer,
  );

  @protected
  BridgeMintOutcome sse_decode_box_autoadd_bridge_mint_outcome(
    SseDeserializer deserializer,
  );

  @protected
  BridgeMintRequest sse_decode_box_autoadd_bridge_mint_request(
    SseDeserializer deserializer,
  );

  @protected
  BridgeRcActivity sse_decode_box_autoadd_bridge_rc_activity(
    SseDeserializer deserializer,
  );

  @protected
  BridgeRcCapabilities sse_decode_box_autoadd_bridge_rc_capabilities(
    SseDeserializer deserializer,
  );

  @protected
  BridgeRcEvent sse_decode_box_autoadd_bridge_rc_event(
    SseDeserializer deserializer,
  );

  @protected
  BridgeRcFeedTool sse_decode_box_autoadd_bridge_rc_feed_tool(
    SseDeserializer deserializer,
  );

  @protected
  BridgeRcState sse_decode_box_autoadd_bridge_rc_state(
    SseDeserializer deserializer,
  );

  @protected
  BridgeSessionRc sse_decode_box_autoadd_bridge_session_rc(
    SseDeserializer deserializer,
  );

  @protected
  BridgeShed sse_decode_box_autoadd_bridge_shed(SseDeserializer deserializer);

  @protected
  BridgeSystemDiskUsage sse_decode_box_autoadd_bridge_system_disk_usage(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  BridgeControlBundle sse_decode_bridge_control_bundle(
    SseDeserializer deserializer,
  );

  @protected
  BridgeCreateShedRequest sse_decode_bridge_create_shed_request(
    SseDeserializer deserializer,
  );

  @protected
  BridgeCreateUpdate sse_decode_bridge_create_update(
    SseDeserializer deserializer,
  );

  @protected
  BridgeDiskEntry sse_decode_bridge_disk_entry(SseDeserializer deserializer);

  @protected
  BridgeDiskSize sse_decode_bridge_disk_size(SseDeserializer deserializer);

  @protected
  BridgeDiskTotals sse_decode_bridge_disk_totals(SseDeserializer deserializer);

  @protected
  BridgeError sse_decode_bridge_error(SseDeserializer deserializer);

  @protected
  BridgeLiveCounters sse_decode_bridge_live_counters(
    SseDeserializer deserializer,
  );

  @protected
  BridgeMintOutcome sse_decode_bridge_mint_outcome(
    SseDeserializer deserializer,
  );

  @protected
  BridgeMintRequest sse_decode_bridge_mint_request(
    SseDeserializer deserializer,
  );

  @protected
  BridgeOverlayEntry sse_decode_bridge_overlay_entry(
    SseDeserializer deserializer,
  );

  @protected
  BridgeOverview sse_decode_bridge_overview(SseDeserializer deserializer);

  @protected
  BridgeOverviewServer sse_decode_bridge_overview_server(
    SseDeserializer deserializer,
  );

  @protected
  BridgeOverviewShed sse_decode_bridge_overview_shed(
    SseDeserializer deserializer,
  );

  @protected
  BridgeRcActivity sse_decode_bridge_rc_activity(SseDeserializer deserializer);

  @protected
  BridgeRcAgentInfo sse_decode_bridge_rc_agent_info(
    SseDeserializer deserializer,
  );

  @protected
  BridgeRcCapabilities sse_decode_bridge_rc_capabilities(
    SseDeserializer deserializer,
  );

  @protected
  BridgeRcEvent sse_decode_bridge_rc_event(SseDeserializer deserializer);

  @protected
  BridgeRcFeedMessage sse_decode_bridge_rc_feed_message(
    SseDeserializer deserializer,
  );

  @protected
  BridgeRcFeedTool sse_decode_bridge_rc_feed_tool(SseDeserializer deserializer);

  @protected
  BridgeRcInvocation sse_decode_bridge_rc_invocation(
    SseDeserializer deserializer,
  );

  @protected
  BridgeRcKind sse_decode_bridge_rc_kind(SseDeserializer deserializer);

  @protected
  BridgeRcKindFeatures sse_decode_bridge_rc_kind_features(
    SseDeserializer deserializer,
  );

  @protected
  BridgeRcMessagesPage sse_decode_bridge_rc_messages_page(
    SseDeserializer deserializer,
  );

  @protected
  BridgeRcSession sse_decode_bridge_rc_session(SseDeserializer deserializer);

  @protected
  BridgeRcSessionDto sse_decode_bridge_rc_session_dto(
    SseDeserializer deserializer,
  );

  @protected
  BridgeRcState sse_decode_bridge_rc_state(SseDeserializer deserializer);

  @protected
  BridgeSession sse_decode_bridge_session(SseDeserializer deserializer);

  @protected
  BridgeSessionRc sse_decode_bridge_session_rc(SseDeserializer deserializer);

  @protected
  BridgeShed sse_decode_bridge_shed(SseDeserializer deserializer);

  @protected
  BridgeShedImage sse_decode_bridge_shed_image(SseDeserializer deserializer);

  @protected
  BridgeShedStatus sse_decode_bridge_shed_status(SseDeserializer deserializer);

  @protected
  BridgeSystemDiskUsage sse_decode_bridge_system_disk_usage(
    SseDeserializer deserializer,
  );

  @protected
  BridgeWatcherUpdate sse_decode_bridge_watcher_update(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<BridgeDiskEntry> sse_decode_list_bridge_disk_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<BridgeOverlayEntry> sse_decode_list_bridge_overlay_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<BridgeOverviewShed> sse_decode_list_bridge_overview_shed(
    SseDeserializer deserializer,
  );

  @protected
  List<BridgeRcFeedMessage> sse_decode_list_bridge_rc_feed_message(
    SseDeserializer deserializer,
  );

  @protected
  List<BridgeRcKind> sse_decode_list_bridge_rc_kind(
    SseDeserializer deserializer,
  );

  @protected
  List<BridgeRcSession> sse_decode_list_bridge_rc_session(
    SseDeserializer deserializer,
  );

  @protected
  List<BridgeRcSessionDto> sse_decode_list_bridge_rc_session_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<BridgeSession> sse_decode_list_bridge_session(
    SseDeserializer deserializer,
  );

  @protected
  List<BridgeShed> sse_decode_list_bridge_shed(SseDeserializer deserializer);

  @protected
  List<BridgeShedImage> sse_decode_list_bridge_shed_image(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(String, BridgeRcAgentInfo)>
  sse_decode_list_record_string_bridge_rc_agent_info(
    SseDeserializer deserializer,
  );

  @protected
  List<(String, BridgeRcKindFeatures)>
  sse_decode_list_record_string_bridge_rc_kind_features(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  BridgeRcActivity? sse_decode_opt_box_autoadd_bridge_rc_activity(
    SseDeserializer deserializer,
  );

  @protected
  BridgeRcCapabilities? sse_decode_opt_box_autoadd_bridge_rc_capabilities(
    SseDeserializer deserializer,
  );

  @protected
  BridgeRcFeedTool? sse_decode_opt_box_autoadd_bridge_rc_feed_tool(
    SseDeserializer deserializer,
  );

  @protected
  BridgeRcState? sse_decode_opt_box_autoadd_bridge_rc_state(
    SseDeserializer deserializer,
  );

  @protected
  BridgeSessionRc? sse_decode_opt_box_autoadd_bridge_session_rc(
    SseDeserializer deserializer,
  );

  @protected
  BridgeSystemDiskUsage? sse_decode_opt_box_autoadd_bridge_system_disk_usage(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  (String, BridgeRcAgentInfo) sse_decode_record_string_bridge_rc_agent_info(
    SseDeserializer deserializer,
  );

  @protected
  (String, BridgeRcKindFeatures)
  sse_decode_record_string_bridge_rc_kind_features(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeClient(
    BridgeClient self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeCreateHandle(
    BridgeCreateHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeTestSse(
    BridgeTestSse self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeWatcherHandle(
    BridgeWatcherHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeClient(
    BridgeClient self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeCreateHandle(
    BridgeCreateHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeTestSse(
    BridgeTestSse self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeWatcherHandle(
    BridgeWatcherHandle self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_String_bridge_rc_agent_info_None(
    Map<String, BridgeRcAgentInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_String_bridge_rc_kind_features_None(
    Map<String, BridgeRcKindFeatures> self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeClient(
    BridgeClient self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeCreateHandle(
    BridgeCreateHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeTestSse(
    BridgeTestSse self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeWatcherHandle(
    BridgeWatcherHandle self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_bridge_create_update_Sse(
    RustStreamSink<BridgeCreateUpdate> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_bridge_mint_request_Sse(
    RustStreamSink<BridgeMintRequest> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_bridge_watcher_update_Sse(
    RustStreamSink<BridgeWatcherUpdate> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bridge_create_shed_request(
    BridgeCreateShedRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_mint_outcome(
    BridgeMintOutcome self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_mint_request(
    BridgeMintRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_rc_activity(
    BridgeRcActivity self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_rc_capabilities(
    BridgeRcCapabilities self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_rc_event(
    BridgeRcEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_rc_feed_tool(
    BridgeRcFeedTool self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_rc_state(
    BridgeRcState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_session_rc(
    BridgeSessionRc self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_shed(
    BridgeShed self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_system_disk_usage(
    BridgeSystemDiskUsage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_control_bundle(
    BridgeControlBundle self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_create_shed_request(
    BridgeCreateShedRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_create_update(
    BridgeCreateUpdate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_disk_entry(
    BridgeDiskEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_disk_size(
    BridgeDiskSize self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_disk_totals(
    BridgeDiskTotals self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_error(BridgeError self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_live_counters(
    BridgeLiveCounters self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_mint_outcome(
    BridgeMintOutcome self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_mint_request(
    BridgeMintRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_overlay_entry(
    BridgeOverlayEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_overview(
    BridgeOverview self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_overview_server(
    BridgeOverviewServer self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_overview_shed(
    BridgeOverviewShed self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_rc_activity(
    BridgeRcActivity self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_rc_agent_info(
    BridgeRcAgentInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_rc_capabilities(
    BridgeRcCapabilities self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_rc_event(BridgeRcEvent self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_rc_feed_message(
    BridgeRcFeedMessage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_rc_feed_tool(
    BridgeRcFeedTool self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_rc_invocation(
    BridgeRcInvocation self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_rc_kind(BridgeRcKind self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_rc_kind_features(
    BridgeRcKindFeatures self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_rc_messages_page(
    BridgeRcMessagesPage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_rc_session(
    BridgeRcSession self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_rc_session_dto(
    BridgeRcSessionDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_rc_state(BridgeRcState self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_session(BridgeSession self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_session_rc(
    BridgeSessionRc self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_shed(BridgeShed self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_shed_image(
    BridgeShedImage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_shed_status(
    BridgeShedStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_system_disk_usage(
    BridgeSystemDiskUsage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_watcher_update(
    BridgeWatcherUpdate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bridge_disk_entry(
    List<BridgeDiskEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bridge_overlay_entry(
    List<BridgeOverlayEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bridge_overview_shed(
    List<BridgeOverviewShed> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bridge_rc_feed_message(
    List<BridgeRcFeedMessage> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bridge_rc_kind(
    List<BridgeRcKind> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bridge_rc_session(
    List<BridgeRcSession> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bridge_rc_session_dto(
    List<BridgeRcSessionDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bridge_session(
    List<BridgeSession> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bridge_shed(
    List<BridgeShed> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bridge_shed_image(
    List<BridgeShedImage> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_bridge_rc_agent_info(
    List<(String, BridgeRcAgentInfo)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_bridge_rc_kind_features(
    List<(String, BridgeRcKindFeatures)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bridge_rc_activity(
    BridgeRcActivity? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_bridge_rc_capabilities(
    BridgeRcCapabilities? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_bridge_rc_feed_tool(
    BridgeRcFeedTool? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_bridge_rc_state(
    BridgeRcState? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_bridge_session_rc(
    BridgeSessionRc? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_bridge_system_disk_usage(
    BridgeSystemDiskUsage? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_bridge_rc_agent_info(
    (String, BridgeRcAgentInfo) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_bridge_rc_kind_features(
    (String, BridgeRcKindFeatures) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeClient(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeClient(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeClient(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeClient(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeCreateHandle(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeCreateHandle(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeCreateHandle(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeCreateHandle(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeTestSse(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeTestSse(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeTestSse(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeTestSse(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeWatcherHandle(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeWatcherHandle(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeWatcherHandle(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeWatcherHandle(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeClient(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeClient(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeCreateHandle(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeCreateHandle(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeTestSse(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeTestSse(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeWatcherHandle(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeWatcherHandle(
    int ptr,
  );
}
