//! The TokenMinter inversion (plan §3.2) — production shape.
//!
//! The control-token FSM lives in Rust (`shed_core::ControlTokenProvider`), but
//! a mint needs a Dart SSH round-trip. Inversion: [`BridgeMinter`] (installed as
//! the provider's `TokenMinter`) allocates a `request_id`, parks a `oneshot`
//! keyed by it, emits a [`BridgeMintRequest`] on an APP-SCOPED `StreamSink`
//! (D3, routed by `request_id`); Dart mints over dartssh2 and calls
//! [`submit_mint_result`]; Rust completes the `oneshot` and parses the bundle
//! IN RUST via `parse_credential_bundle` (with the expected pin). The whole path
//! runs on `bridge_rt` (FRB's executor has no tokio time driver — B1 finding 2),
//! so `tokio::time::timeout` is valid.
//!
//! Lifecycle invariants (plan §3.2): immutable transport identity in the
//! request; RAII pending-guard so an FRB-dropped future still cleans up; benign
//! rejection of unknown/late/duplicate submits; listener-before-client (a mint
//! with no sink fails fast); a capped pending map; one app-scoped sink with an
//! explicit shutdown seam (B1 finding 3) so Dart's unsubscribe never deadlocks.
//!
//! # mtls enrollment (plan 002 §7 P2/P3)
//!
//! [`BridgeMinter`] implements the generalized minter contract, so the SERVER
//! decides at every mint whether this client gets a bearer token or a client
//! CERTIFICATE. The keypair behind that certificate is generated by
//! `shed_core::ControlTokenProvider` (from `shed_core::csr`), lives in Rust
//! memory for as long as the credential it belongs to, and is never persisted.
//! All this module relays is the provider's base64 CSR — public material — which
//! rides [`BridgeMintRequest::extra_args`] out to Dart and comes back as the raw
//! bundle stdout. No private key exists on any type this module marshals.
//!
//! Secret handling (AC#5): the raw credential-bearing stdout crosses FFI ONLY in
//! the [`submit_mint_result`] payload (Dart→Rust). It is parsed then dropped; it
//! is never logged, never placed in an error/`Display`/`Debug`, never retained
//! past the `oneshot`, and never emitted back to Dart. What crosses back
//! ([`BridgeControlBundle`]) carries the token LENGTH, not bytes. Unit tests
//! destructure the REAL production DTOs field by field (plan 002 §7 P3(b)) and
//! scan the generated FRB surface for key-carrying types.

use std::collections::HashMap;
use std::sync::atomic::Ordering;
use std::sync::{Mutex, OnceLock};
use std::time::Duration;

use flutter_rust_bridge::frb;
use tokio::sync::oneshot;

use shed_core::http::ShedError;
use shed_core::token::{
    parse_credential_bundle, ControlBundle, CredentialRequest, MintedCredential, MintedToken,
    TokenBundleError, TokenMinter,
};

use crate::frb_generated::StreamSink;

use super::bridge_rt::{bridge_rt, next_id, PENDING_MINTS};
use super::error::encode_token_err;
use crate::sink_registry::{EmitError, Emitter, SinkRegistry};

/// Hard upper bound on a mint round-trip (SSH dial + remote exec + submit). The
/// provider's own cooldown/refresh-window knobs govern *when* a mint happens;
/// this bounds a single in-flight one so a wedged SSH never parks a request
/// forever.
const MINT_TIMEOUT: Duration = Duration::from_secs(45);

/// Cap on concurrently-parked mints. In practice one client mints at a time; a
/// runaway (e.g. a stuck Dart listener) fails fast rather than growing the map.
const MAX_PENDING_MINTS: usize = 64;

/// Hard cap on one `_bootstrap` bundle, enforced before the JSON parser sees it.
///
/// A real bundle is a single JSON line: a token or a PEM certificate, a pin, a
/// port and an expiry — under 1 KiB in token mode, roughly 2 KiB with a
/// certificate. 64 KiB is far past anything a shed-server emits while staying
/// small enough that a hostile endpoint cannot make the app accumulate and parse
/// megabytes.
///
/// It matters most on the ADD-SERVER path, which is the one place this client
/// talks to something the user has not trusted yet: the host key is TOFU, the
/// TLS pin is the thing being learned, and the SSH timeout is generous enough
/// (15–20 s) for a malicious endpoint to stream for a while. Bounding here bounds
/// what is retained and parsed; bounding what is READ off the socket is Dart's
/// half of the job, since the FRB submit hands over one already-built `String`.
const MAX_BUNDLE_BYTES: usize = 64 * 1024;

/// Why Rust is asking Dart to run a `_bootstrap` round-trip. The two purposes
/// differ ONLY in the trust anchor Dart must use for the SSH host key, which is
/// Dart's half of the flow and cannot be decided in Rust:
///   * [`BridgeMintPurpose::ControlMint`] — a saved server: the host key is
///     PINNED to the stored `ServerRecord.hostKeyPin`;
///   * [`BridgeMintPurpose::AddServerPreview`] — first contact ([`preview`]):
///     TOFU, and the fingerprint Dart learns is what the user confirms.
///
/// [`preview`]: super::preview
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum BridgeMintPurpose {
    ControlMint,
    AddServerPreview,
}

/// The need-credential request Rust emits to Dart. Carries the IMMUTABLE
/// transport identity (plan §3.2) — not a mutable server-name to be looked up at
/// submit time.
///
/// # `extra_args` — the mtls enrollment channel (plan 002 §7 P2, plan 001 D4)
///
/// The `_bootstrap` request grammar is `<scope> [<kind>] [csr=<base64 std DER>]`.
/// Dart already composes the first two tokens (`control shed-mobile`); this field
/// carries whatever else the mint needs — today exactly one `csr=…` argument, or
/// nothing for a CSR-less mint. **Dart appends these VERBATIM**: they are
/// already in wire form.
///
/// That "verbatim" is load-bearing, not stylistic. shed-server reads the request
/// line with `sess.RawCommand()` and splits it on whitespace — there is no shell
/// on that path, so a POSIX-quoted argument arrives WITH its quotes and the
/// `csr=` prefix match fails. Standard base64 uses `+` and `=`, which mobile's
/// `shellQuote` does not consider bare-safe, so routing these through
/// `wireCmd`/`shellQuote` would silently produce `'csr=…'` and an mtls server
/// would answer "this server requires auth.mode: mtls; upgrade shed". The M2 Dart
/// change must append them to the composed command string, not through the
/// quoter, and its injected-`SshRun` test asserts the exact argv.
///
/// Key containment (§7 P3): a CSR is a PUBLIC artifact — the private half stays
/// in the `ControlTokenProvider` that generated it (control mint) or in the
/// preview future (add-server), and no field on this type can carry it.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct BridgeMintRequest {
    pub request_id: String,
    pub purpose: BridgeMintPurpose,
    pub host: String,
    pub ssh_port: u16,
    pub base_url: String,
    pub expected_tls_pin: Option<String>,
    /// Extra `_bootstrap` arguments, appended VERBATIM after `control <kind>`.
    pub extra_args: Vec<String>,
}

/// The `_bootstrap` extra arguments for a credential request: the CSR argument
/// when the provider handed us one, nothing otherwise.
///
/// One place composes the wire form, so the mint path and the add-server preview
/// can never drift apart, and `csr=` is spelled exactly once in this crate.
pub(crate) fn csr_extra_args(csr_base64: Option<&str>) -> Vec<String> {
    match csr_base64 {
        Some(csr) => vec![format!("csr={csr}")],
        None => Vec::new(),
    }
}

/// Dart's answer to a mint request — a real FRB 2.13 sealed enum (the B1
/// tagged-struct workaround is retired). `Success` carries the raw
/// `shed-ext-rc`-style bundle stdout (the token-bearing payload); `Failure`
/// carries a non-secret code.
pub enum BridgeMintOutcome {
    Success { raw_stdout: String },
    Failure { code: String },
}

/// The parsed control bundle returned to Dart from [`demo_mint`] — TOKEN OMITTED
/// (only its length crosses back; AC#5).
pub struct BridgeControlBundle {
    pub token_present: bool,
    pub token_len: u32,
    pub expires_at_unix: u64,
    pub tls_cert_fingerprint: String,
    pub https_port: u16,
}

/// The typed failure of the shared mint core, so the caller can preserve a
/// `TokenBundleError` (Codex review #3) instead of stringifying it.
pub(crate) enum RunMintError {
    Message(String),
    Token(TokenBundleError),
}

impl RunMintError {
    /// Collapse into the only error type a `TokenMinter` may return, tunnelling a
    /// typed bundle error through the marked transport message
    /// (`error::TOKEN_ERR_MARKER`) so `From<ShedError>` can recover it. Both
    /// shapes are non-secret.
    pub(crate) fn into_shed_error(self) -> ShedError {
        ShedError::Transport(match self {
            RunMintError::Message(m) => m,
            RunMintError::Token(t) => encode_token_err(&t),
        })
    }
}

/// The raw `_bootstrap` bundle stdout, straight off the wire.
///
/// A newtype rather than a bare `String` for one reason: in token mode this text
/// IS the bearer token (plus its envelope), so it must never reach a log line, an
/// error payload, or a `{:?}` of an enclosing type. `Debug` is redacted, there is
/// no `Display`, and the only accessor hands out a borrowed `&str` for a parser
/// to consume — the value itself is dropped at the end of the mint that produced
/// it and never travels back across FFI.
pub(crate) struct RawBundle(String);

impl RawBundle {
    pub(crate) fn as_str(&self) -> &str {
        &self.0
    }
}

impl std::fmt::Debug for RawBundle {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("RawBundle")
            .field("stdout", &"<redacted>")
            .field("len", &self.0.len())
            .finish()
    }
}

/// How a parked mint resolves: Dart submitted, the bridge-runtime timer fired,
/// or the sink was shut down out from under it (Codex review #2).
enum MintResolution {
    Submitted(BridgeMintOutcome),
    TimedOut,
    SinkShutdown,
}

/// The app-scoped mint sink (plan D3: ONE shared sink routed by `request_id`),
/// with its generation and shutdown signal in the same atomically-swapped slot —
/// see [`SinkRegistry`] for the two races that shape demanded.
pub(crate) static MINT_SINK: SinkRegistry<BridgeMintRequest> = SinkRegistry::new();

// request_id -> oneshot sender awaiting Dart's submit (or the timer).
static PENDING: OnceLock<Mutex<HashMap<String, oneshot::Sender<MintResolution>>>> = OnceLock::new();

fn pending() -> &'static Mutex<HashMap<String, oneshot::Sender<MintResolution>>> {
    PENDING.get_or_init(|| Mutex::new(HashMap::new()))
}

/// Remove a pending entry, decrementing the leak counter IFF it was present.
/// The single mutation point, so the counter always matches the map exactly and
/// exactly one of {submit, timer, drop-guard} decrements per request.
fn take_pending(id: &str) -> Option<oneshot::Sender<MintResolution>> {
    let removed = pending().lock().unwrap().remove(id);
    if removed.is_some() {
        PENDING_MINTS.fetch_sub(1, Ordering::SeqCst);
    }
    removed
}

/// Register the app-scoped mint StreamSink and stay alive until
/// [`shutdown_mint_sink`] fires (keeping the FRB stream open for the app's
/// lifetime). Dart listens BEFORE any `BridgeClient` is constructed
/// (listener-before-client); a `mint` emitted with no sink fails fast.
///
/// Generation-guarded (Codex review #1): each registration takes a fresh
/// generation and, if a prior sink is live, evicts it FIRST (drains its pending
/// under the same lock, then fires its shutdown). When this task's await
/// returns, it clears the slot ONLY if it still owns the generation — so a later
/// sink B installed while A's task was parked is never clobbered by A.
pub async fn set_mint_sink(sink: StreamSink<BridgeMintRequest>) {
    let (generation, srx) = install_mint_sink(std::sync::Arc::new(sink));
    let _ = srx.await; // parks until shutdown_mint_sink() fires, then returns
    MINT_SINK.release(generation);
}

/// The ONE install point for the mint sink, so the eviction semantics —
/// "resolve the outgoing sink's parked mints under the same lock that removes
/// it" — are shared by production and by the tests that register a fake.
pub(crate) fn install_mint_sink(
    emitter: std::sync::Arc<dyn Emitter<BridgeMintRequest>>,
) -> (u64, oneshot::Receiver<()>) {
    MINT_SINK.install(emitter, drain_pending_locked)
}

/// End the mint sink fn cleanly (Dart calls this in `onDispose` before
/// unsubscribing). Idempotent. Resolves EVERY parked mint immediately with a
/// non-secret `SinkShutdown` (Codex review #2 — no more 45 s strand), then fires
/// the sink's shutdown signal. Synchronous so Riverpod `onDispose` can call it
/// without an unawaitable future (Codex review #9).
///
/// Removal and drain happen under ONE lock, which closes the window a split
/// implementation left open: a mint that parked after the drain but before the
/// sink was cleared used to stay parked to its 45 s timer even though its
/// listener was already gone. Now the emit that follows such a park sees no
/// sink and fails immediately.
#[frb(sync)]
pub fn shutdown_mint_sink() {
    MINT_SINK.shutdown(drain_pending_locked);
}

/// Resolve and remove EVERY parked mint with `SinkShutdown`, keeping the leak
/// counter exact (Codex review #2 — never strand a parked mint for the 45 s
/// timeout when the sink goes away).
///
/// Called only from inside [`SinkRegistry`]'s slot lock (install-eviction and
/// shutdown), so "the sink is gone" and "its parked work is resolved" are one
/// indivisible step. Lock order is registry → pending, and nothing takes them
/// the other way round: [`run_mint_raw`] parks (pending) and releases before it
/// emits (registry).
pub(crate) fn drain_pending_locked() {
    let entries: Vec<(String, oneshot::Sender<MintResolution>)> =
        pending().lock().unwrap().drain().collect();
    for (_id, tx) in entries {
        PENDING_MINTS.fetch_sub(1, Ordering::SeqCst);
        let _ = tx.send(MintResolution::SinkShutdown);
    }
}

/// RAII guard: on drop (normal return, error, OR FRB-cancel of the outer future)
/// remove the pending entry if still present — the drop-safe cleanup path.
struct PendingGuard {
    id: String,
}
impl Drop for PendingGuard {
    fn drop(&mut self) {
        let _ = take_pending(&self.id);
    }
}

/// The shared inversion core: emit a need-credential request → await Dart's
/// submit (bounded) → return the RAW bundle stdout for the caller to parse.
///
/// Three callers, three different parses, one round-trip implementation:
/// [`BridgeMinter::mint_credential`] (the mint path — `parse_credential_bundle`,
/// pin and port already known), [`super::preview::preview_add_server`] (first
/// contact — the stricter `parse_control_bundle`), and [`demo_mint`].
///
/// The returned [`RawBundle`] is credential-bearing; see its doc for why it is a
/// redacted newtype and not a `String`.
pub(crate) async fn run_mint_raw(
    purpose: BridgeMintPurpose,
    host: String,
    ssh_port: u16,
    base_url: String,
    expected_tls_pin: Option<String>,
    extra_args: Vec<String>,
    timeout: Duration,
) -> Result<RawBundle, RunMintError> {
    let request_id = next_id("mint");
    let (tx, rx) = oneshot::channel::<MintResolution>();

    // Cap + park BEFORE emitting, so a submit that races in can never find an
    // empty map. The guard cleans it up on any exit path.
    {
        let mut map = pending().lock().unwrap();
        if map.len() >= MAX_PENDING_MINTS {
            return Err(RunMintError::Message(
                "mint rejected: too many pending mint requests".to_string(),
            ));
        }
        map.insert(request_id.clone(), tx);
    }
    PENDING_MINTS.fetch_add(1, Ordering::SeqCst);
    let _guard = PendingGuard {
        id: request_id.clone(),
    };

    // Emit to the app-scoped sink (fail fast if none registered / closed).
    emit_request(BridgeMintRequest {
        request_id: request_id.clone(),
        purpose,
        host,
        ssh_port,
        base_url,
        expected_tls_pin,
        extra_args,
    })?;

    // Timeout driver on bridge_rt (FRB's executor has no time driver): after the
    // deadline, resolve the same oneshot with TimedOut if still pending.
    {
        let id = request_id.clone();
        bridge_rt().spawn(async move {
            tokio::time::sleep(timeout).await;
            if let Some(tx) = take_pending(&id) {
                let _ = tx.send(MintResolution::TimedOut);
            }
        });
    }

    // Await resolution — a plain channel await (safe on any executor).
    let outcome = match rx
        .await
        .map_err(|_| RunMintError::Message("mint channel dropped".to_string()))?
    {
        MintResolution::TimedOut => {
            return Err(RunMintError::Message(
                "mint timed out awaiting submit_mint_result".to_string(),
            ))
        }
        MintResolution::SinkShutdown => {
            return Err(RunMintError::Message("mint sink shut down".to_string()))
        }
        MintResolution::Submitted(o) => o,
    };

    match outcome {
        BridgeMintOutcome::Success { raw_stdout } => {
            // Fail closed on an oversized payload BEFORE it reaches a JSON parser
            // (see MAX_BUNDLE_BYTES). Only the length is reported — never a byte
            // of the payload, which in token mode is the credential itself.
            if raw_stdout.len() > MAX_BUNDLE_BYTES {
                return Err(RunMintError::Message(format!(
                    "bootstrap response too large: {} bytes (cap {MAX_BUNDLE_BYTES})",
                    raw_stdout.len()
                )));
            }
            Ok(RawBundle(raw_stdout))
        }
        BridgeMintOutcome::Failure { code } => {
            Err(RunMintError::Message(format!("mint failed: {code}")))
        }
    }
}

/// Hand one request to the app-scoped sink, failing fast when Dart is not
/// listening (listener-before-client) or the stream is closed. Never parks on a
/// sink that has gone away — that is the whole point of routing every emit
/// through the registry's single lock.
fn emit_request(req: BridgeMintRequest) -> Result<(), RunMintError> {
    MINT_SINK.emit(req).map_err(|e| {
        RunMintError::Message(
            match e {
                EmitError::NoSink => {
                    "no mint sink registered (listener-before-client violated, or the sink shut down)"
                }
                EmitError::Closed => "mint sink closed",
            }
            .to_string(),
        )
    })
}

/// [`run_mint_raw`] plus the strict add-server parse, for [`demo_mint`].
async fn run_mint(
    host: String,
    ssh_port: u16,
    base_url: String,
    expected_tls_pin: Option<String>,
    timeout: Duration,
) -> Result<ControlBundle, RunMintError> {
    let raw = run_mint_raw(
        BridgeMintPurpose::ControlMint,
        host,
        ssh_port,
        base_url,
        expected_tls_pin.clone(),
        Vec::new(),
        timeout,
    )
    .await?;
    // Parse IN RUST with the expected pin (a mismatch is a hard error, not a
    // silently-accepted bundle). Preserve the TYPED error (Codex #3). The raw
    // stdout is dropped at the end of this fn.
    shed_core::token::parse_control_bundle(raw.as_str(), expected_tls_pin.as_deref())
        .map_err(RunMintError::Token)
}

/// The production minter: installed as a `ControlTokenProvider`'s `TokenMinter`
/// so a real client request that needs a fresh control token drives the Dart
/// SSH round-trip. Carries the immutable transport identity (plan §3.2).
pub(crate) struct BridgeMinter {
    pub host: String,
    pub ssh_port: u16,
    pub base_url: String,
    pub expected_tls_pin: Option<String>,
}

#[async_trait::async_trait]
impl TokenMinter for BridgeMinter {
    /// Mobile ALWAYS supports mtls — unconditionally, with no capability
    /// negotiation anywhere in the stack.
    ///
    /// The mint is INVERTED here (plan §3.2): Dart owns no protocol knowledge, it
    /// runs the `_bootstrap` SSH command and hands the raw stdout back. A CSR is
    /// therefore just another argument string for Dart to relay
    /// ([`BridgeMintRequest::extra_args`]), so there is no version of this app
    /// that can carry the CSR out but not the certificate back — the two travel
    /// on the same wire the token already used. That is the difference from the
    /// desktop, where the minter is a SEPARATE PROCESS (shed-host-agent) that may
    /// be older than the app and must advertise its capability over the UDS
    /// (§7 P5's tri-state). Nothing analogous exists here: there is no second
    /// process, no version skew, and consequently nothing to negotiate.
    ///
    /// Saying `true` does not ask for a certificate — the SERVER still chooses
    /// the credential shape at every mint (D5). It only means "if you issue one,
    /// this client can complete the enrollment".
    fn supports_mtls(&self) -> bool {
        true
    }

    /// Mint whatever credential the server issues, relaying the provider's CSR.
    ///
    /// The keypair behind `req` was generated by the provider
    /// (`shed_core::csr::ClientKeyPair`, one per mint) and stays there; this
    /// method only sees `csr_base64()`, the public half in wire form. A
    /// certificate that comes back is paired with that key by the provider, which
    /// refuses one it did not request a CSR for.
    async fn mint_credential(
        &self,
        _server: &str,
        req: &CredentialRequest,
    ) -> Result<MintedCredential, ShedError> {
        let raw = run_mint_raw(
            BridgeMintPurpose::ControlMint,
            self.host.clone(),
            self.ssh_port,
            self.base_url.clone(),
            self.expected_tls_pin.clone(),
            csr_extra_args(req.csr_base64()),
            MINT_TIMEOUT,
        )
        .await
        // The trait can only return ShedError, so tunnel a typed TokenBundleError
        // through a MARKED transport message (Codex #3) — the client error path
        // (`From<ShedError>`) recovers it into TokenPinMismatch/PinMissing/
        // AuthExpired. A plain message stays a normal transport error. Both are
        // non-secret (the mint never surfaces credential bytes); the provider's
        // posture stays "no credential on failure" (no downgrade).
        .map_err(RunMintError::into_shed_error)?;

        // The MINT-path parse: the pin and https port are already known (the
        // transport exists), so only the credential and its expiry are required.
        // A present fingerprint that disagrees with the pin is still a hard error.
        parse_credential_bundle(raw.as_str(), self.expected_tls_pin.as_deref())
            .map_err(|t| RunMintError::Token(t).into_shed_error())
    }

    /// The legacy token-only entry point. Production never reaches it — the
    /// provider calls [`Self::mint_credential`] — but the trait requires it, and
    /// leaving it as a CSR-less mint keeps the two paths honest: a server that
    /// answers this one with a certificate is answering a request that carried no
    /// CSR, so the key would be one this process does not hold. Refused rather
    /// than unwrapped into an unusable credential.
    async fn mint(&self, server: &str) -> Result<MintedToken, ShedError> {
        match self
            .mint_credential(server, &CredentialRequest::default())
            .await?
        {
            MintedCredential::Token(t) => Ok(t),
            MintedCredential::Certificate(_) => Err(ShedError::Transport(
                "mint returned a client certificate for a request that carried no CSR".into(),
            )),
        }
    }
}

/// The direct integration proof of the full inversion (retained from B1): emit →
/// await Dart's submit → parse in Rust → return the NON-SECRET fields (token
/// length only). The real app never calls this; `BridgeClient` mints via the
/// provider path. Kept because it exercises the inversion end-to-end from Dart
/// without needing a live shed-server.
pub async fn demo_mint(
    host: String,
    ssh_port: u16,
    base_url: String,
    expected_tls_pin: Option<String>,
    timeout_ms: u64,
) -> Result<BridgeControlBundle, String> {
    let bundle = run_mint(
        host,
        ssh_port,
        base_url,
        expected_tls_pin,
        Duration::from_millis(timeout_ms),
    )
    .await
    .map_err(|e| match e {
        RunMintError::Message(m) => m,
        RunMintError::Token(t) => t.to_string(),
    })?;
    Ok(BridgeControlBundle {
        token_present: !bundle.token.is_empty(),
        token_len: bundle.token.len() as u32,
        expires_at_unix: bundle.expires_at_unix,
        tls_cert_fingerprint: bundle.tls_cert_fingerprint,
        https_port: bundle.https_port,
    })
}

/// Dart submits its mint result here. Benign no-op ("rejected") for an unknown /
/// late / duplicate `request_id` — never a panic. Single-resume via remove.
pub fn submit_mint_result(request_id: String, outcome: BridgeMintOutcome) -> String {
    match take_pending(&request_id) {
        Some(tx) => match tx.send(MintResolution::Submitted(outcome)) {
            Ok(()) => "accepted".to_string(),
            // Receiver already gone (timed out / cancelled) — benign.
            Err(_) => "rejected (already resolved)".to_string(),
        },
        None => "rejected (unknown request_id)".to_string(),
    }
}

/// AC#5 helper: proves the request DTO carries no token field (there is nothing
/// token-bearing to leak on the Rust→Dart request). The real enforcement is the
/// unit tests below — in particular `production_request_dto_carries_no_secret`,
/// which destructures the REAL type rather than trusting this constant (plan 002
/// §7 P3(b): "not a tautological helper").
#[frb(sync)]
pub fn mint_request_is_token_free(_req: BridgeMintRequest) -> bool {
    true
}

#[cfg(test)]
mod tests {
    use std::sync::Arc;

    use super::super::bridge_rt::live_counters;
    use super::super::error::BridgeError;
    use super::super::testsupport::{
        install_mint_emitter, install_sink_hook, mtls_bundle, pin, test_guard, token_bundle, TestCa,
    };
    use super::*;

    fn fixture(pin: &str) -> String {
        format!(
            r#"{{"scope":"control","token":"secret-tok","tls_cert_fingerprint":"{pin}","https_port":8443,"expires_at":"2030-01-01T00:00:00Z"}}"#
        )
    }

    #[test]
    fn parse_control_bundle_accepts_fixture() {
        let fp = "sha256:".to_string() + &"ab".repeat(32);
        let b = shed_core::token::parse_control_bundle(&fixture(&fp), Some(&fp)).unwrap();
        assert_eq!(b.https_port, 8443);
        assert_eq!(b.token, "secret-tok");
    }

    #[test]
    fn pin_mismatch_is_rejected() {
        let fp = "sha256:".to_string() + &"ab".repeat(32);
        let wrong = "sha256:".to_string() + &"cd".repeat(32);
        let err = shed_core::token::parse_control_bundle(&fixture(&fp), Some(&wrong)).unwrap_err();
        assert!(matches!(
            err,
            shed_core::token::TokenBundleError::PinMismatch
        ));
    }

    #[test]
    fn unknown_submit_is_benign() {
        let _g = test_guard();
        let r = submit_mint_result(
            "does-not-exist".to_string(),
            BridgeMintOutcome::Failure { code: "x".into() },
        );
        assert!(r.starts_with("rejected"));
    }

    // ---- sink registration / shutdown ordering (Codex M1 review, finding 2) ----

    /// A mint parked when the sink is gone must fail IMMEDIATELY, not sit out its
    /// 45 s timer. This is the shape the old split-cell implementation got wrong:
    /// shutdown drained the pending map and cleared the sink under two different
    /// locks, so a mint that slipped between them was stranded.
    #[test]
    fn a_mint_emitted_after_shutdown_fails_fast() {
        let _g = test_guard();
        install_sink_hook(|_req| {});
        shutdown_mint_sink();

        let started = std::time::Instant::now();
        let err = rt()
            .block_on(minter().mint_credential("srv", &CredentialRequest::default()))
            .unwrap_err();
        assert!(
            started.elapsed() < Duration::from_secs(5),
            "the mint waited for its timeout instead of failing fast"
        );
        assert!(
            format!("{err}").contains("no mint sink registered"),
            "{err}"
        );
        assert_eq!(live_counters().pending_mints, 0);
    }

    /// The interleaving itself: a mint parks, a shutdown lands while it is
    /// parked, and it resolves at once with the non-secret shutdown reason.
    #[test]
    fn a_mint_parked_during_shutdown_is_resolved_not_stranded() {
        let _g = test_guard();
        install_sink_hook(|_req| {
            // Called from inside the emit, i.e. with the request already parked —
            // the exact window the split-cell version left open.
            shutdown_mint_sink();
        });
        let started = std::time::Instant::now();
        let err = rt()
            .block_on(minter().mint_credential("srv", &CredentialRequest::default()))
            .unwrap_err();
        assert!(started.elapsed() < Duration::from_secs(5), "stranded");
        assert!(format!("{err}").contains("sink shut down"), "{err}");
        assert_eq!(live_counters().pending_mints, 0);
    }

    /// Shutdown-then-register: a registration AFTER a shutdown supersedes
    /// cleanly, and mints work again.
    #[test]
    fn registering_after_a_shutdown_supersedes_cleanly() {
        let _g = test_guard();
        shutdown_mint_sink(); // nothing registered — idempotent no-op
        install_sink_hook(|req| {
            submit_mint_result(
                req.request_id,
                BridgeMintOutcome::Success {
                    raw_stdout: token_bundle(&pin("ab"), Some("token")),
                },
            );
        });
        let minted = rt()
            .block_on(minter().mint_credential("srv", &CredentialRequest::default()))
            .expect("mint after re-registration");
        assert!(matches!(minted, MintedCredential::Token(_)));
    }

    /// Register-then-shutdown, twice: shutdown is idempotent and leaves nothing
    /// installed (a second one must not resurrect a sink or panic).
    #[test]
    fn shutdown_is_idempotent_and_leaves_no_sink() {
        let _g = test_guard();
        install_sink_hook(|_req| {});
        shutdown_mint_sink();
        shutdown_mint_sink();
        assert_eq!(
            MINT_SINK.emit(sample_request()).unwrap_err(),
            EmitError::NoSink
        );
    }

    /// Concurrent registrations: the LAST one owns the slot, and a stale
    /// generation calling `release` (its FRB stream function waking up late)
    /// must not clear the winner's sink.
    #[test]
    fn concurrent_registrations_leave_exactly_one_owner() {
        let _g = test_guard();
        let seen = Arc::new(Mutex::new(Vec::<String>::new()));

        let mut generations = Vec::new();
        for tag in ["a", "b", "c"] {
            let sink = seen.clone();
            let tag = tag.to_string();
            generations.push(install_mint_emitter(Arc::new(TagEmitter { tag, sink })));
        }
        // Every superseded generation wakes and releases; only the last is live.
        for g in &generations[..2] {
            MINT_SINK.release(*g);
        }
        MINT_SINK
            .emit(sample_request())
            .expect("the last sink owns");
        assert_eq!(*seen.lock().unwrap(), vec!["c".to_string()]);

        // ...and the winner's own release does clear it.
        MINT_SINK.release(*generations.last().unwrap());
        assert_eq!(
            MINT_SINK.emit(sample_request()).unwrap_err(),
            EmitError::NoSink
        );
    }

    /// A registered-but-CLOSED Dart stream is distinguished from no sink at all,
    /// and still fails fast.
    #[test]
    fn a_closed_sink_fails_fast_and_is_reported_as_closed() {
        let _g = test_guard();
        install_mint_emitter(Arc::new(super::super::testsupport::ClosedEmitter));
        assert_eq!(
            MINT_SINK.emit(sample_request()).unwrap_err(),
            EmitError::Closed
        );
        let err = rt()
            .block_on(minter().mint_credential("srv", &CredentialRequest::default()))
            .unwrap_err();
        assert!(format!("{err}").contains("mint sink closed"), "{err}");
        assert_eq!(live_counters().pending_mints, 0);
    }

    /// Re-registering evicts the previous sink AND drains its parked mints under
    /// the same lock — a mint waiting on sink A is not left waiting on sink B.
    #[test]
    fn a_new_registration_drains_the_evicted_sinks_parked_mints() {
        let _g = test_guard();
        install_sink_hook(|_req| {
            // Parked under sink A; a fresh registration lands while we wait.
            install_sink_hook(|_| {});
        });
        let err = rt()
            .block_on(minter().mint_credential("srv", &CredentialRequest::default()))
            .unwrap_err();
        assert!(format!("{err}").contains("sink shut down"), "{err}");
        assert_eq!(live_counters().pending_mints, 0);
    }

    struct TagEmitter {
        tag: String,
        sink: Arc<Mutex<Vec<String>>>,
    }

    impl Emitter<BridgeMintRequest> for TagEmitter {
        fn emit(&self, _value: BridgeMintRequest) -> Result<(), ()> {
            self.sink.lock().unwrap().push(self.tag.clone());
            Ok(())
        }
    }

    // ---- response size bound (Codex M1 review, finding 4) ----

    /// A bundle at the cap is accepted (the cap is a ceiling, not a fence around
    /// the real shape), and one over it is refused BEFORE the JSON parser runs.
    /// The refusal names only the length — never a byte of a payload that is, in
    /// token mode, the credential itself.
    #[test]
    fn an_oversized_bootstrap_response_is_refused_before_parsing() {
        let _g = test_guard();
        let p = pin("ab");

        // Exactly at the cap: pad a VALID bundle with an unknown key (which the
        // parser ignores) until it measures MAX_BUNDLE_BYTES.
        let at_cap = padded_bundle(&p, MAX_BUNDLE_BYTES);
        assert_eq!(at_cap.len(), MAX_BUNDLE_BYTES);
        let raw_at_cap = at_cap.clone();
        install_sink_hook(move |req| {
            submit_mint_result(
                req.request_id,
                BridgeMintOutcome::Success {
                    raw_stdout: raw_at_cap,
                },
            );
        });
        assert!(rt()
            .block_on(minter().mint_credential("srv", &CredentialRequest::default()))
            .is_ok());

        // One byte over: refused, with the length and nothing else.
        let over = padded_bundle(&p, MAX_BUNDLE_BYTES + 1);
        install_sink_hook(move |req| {
            submit_mint_result(
                req.request_id,
                BridgeMintOutcome::Success { raw_stdout: over },
            );
        });
        let err = rt()
            .block_on(minter().mint_credential("srv", &CredentialRequest::default()))
            .unwrap_err();
        let rendered = format!("{err}");
        assert!(rendered.contains("too large"), "{rendered}");
        assert!(rendered.contains(&(MAX_BUNDLE_BYTES + 1).to_string()));
        assert!(
            !rendered.contains("secret-tok"),
            "payload leaked: {rendered}"
        );
        assert_eq!(live_counters().pending_mints, 0);
    }

    /// A valid token bundle padded with an IGNORED key to exactly `len` bytes.
    fn padded_bundle(pin: &str, len: usize) -> String {
        let build = |n: usize| {
            format!(
                r#"{{"scope":"control","token":"secret-tok","tls_cert_fingerprint":"{pin}","https_port":8443,"expires_at":"2030-01-01T00:00:00Z","pad":"{}"}}"#,
                "x".repeat(n)
            )
        };
        build(len.saturating_sub(build(0).len()))
    }

    fn rt() -> tokio::runtime::Runtime {
        tokio::runtime::Builder::new_current_thread()
            .enable_all()
            .build()
            .unwrap()
    }

    #[test]
    fn pending_registry_single_resume_and_counter_discipline() {
        // The guard is load-bearing, not decoration: this test parks an entry in
        // the PROCESS-GLOBAL pending map and then submits against it, while every
        // sink-registering test drains that same map on registration (eviction
        // resolves the outgoing sink's parked mints under one lock — the
        // shutdown-race fix). Unguarded, a concurrent `install_sink_hook` removes
        // "req-x" before the submit lands and this fails with "rejected (unknown
        // request_id)" — the CI flake in run 30197516584.
        let _g = test_guard();
        // Drive the registry directly (no async sink): a parked entry resolves
        // exactly once; a duplicate/late submit for the same id is benign; the
        // leak counter tracks the map exactly.
        let before = PENDING_MINTS.load(Ordering::SeqCst);
        let (tx, mut rx) = oneshot::channel::<MintResolution>();
        pending().lock().unwrap().insert("req-x".into(), tx);
        PENDING_MINTS.fetch_add(1, Ordering::SeqCst);
        assert_eq!(PENDING_MINTS.load(Ordering::SeqCst), before + 1);

        // First submit resolves the parked oneshot.
        assert_eq!(
            submit_mint_result(
                "req-x".into(),
                BridgeMintOutcome::Success {
                    raw_stdout: "s".into()
                }
            ),
            "accepted"
        );
        assert!(matches!(rx.try_recv(), Ok(MintResolution::Submitted(_))));
        // Counter back to baseline (take_pending decremented on the resolve).
        assert_eq!(PENDING_MINTS.load(Ordering::SeqCst), before);

        // A duplicate/late submit for the now-removed id is a benign no-op.
        assert!(submit_mint_result(
            "req-x".into(),
            BridgeMintOutcome::Failure {
                code: "late".into()
            }
        )
        .starts_with("rejected"));
        assert_eq!(PENDING_MINTS.load(Ordering::SeqCst), before);
    }

    #[test]
    fn request_type_has_no_token_field() {
        // AC#5: the Rust→Dart request carries no token bytes at all.
        assert!(mint_request_is_token_free(sample_request()));
    }

    fn sample_request() -> BridgeMintRequest {
        BridgeMintRequest {
            request_id: "r".into(),
            purpose: BridgeMintPurpose::ControlMint,
            host: "h".into(),
            ssh_port: 22,
            base_url: "https://h".into(),
            expected_tls_pin: None,
            extra_args: Vec::new(),
        }
    }

    // ---- plan 002: the CSR ride-along, exact wire shape ----

    /// The composition rule, stated once: a CSR becomes exactly one `csr=<b64>`
    /// argument, and no CSR becomes no arguments (a token-only mint's request
    /// line is byte-identical to the pre-mtls one — plan 001 D4 compat leg).
    #[test]
    fn csr_extra_args_composes_one_argument_or_none() {
        assert_eq!(csr_extra_args(None), Vec::<String>::new());
        assert_eq!(
            csr_extra_args(Some("AAA+/aa=")),
            vec!["csr=AAA+/aa=".to_string()]
        );
    }

    /// The EXACT `_bootstrap` request line the M2 Dart relay must produce, spelled
    /// out against the server's grammar (`<scope> [<kind>] [csr=<b64>]`,
    /// `internal/sshd/bootstrap.go`).
    ///
    /// Dart owns the `control <kind>` prefix (`BootstrapService`), Rust owns the
    /// tail; this asserts the JOIN, which is the thing that can silently drift.
    /// Note what the value looks like: standard base64 with `+`, `/` and `=`
    /// padding. Mobile's `shellQuote` treats `+`/`=` as unsafe, so routing this
    /// through `wireCmd` would emit `'csr=…'` WITH quotes, the server's `csr=`
    /// prefix match would fail, and an mtls server would answer "upgrade shed".
    /// Hence "appended verbatim" on `BridgeMintRequest::extra_args`.
    #[test]
    fn the_bootstrap_request_line_matches_the_server_grammar() {
        // What Dart composes today, unchanged.
        let dart_prefix = ["control".to_string(), "shed-mobile".to_string()];
        let real_csr = shed_core::csr::ClientKeyPair::generate()
            .unwrap()
            .csr_base64();

        let argv: Vec<String> = dart_prefix
            .iter()
            .cloned()
            .chain(csr_extra_args(Some(&real_csr)))
            .collect();
        assert_eq!(argv.len(), 3);
        assert_eq!(argv[0], "control");
        assert_eq!(argv[1], "shed-mobile");
        assert_eq!(argv[2], format!("csr={real_csr}"));
        // Exactly one `csr=` argument (the server rejects duplicates), no
        // whitespace inside it (the server splits the line on whitespace), and
        // the standard alphabet (the server decodes with StdEncoding.Strict).
        assert_eq!(argv.iter().filter(|a| a.starts_with("csr=")).count(), 1);
        assert!(!argv[2].contains(char::is_whitespace));
        assert!(!real_csr.contains('-') && !real_csr.contains('_'));

        // A token-only mint leaves the line exactly as the pre-mtls client sent it.
        let argv: Vec<String> = dart_prefix
            .iter()
            .cloned()
            .chain(csr_extra_args(None))
            .collect();
        assert_eq!(argv, vec!["control", "shed-mobile"]);
    }

    /// Mobile advertises mtls unconditionally — there is no capability
    /// negotiation on this bridge (the CSR is just an argument Dart relays).
    #[test]
    fn the_bridge_minter_always_supports_mtls() {
        assert!(minter().supports_mtls());
    }

    fn minter() -> BridgeMinter {
        BridgeMinter {
            host: "host.example".into(),
            ssh_port: 2222,
            base_url: "https://host.example:8443".into(),
            expected_tls_pin: Some(pin("ab")),
        }
    }

    /// One CSR per mint, and a DIFFERENT key each time: the provider generates a
    /// fresh keypair per mint attempt (key lifetime == certificate lifetime), and
    /// the minter must relay THAT csr rather than caching one.
    #[test]
    fn each_mint_relays_exactly_one_fresh_csr() {
        let _g = test_guard();
        let seen = Arc::new(Mutex::new(Vec::<String>::new()));
        let rt = tokio::runtime::Builder::new_current_thread()
            .enable_all()
            .build()
            .unwrap();

        for _ in 0..2 {
            // A distinct CSR per attempt, exactly as the provider produces.
            let csr = shed_core::csr::ClientKeyPair::generate()
                .unwrap()
                .csr_base64();
            let req = CredentialRequest::with_csr(csr.clone());
            let sink = seen.clone();
            let expected = csr.clone();
            install_sink_hook(move |r| {
                assert_eq!(r.extra_args, vec![format!("csr={expected}")]);
                sink.lock().unwrap().push(r.extra_args[0].clone());
                // Answer with a token bundle: the point here is the OUTBOUND
                // relay, and a token answer needs no CA.
                submit_mint_result(
                    r.request_id,
                    BridgeMintOutcome::Success {
                        raw_stdout: token_bundle(&pin("ab"), Some("token")),
                    },
                );
            });
            let minted = rt
                .block_on(minter().mint_credential("srv", &req))
                .expect("mint");
            assert!(matches!(minted, MintedCredential::Token(_)));
        }

        let seen = seen.lock().unwrap();
        assert_eq!(seen.len(), 2);
        assert_ne!(seen[0], seen[1], "the minter cached a CSR across mints");
    }

    /// The mint path adopts whatever the server issues — a certificate for the
    /// CSR it relayed, with no local configuration involved (D5).
    #[test]
    fn the_mint_path_adopts_a_certificate_when_the_server_issues_one() {
        let _g = test_guard();
        let keypair = shed_core::csr::ClientKeyPair::generate().unwrap();
        let csr = keypair.csr_base64();
        let req = CredentialRequest::with_csr(csr.clone());
        install_sink_hook(move |r| {
            let sent = r.extra_args[0].strip_prefix("csr=").unwrap();
            assert_eq!(sent, csr, "the minter must relay the provider's CSR");
            let cert = TestCa::new().sign_csr_base64(sent);
            submit_mint_result(
                r.request_id,
                BridgeMintOutcome::Success {
                    raw_stdout: mtls_bundle(&pin("ab"), &cert),
                },
            );
        });
        let minted = tokio::runtime::Builder::new_current_thread()
            .enable_all()
            .build()
            .unwrap()
            .block_on(minter().mint_credential("srv", &req))
            .expect("mint");
        match minted {
            MintedCredential::Certificate(c) => {
                assert!(c.cert_pem.contains("BEGIN CERTIFICATE"));
                assert_eq!(c.serial, "2a");
                assert!(c.expires_at_unix.is_some());
            }
            other => panic!("expected a certificate, got {other:?}"),
        }
    }

    /// A CSR-less mint that comes back with a certificate is REFUSED: the key it
    /// was issued for lives in no process, so adopting it would arm a credential
    /// that can never complete a handshake.
    #[test]
    fn a_csr_less_mint_refuses_a_certificate() {
        let _g = test_guard();
        install_sink_hook(|r| {
            assert!(r.extra_args.is_empty());
            let kp = shed_core::csr::ClientKeyPair::generate().unwrap();
            let cert = TestCa::new().sign_csr_base64(&kp.csr_base64());
            submit_mint_result(
                r.request_id,
                BridgeMintOutcome::Success {
                    raw_stdout: mtls_bundle(&pin("ab"), &cert),
                },
            );
        });
        let err = tokio::runtime::Builder::new_current_thread()
            .enable_all()
            .build()
            .unwrap()
            .block_on(minter().mint("srv"))
            .unwrap_err();
        assert!(format!("{err}").contains("carried no CSR"), "{err}");
    }

    /// A typed bundle error survives the `ShedError`-only trait return and is
    /// recovered by the app-facing error mapping (Codex review #3, still true on
    /// the credential path).
    #[test]
    fn a_pin_mismatch_on_the_mint_path_surfaces_as_the_typed_error() {
        let _g = test_guard();
        install_sink_hook(|r| {
            submit_mint_result(
                r.request_id,
                BridgeMintOutcome::Success {
                    // Minted against a DIFFERENT server certificate than the one
                    // this client is pinned to — a possible MITM, never silently
                    // accepted.
                    raw_stdout: token_bundle(&pin("cd"), Some("token")),
                },
            );
        });
        let err = tokio::runtime::Builder::new_current_thread()
            .enable_all()
            .build()
            .unwrap()
            .block_on(minter().mint_credential("srv", &CredentialRequest::default()))
            .unwrap_err();
        assert_eq!(BridgeError::from(err), BridgeError::TokenPinMismatch);
    }

    // ---- key containment, on the REAL production DTOs (plan 002 §7 P3) ----

    /// §7 P3(b) against the actual type, not a helper that returns `true`.
    ///
    /// The request is DESTRUCTURED — no `..` — so a field added later cannot
    /// slip past this audit: the test stops compiling until someone classifies
    /// the new field. Every field is then checked against the material that must
    /// never cross: the PKCS#8 private key of the very keypair whose CSR is
    /// riding along (the sanctioned crossing), in both DER and PEM form.
    #[test]
    fn production_request_dto_carries_no_secret() {
        use base64::engine::general_purpose::STANDARD as BASE64;
        use base64::Engine as _;

        let keypair = shed_core::csr::ClientKeyPair::generate().unwrap();
        let key_b64 = BASE64.encode(keypair.key_pkcs8_der());
        let key_pem = keypair.key_pem();

        let req = BridgeMintRequest {
            request_id: "mint-1".into(),
            purpose: BridgeMintPurpose::ControlMint,
            host: "host.example".into(),
            ssh_port: 2222,
            base_url: "https://host.example:8443".into(),
            expected_tls_pin: Some(pin("ab")),
            extra_args: csr_extra_args(Some(&keypair.csr_base64())),
        };

        let BridgeMintRequest {
            request_id,
            purpose,
            host,
            ssh_port,
            base_url,
            expected_tls_pin,
            extra_args,
        } = req.clone();

        let mut crossing = vec![request_id, host, base_url, ssh_port.to_string()];
        crossing.push(format!("{purpose:?}"));
        crossing.extend(expected_tls_pin);
        crossing.extend(extra_args.clone());
        // ...and the derived rendering, which is where a `{:?}` in a log line
        // would pick things up.
        crossing.push(format!("{req:?}"));

        for field in &crossing {
            assert!(
                !field.contains(&key_b64),
                "private key DER crossed: {field}"
            );
            assert!(!field.contains("PRIVATE KEY"), "PEM key crossed: {field}");
            for line in key_pem.lines().filter(|l| !l.starts_with("-----")) {
                assert!(!field.contains(line), "private key body crossed: {field}");
            }
        }
        // The one sanctioned outbound crossing IS present — this test would pass
        // vacuously against a request that carried nothing at all.
        assert!(extra_args[0].contains(&keypair.csr_base64()));
    }

    /// **Every type exported to Dart, enumerated and vouched for.**
    ///
    /// Adding a name to `EXPORTED_TYPES` is an assertion by whoever adds it:
    /// *this type carries no private-key material, in any field, at any depth.*
    /// The test fails until that assertion is made, so a newly exported
    /// `EnrollmentMaterial { bytes: Vec<u8> }` cannot slip onto the FRB surface —
    /// which a name blacklist would have waved straight through, since nothing in
    /// that name looks like a key.
    ///
    /// Scans the COMMITTED generated glue (regenerated by `make frb-gen`), so the
    /// failure lands on the commit that widens the surface rather than in review.
    /// The blacklist below is kept as a second, independent layer: it catches a
    /// key-shaped FIELD added to an already-vouched-for type.
    #[test]
    fn the_generated_frb_surface_exports_no_key_type() {
        /// The public bridge surface. Sorted; `X_Variant` entries are the freezed
        /// arms FRB generates for a fielded Rust enum.
        const EXPORTED_TYPES: &[&str] = &[
            "BridgeAddServerPreview",
            "BridgeClient",
            "BridgeControlBundle",
            "BridgeCreateHandle",
            "BridgeCreateShedRequest",
            "BridgeCreateUpdate",
            "BridgeCreateUpdate_Complete",
            "BridgeCreateUpdate_Error",
            "BridgeCreateUpdate_Progress",
            "BridgeCredentialEvent",
            "BridgeCredentialEvent_Adopted",
            "BridgeCredentialEvent_ModeChanged",
            "BridgeDiskEntry",
            "BridgeDiskSize",
            "BridgeDiskTotals",
            "BridgeError",
            // Two Strings — a server NAME and a human detail. No key
            // material at any depth (plan 012 S5: absorbed with the shed-core
            // pin bump, where the variant is a server-identity + remedy pair).
            "BridgeError_AgentUpgradeRequired",
            "BridgeError_BadStatus",
            "BridgeError_Config",
            "BridgeError_Create",
            "BridgeError_Decode",
            "BridgeError_RcBadRequest",
            "BridgeError_RcFailed",
            "BridgeError_RcMissingBinary",
            "BridgeError_RcNotFound",
            "BridgeError_RcSlugTaken",
            "BridgeError_TokenAuthExpired",
            "BridgeError_TokenPinMismatch",
            "BridgeError_TokenPinMissing",
            "BridgeError_Transport",
            "BridgeLiveCounters",
            "BridgeMintOutcome",
            "BridgeMintOutcome_Failure",
            "BridgeMintOutcome_Success",
            "BridgeMintPurpose",
            "BridgeMintRequest",
            "BridgeOverlayEntry",
            "BridgeOverview",
            "BridgeOverviewServer",
            "BridgeOverviewShed",
            "BridgeRcActivity",
            "BridgeRcAgentInfo",
            "BridgeRcCapabilities",
            "BridgeRcEvent",
            "BridgeRcEvent_ActivityChanged",
            "BridgeRcEvent_HubUnavailable",
            "BridgeRcEvent_MessageAppended",
            "BridgeRcEvent_SessionUpdated",
            "BridgeRcEvent_ShedStopped",
            "BridgeRcFeedMessage",
            "BridgeRcFeedTool",
            "BridgeRcInvocation",
            "BridgeRcKind",
            "BridgeRcKind_ClaudeBroker",
            "BridgeRcKind_ClaudeRc",
            "BridgeRcKind_Codex",
            "BridgeRcKind_Cursor",
            "BridgeRcKind_Opencode",
            "BridgeRcKind_Other",
            "BridgeRcKind_Shell",
            "BridgeRcKindFeatures",
            "BridgeRcMessagesPage",
            "BridgeRcSession",
            "BridgeRcState",
            // Plan 013 S3m — the roost feed, replacing the machine hub's. Every
            // one carries TAB metadata only (roost's tab id, title, cwd, the
            // four agent axes, a viewport of text) plus a human reason string;
            // both handles are opaque and hold a channel or a socket, never
            // credentials. The SSH identity still never crosses this surface:
            // Dart owns the transport and hands Rust a loopback PORT.
            "BridgeRoostPeek",
            "BridgeRoostUpdate",
            "BridgeRoostUpdate_Down",
            "BridgeRoostUpdate_Snapshot",
            "BridgeRoostWatcher",
            "BridgeSession",
            "BridgeSessionRc",
            "BridgeShed",
            "BridgeShedImage",
            "BridgeShedStatus",
            "BridgeSystemDiskUsage",
            // One `tab.dump` frame: geometry, an optional cursor position, and
            // the visible rows as text. Read-only, and terminal text only.
            "BridgeTabDump",
            "BridgeTestSse",
            "BridgeWatcherHandle",
            "BridgeWatcherUpdate",
            "BridgeWatcherUpdate_Down",
            "BridgeWatcherUpdate_Event",
        ];

        let api = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .unwrap()
            .join("lib/src/rust/api");
        let mut files = Vec::new();
        collect_dart(&api, &mut files);
        assert!(
            files.len() > 3,
            "expected the committed FRB glue under {}",
            api.display()
        );

        // Layer 0 — the shape of the generated tree itself. The allowlist below
        // audits `api/`, so a type that appears OUTSIDE it would go unexamined.
        // That is not hypothetical: a generic type briefly living under
        // `crate::api` made the codegen emit a whole `lib.dart` exporting an
        // opaque `class T`, and nothing but this check would have noticed the
        // orphan (codegen adds files, it never removes them).
        let mut top: Vec<String> = std::fs::read_dir(api.parent().unwrap())
            .unwrap()
            .map(|e| e.unwrap().file_name().to_string_lossy().into_owned())
            .collect();
        top.sort();
        assert_eq!(
            top,
            vec![
                "api",
                "frb_generated.dart",
                "frb_generated.io.dart",
                "frb_generated.web.dart"
            ],
            "unexpected file(s) in the generated Dart tree — a stale artifact from \
             an earlier codegen, or a new module whose types this test does not audit"
        );

        // Layer 1 — the ALLOWLIST. Declared types must match the list exactly.
        let mut declared: Vec<String> = Vec::new();
        for (_, text) in &files {
            for line in text.lines() {
                let l = line.trim_start();
                if l.starts_with("//") {
                    continue;
                }
                for kw in ["abstract class ", "sealed class ", "class ", "enum "] {
                    if let Some(rest) = l.strip_prefix(kw) {
                        let name: String = rest
                            .chars()
                            .take_while(|c| c.is_alphanumeric() || *c == '_')
                            .collect();
                        // freezed's private mixins (`_$Foo`) are machinery for an
                        // already-listed type, not a surface of their own.
                        if !name.is_empty() && !name.starts_with('_') {
                            declared.push(name);
                        }
                        break;
                    }
                }
            }
        }
        declared.sort();
        declared.dedup();
        let allowed: Vec<String> = EXPORTED_TYPES.iter().map(|s| s.to_string()).collect();
        let added: Vec<&String> = declared.iter().filter(|d| !allowed.contains(d)).collect();
        assert!(
            added.is_empty(),
            "new type(s) on the FRB surface: {added:?}\n\
             Add each to EXPORTED_TYPES — doing so asserts it carries NO private-key \
             material in any field, at any depth (plan 002 §7 P3(a))."
        );
        let removed: Vec<&String> = allowed.iter().filter(|a| !declared.contains(a)).collect();
        assert!(
            removed.is_empty(),
            "EXPORTED_TYPES lists type(s) the surface no longer has: {removed:?} \
             (drop them from the list)"
        );

        // Layer 2 — the substring blacklist, over the whole generated tree. Catches
        // a key-shaped FIELD grafted onto a type the list already vouches for.
        // Case-insensitive: FRB renames snake_case to camelCase, so a
        // `key_pkcs8_der` field would appear as `keyPkcs8Der`.
        const FORBIDDEN: &[&str] = &[
            "clientkeypair",
            "privatekey",
            "private_key",
            "keypkcs8",
            "key_pkcs8",
            "keypem",
            "key_pem",
            "pkcs8",
            "private key",
        ];
        let mut all = Vec::new();
        collect_dart(api.parent().unwrap(), &mut all);
        for (path, text) in all {
            // CODE only. FRB copies Rust doc comments into the generated Dart, and
            // several of them talk ABOUT the private key precisely to record that
            // it does not cross — prose must not fail an audit of the surface.
            let code: String = text
                .lines()
                .filter(|l| !l.trim_start().starts_with("//"))
                .collect::<Vec<_>>()
                .join("\n")
                .to_lowercase();
            for needle in FORBIDDEN {
                assert!(
                    !code.contains(needle),
                    "{}: the FRB surface exposes {needle:?}",
                    path.display()
                );
            }
        }
    }

    /// **The parallelism rule, enforced instead of documented.**
    ///
    /// The bridge's mint machinery is process-global by design (one app-scoped
    /// sink, one pending map, one set of leak counters), and `cargo test` runs
    /// tests on many threads — so a test that touches any of it must hold
    /// `test_guard()`. Forgetting is not a local failure: registering a sink
    /// EVICTS the previous one, and eviction drains the pending map, so an
    /// unguarded test's parked request is resolved and removed by a neighbour
    /// that has nothing to do with it. That is a flake that reproduces on CI's
    /// machine shape and not on a developer's (run 30197516584), which is the
    /// worst kind to leave to a convention.
    ///
    /// So: any `#[test]` whose body mentions the shared state must also mention
    /// `test_guard()`. Cheap, mechanical, and it fails on the commit that
    /// introduces the omission rather than three CI runs later.
    #[test]
    fn every_test_touching_global_state_takes_the_guard() {
        /// Touching any of these means touching state another test can see.
        const GLOBAL_STATE: &[&str] = &[
            "pending()",
            "PENDING_MINTS",
            "PENDING_PREVIEW_CREDENTIALS",
            "submit_mint_result(",
            "install_sink_hook(",
            "install_mint_emitter(",
            "shutdown_mint_sink(",
            "MINT_SINK",
            "CRED_SINK",
            "live_counters(",
            "credential_events_for(",
            "preview_add_server(",
            "run_preview(",
            "build_provider(",
            "mint_credential(",
        ];
        // This test's own body quotes every marker above, so it would flag itself.
        const SELF: &str = "every_test_touching_global_state_takes_the_guard";

        let src = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("src/api");
        let mut offenders = Vec::new();
        let mut checked = 0usize;
        for name in ["mint.rs", "preview.rs", "client.rs"] {
            let text = std::fs::read_to_string(src.join(name)).unwrap();
            let tests = text
                .split_at(text.find("#[cfg(test)]").expect("a test module"))
                .1;
            for chunk in tests.split("\n    #[test]\n").skip(1) {
                // Stop at the end of the test fn so a helper defined after it is
                // not attributed to it.
                let body = chunk.split("\n    }\n").next().unwrap_or(chunk);
                let fn_name = body
                    .lines()
                    .find_map(|l| l.trim().strip_prefix("fn "))
                    .map(|l| l.split('(').next().unwrap_or("?").to_string())
                    .unwrap_or_else(|| "?".into());
                if fn_name == SELF {
                    continue;
                }
                checked += 1;
                let touches = GLOBAL_STATE.iter().any(|m| body.contains(m));
                if touches && !body.contains("test_guard()") {
                    offenders.push(format!("{name}::{fn_name}"));
                }
            }
        }
        assert!(checked > 30, "the scan found almost no tests ({checked})");
        assert!(
            offenders.is_empty(),
            "these tests touch process-global bridge state without `let _g = test_guard();`: \
             {offenders:?}\nSee testsupport::TEST_LOCK for why that is a race, not a style point."
        );
    }

    fn collect_dart(dir: &std::path::Path, out: &mut Vec<(std::path::PathBuf, String)>) {
        for entry in std::fs::read_dir(dir).expect("generated glue dir") {
            let path = entry.unwrap().path();
            if path.is_dir() {
                collect_dart(&path, out);
            } else if path.extension().is_some_and(|e| e == "dart") {
                out.push((path.clone(), std::fs::read_to_string(&path).unwrap()));
            }
        }
    }

    // ---- the add-server bundle parse: behavior inherited from Dart ----

    /// **A regression guard, not a cross-implementation parity test.**
    ///
    /// The add-server bundle parse used to live in Dart
    /// (`lib/control/token_bundle.dart:parseControlBundle`); M2 deleted it, and
    /// this Rust parse is now the only one. Two implementations no longer exist
    /// to compare, so nothing here can (or claims to) execute the Dart side.
    ///
    /// What it does instead is pin the BEHAVIOR that was handed over. Every case
    /// below is a fixture recorded from the deleted function's own test suite
    /// (`test/control/token_bundle_test.dart`, deleted in the same commit) with
    /// the decision it produced: which bundles it accepted, which it rejected,
    /// and with which error code. A change to `parse_control_bundle` upstream
    /// that quietly loosened one of those rules would land in mobile's
    /// first-contact path — the one place the app talks to a server the user has
    /// not trusted yet — and this is what fails when it does.
    ///
    /// Plus the two legs the Dart parser could not express, both required by plan
    /// 001 D4: an ABSENT `auth_mode` (a pre-mtls server) and the legacy
    /// `"secure"` spelling each decode as token, and an mtls bundle decodes to a
    /// certificate.
    #[test]
    fn the_add_server_parse_keeps_the_retired_dart_parsers_decisions() {
        let p = pin("ab");

        // Accepts a valid bundle (Dart: 'accepts a valid bundle').
        let b = parse_credential_or_control(&token_bundle(&p, None));
        let b = b.expect("valid bundle");
        assert_eq!(b.https_port, 8443);
        assert_eq!(b.tls_cert_fingerprint, p);
        assert_eq!(b.token, "secret-tok");
        // ABSENT auth_mode is TOKEN (plan 001 D4, compat leg 4) — the Dart parser
        // had no such field at all, so this is the leg that keeps a new client
        // working against a released server.
        assert_eq!(b.auth_mode, shed_core::token::AuthMode::Token);
        assert!(b.client_cert.is_empty());

        // The legacy "secure" spelling of token mode (plan 001 D1) — and any
        // other unrecognized value — is token, never mtls.
        for mode in ["secure", "token", "", "future-mode"] {
            let b = parse_credential_or_control(&token_bundle(&p, Some(mode)))
                .unwrap_or_else(|e| panic!("auth_mode {mode:?} rejected: {e:?}"));
            assert_eq!(
                b.auth_mode,
                shed_core::token::AuthMode::Token,
                "auth_mode {mode:?} must decode as token"
            );
            assert_eq!(b.token, "secret-tok");
        }

        // Requires the TLS fingerprint (Dart: SHED_TLS_PIN_MISSING).
        let no_fp = r#"{"scope":"control","token":"t","https_port":8443,"expires_at":"2030-01-01T00:00:00Z"}"#;
        assert_eq!(
            parse_credential_or_control(no_fp).unwrap_err(),
            TokenBundleError::PinMissing
        );

        // Rejects an out-of-range https_port (Dart: 70000 and 0).
        for port in ["70000", "0"] {
            let raw = format!(
                r#"{{"scope":"control","token":"t","tls_cert_fingerprint":"{p}","https_port":{port},"expires_at":"2030-01-01T00:00:00Z"}}"#
            );
            assert_eq!(
                parse_credential_or_control(&raw).unwrap_err(),
                TokenBundleError::AuthExpired,
                "https_port {port} must be rejected"
            );
        }

        // Enforces an expected pin (Dart: SHED_TLS_PIN_MISMATCH).
        assert_eq!(
            shed_core::token::parse_control_bundle(&token_bundle(&p, None), Some(&pin("cd")))
                .unwrap_err(),
            TokenBundleError::PinMismatch
        );

        // A blank token, a non-`control` scope and a missing expiry all fail
        // closed, exactly as the Dart parser did.
        for raw in [
            format!(
                r#"{{"scope":"control","token":"  ","tls_cert_fingerprint":"{p}","https_port":8443,"expires_at":"2030-01-01T00:00:00Z"}}"#
            ),
            format!(
                r#"{{"scope":"session","token":"t","tls_cert_fingerprint":"{p}","https_port":8443,"expires_at":"2030-01-01T00:00:00Z"}}"#
            ),
            format!(
                r#"{{"scope":"control","token":"t","tls_cert_fingerprint":"{p}","https_port":8443}}"#
            ),
            "not json".to_string(),
        ] {
            assert_eq!(
                parse_credential_or_control(&raw).unwrap_err(),
                TokenBundleError::AuthExpired,
                "must reject: {raw}"
            );
        }

        // NEW leg the Dart parser could not express: an mtls bundle carries a
        // certificate instead of a token, and everything else is identical.
        let kp = shed_core::csr::ClientKeyPair::generate().unwrap();
        let cert = TestCa::new().sign_csr_base64(&kp.csr_base64());
        let b = parse_credential_or_control(&mtls_bundle(&p, &cert)).expect("mtls bundle");
        assert_eq!(b.auth_mode, shed_core::token::AuthMode::Mtls);
        assert!(b.token.is_empty());
        assert!(b.client_cert.contains("BEGIN CERTIFICATE"));
        assert_eq!(b.cert_serial, "2a");
        assert_eq!(b.https_port, 8443);
        assert_eq!(b.tls_cert_fingerprint, p);

        // ...and an mtls bundle with NO usable certificate is refused rather than
        // adopted as an empty credential.
        let broken = mtls_bundle(
            &p,
            "-----BEGIN CERTIFICATE-----\n!!!\n-----END CERTIFICATE-----",
        );
        assert_eq!(
            parse_credential_or_control(&broken).unwrap_err(),
            TokenBundleError::AuthExpired
        );
    }

    /// The add-server parse under test, with no pin configured (first contact).
    fn parse_credential_or_control(raw: &str) -> Result<ControlBundle, TokenBundleError> {
        shed_core::token::parse_control_bundle(raw, None)
    }
}
