// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `bridge_rt`, `next_id`

/// Read the current live-resource counters.
Future<BridgeLiveCounters> liveCounters() =>
    RustLib.instance.api.crateApiBridgeRtLiveCounters();

/// Snapshot of the live-resource counters (plan AC#2). A Dart integration test
/// asserts every field is 0 after disposing each slice's resources.
class BridgeLiveCounters {
  final BigInt activeWatchers;
  final BigInt activeForwarders;
  final BigInt activeCreateStreams;
  final BigInt pendingMints;

  const BridgeLiveCounters({
    required this.activeWatchers,
    required this.activeForwarders,
    required this.activeCreateStreams,
    required this.pendingMints,
  });

  @override
  int get hashCode =>
      activeWatchers.hashCode ^
      activeForwarders.hashCode ^
      activeCreateStreams.hashCode ^
      pendingMints.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeLiveCounters &&
          runtimeType == other.runtimeType &&
          activeWatchers == other.activeWatchers &&
          activeForwarders == other.activeForwarders &&
          activeCreateStreams == other.activeCreateStreams &&
          pendingMints == other.pendingMints;
}
