// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.5.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'dto.dart';
import 'dto_rc.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `inner`, `run`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BridgeClient>>
abstract class BridgeClient implements RustOpaqueInterface {
  /// Build a secure, provider-backed client for one host (the production
  /// path). `tls_pin` (`sha256:<hex>`) enables leaf pinning on the https
  /// `base_url`; `host`/`ssh_port` are the SSH transport identity the mint
  /// inversion dials; `seed_token`/`seed_expiry_unix`, when present, prime the
  /// provider so the first request skips a mint. Fails with
  /// [`BridgeError::Config`] on a pin/URL mismatch (fail-closed).
  static Future<BridgeClient> connect({
    required String baseUrl,
    required String serverName,
    required String host,
    required int sshPort,
    String? tlsPin,
    String? seedToken,
    BigInt? seedExpiryUnix,
  }) => RustLib.instance.api.crateApiClientBridgeClientConnect(
    baseUrl: baseUrl,
    serverName: serverName,
    host: host,
    sshPort: sshPort,
    tlsPin: tlsPin,
    seedToken: seedToken,
    seedExpiryUnix: seedExpiryUnix,
  );

  /// Build an OPEN-mode client (no minter, empty token) against `base_url`.
  /// Used by the hermetic slice tests (a local plaintext SSE server that
  /// ignores auth) and any future open-mode server; the production app uses
  /// [`BridgeClient::connect`].
  static Future<BridgeClient> connectOpen({
    required String baseUrl,
    required String serverName,
  }) => RustLib.instance.api.crateApiClientBridgeClientConnectOpen(
    baseUrl: baseUrl,
    serverName: serverName,
  );

  Future<void> delete({required String name});

  Future<void> deleteSession({required String shed, required String session});

  Future<List<BridgeShedImage>> listImages();

  Future<List<BridgeSession>> listSessions({required String shed});

  Future<List<BridgeShed>> listSheds();

  Future<BridgeOverview> overview();

  Future<void> rcInput({
    required String shed,
    required String slug,
    required String text,
  });

  Future<BridgeRcMessagesPage> rcMessages({
    required String shed,
    required String slug,
    required BigInt since,
    int? limit,
  });

  Future<void> reset({required String name});

  Future<void> start({required String name});

  Future<void> stop({required String name});

  Future<BridgeSystemDiskUsage> systemDf();
}
