// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.5.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'dto_lane.dart';
import 'dto_rc.dart';
import 'lane.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `apply`, `apply`, `call`, `closed_error`, `empty`, `empty`, `fold`, `forward_loop`, `is_closed`, `lock`, `new`, `offline`, `open_on`, `roster_pump`, `snapshot`, `spawn_forwarder`, `teardown`, `touch`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CrazeView`, `Cut`, `Pending`, `SourceInner`, `SourceState`, `SourceTasks`, `Staged`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `drop`, `drop`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// The command the craze tunnel execs on the far side, verbatim — craze's
/// published ladder ending in `craze bridge --hub`, plus the exec-only PATH
/// (`shed_core::craze::bridge_hub_command`, plan 025 §3.4).
///
/// **Dart composes no part of it**, for [`super::roost::roost_remote_command`]'s
/// reason: which rung wins and how the script is quoted is pinned by shed's
/// `tests/machine-transport` corpus, through a real sshd, and a second
/// composition here could only drift from it.
String crazeRemoteCommand() =>
    RustLib.instance.api.crateApiCrazeCrazeRemoteCommand();

/// **Test mode only**: the JAILED bridge argv (`shed_core::craze::
/// bridge_hub_argv_jailed` — `["sh", "-c", <rungs 1–2 only, no exec PATH>]`).
///
/// The hermetic harness (`integration_test/craze_test.dart`) runs its craze
/// tunnel as a local process over this, under craze's recipe environment, so a
/// craze installed on the host running the tests — an absolute rung, an
/// injected Homebrew directory — can never answer a hermetic cell. No
/// production transport sends it; the shipped feed execs
/// [`craze_remote_command`].
List<String> crazeJailedBridgeArgv() =>
    RustLib.instance.api.crateApiCrazeCrazeJailedBridgeArgv();

/// A fresh create request id in craze's form (`shed_craze::new_request_id`):
/// minted for a submission, and reused ONLY while that submission's outcome is
/// unknown (plan 025 §3.8).
String crazeNewRequestId() =>
    RustLib.instance.api.crateApiCrazeCrazeNewRequestId();

/// **The row merge for ONE machine** (plan 025 §3.6.3, D4) —
/// `shed_app::craze_rows::fold_plan`, the rule the desktop runs, called rather
/// than re-derived.
///
/// `hub` is the machine's craze rows **only while its craze feed is live**, and
/// `None` otherwise (offline, never reached): a feed that is not live absorbs
/// nothing, so roost's craze rows stand alone exactly as they would with no
/// craze source at all. With a live feed EVERY craze-owned tab is absorbed —
/// attached to the hub row whose `provider_session_id` it names (two tabs of one
/// session: the newest attaches; two rows claiming one session: the newer
/// `since`/`startedAt`, ties to the greater hostId), or hidden when no row names
/// it. A fold never crosses machines: the caller passes one machine's tabs and
/// that machine's rows.
BridgeFoldPlan crazeFoldPlan({
  required List<BridgeRoostTabRef> roost,
  List<BridgeLaneSession>? hub,
}) => RustLib.instance.api.crateApiCrazeCrazeFoldPlan(roost: roost, hub: hub);

/// **Open one machine's craze source** on the craze tunnel's local port: a
/// `CrazeSource` over `TcpDial(port)`, and the pump folding its events into the
/// staged view.
///
/// Returns at once. The source dials on its own schedule — a machine with no
/// craze, or one asleep, is the snapshot's `offline`, never this call's error —
/// and keeps redialling with shed-craze's backoff for as long as the handle is
/// open.
///
/// `machine` names the source in a refusal; it is not dialled.
Future<BridgeCrazeSource> crazeSourceOpen({
  required String machine,
  required int port,
}) => RustLib.instance.api.crateApiCrazeCrazeSourceOpen(
  machine: machine,
  port: port,
);

/// Stream this source's nudges. **One claim**: a second call on the same handle
/// is a no-op rather than a silent split. The stream stays open until
/// [`craze_source_close`].
Stream<bool> crazeSourceNudges({required BridgeCrazeSource src}) =>
    RustLib.instance.api.crateApiCrazeCrazeSourceNudges(src: src);

/// **The one read**, and the nudge acknowledgement: the staged view, the
/// created rows and Dart's note, projected under ONE lock with the dirty bit
/// cleared.
///
/// The dirty bit is cleared BEFORE the created rows are read, under the same
/// guard: a created row the source lets go after this read raises the next
/// nudge, and one it let go before is already absent from the answer. A closed
/// source still projects its last view.
BridgeCrazeSnapshot crazeSourceSnapshot({required BridgeCrazeSource src}) =>
    RustLib.instance.api.crateApiCrazeCrazeSourceSnapshot(src: src);

/// **Dart's class for a failure before `hello`** (the module doc): what the
/// craze tunnel's stderr said — `NotInstalled` (the ladder's `craze: command
/// not found`) or `TooOld` (v0.0.1's `unknown flag: --hub`) — with the far
/// side's line. The snapshot's `offline` carries it in place of an
/// `Unreachable` until a seed proves the far side answers.
void crazeSourceNoteReach({
  required BridgeCrazeSource src,
  required BridgeSourceOffline cause,
  required String message,
}) => RustLib.instance.api.crateApiCrazeCrazeSourceNoteReach(
  src: src,
  cause: cause,
  message: message,
);

/// What a create can start on this machine — craze's `sessions.createOptions`,
/// on a connection of its own (each call is its own exec of the bridge, which
/// Ensures a hub: an explicit user action). Providers in craze's order, the
/// default as craze states it, the recent directories newest first.
Future<BridgeLaneCreateOptions> crazeCreateOptions({
  required BridgeCrazeSource src,
}) => RustLib.instance.api.crateApiCrazeCrazeCreateOptions(src: src);

/// Create a session — craze's `session.create{cwd, provider?, prompt?,
/// requestId}`, on a connection of its own, retried once under the same id
/// when its outcome is unknown (shed-craze's rule, plan 025 §3.3.3).
///
/// The new session's row is the source's at once (its created rows): this
/// handle is nudged, so the row is listed — and a lane opens on its hostId —
/// before the roster has caught up.
///
/// **What a refusal tells the caller about its request id** (plan 025 §3.8):
/// [`BridgeLaneError::OutcomeUnknown`] — the answer was lost twice, or this
/// handle was closed while the create was in flight — is the one refusal after
/// which the caller keeps the id, because craze may have started the session
/// and answers a retry under that id with it. Every other refusal is definite,
/// a source closed before the create began included (nothing was sent): the
/// next submission mints a new id.
Future<BridgeLaneCreated> crazeCreate({
  required BridgeCrazeSource src,
  required BridgeLaneCreateRequest request,
}) => RustLib.instance.api.crateApiCrazeCrazeCreate(src: src, request: request);

/// **Open one craze session's transcript** — the source's lane on `host_id`
/// (the row's id, P11), as the SAME [`BridgeLane`] an opencode lane is, so every
/// `lane_*` verb serves it.
///
/// No forward and no stamp: the lane reaches its session through the hub's
/// splice over this source's own dial, one connection of its own (D10). It binds
/// the row (and its craze session id) the source holds — a roster's or a
/// create's — and a hostId the source has never listed is `UnknownSession`. A
/// CLOSED source refuses with `Unavailable` — transient, see the body.
/// Opened through the source, the lane says its session's end back to it, which
/// is what lets a created row go (Amendment A16).
Future<BridgeLane> crazeLaneOpen({
  required BridgeCrazeSource src,
  required String hostId,
}) => RustLib.instance.api.crateApiCrazeCrazeLaneOpen(src: src, hostId: hostId);

/// End the source — the SYNCHRONOUS co-primary teardown. Idempotent; `Drop` is
/// the backstop. Call it BEFORE cancelling the nudge stream: the stream ends
/// here, and a cancel awaited first never completes (the lane's rule).
void crazeSourceClose({required BridgeCrazeSource src}) =>
    RustLib.instance.api.crateApiCrazeCrazeSourceClose(src: src);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BridgeCrazeSource>>
abstract class BridgeCrazeSource implements RustOpaqueInterface {}

/// Why a source is offline, and its own words for it.
class BridgeCrazeOffline {
  final BridgeSourceOffline cause;
  final String reason;

  const BridgeCrazeOffline({required this.cause, required this.reason});

  @override
  int get hashCode => cause.hashCode ^ reason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeCrazeOffline &&
          runtimeType == other.runtimeType &&
          cause == other.cause &&
          reason == other.reason;
}

/// **One machine's craze source, as one atomic read** — what
/// [`craze_source_snapshot`] answers.
///
/// * `rows` — the sessions the source holds, by hostId (P11): the roster's
///   swapped-in rows, then the rows only a create answered with (not yet
///   listed by the roster, unexpired). While the source is not `live` these
///   are the LAST KNOWN rows, and a client renders them stale (§3.6.2).
/// * `live` — a roster seed is swapped in and its connection is following the
///   hub. The row merge absorbs roost's craze tabs only while this is true.
/// * `offline` — why it is not live, once it has said; `None` while it has
///   never said anything (connecting). `NotInstalled` is QUIET (the machine
///   simply has no craze); `TooOld` asks the person to update craze there.
/// * `caps` — what a create may do here (`create`, `create_options`), from
///   the hub's `hello`; `None` until a seed carried them.
/// * `truncated` — the hub cut its roster to a bound of its own.
class BridgeCrazeSnapshot {
  final List<BridgeLaneSession> rows;
  final bool live;
  final BridgeCrazeOffline? offline;
  final BridgeSourceCapabilities? caps;
  final bool truncated;

  const BridgeCrazeSnapshot({
    required this.rows,
    required this.live,
    this.offline,
    this.caps,
    required this.truncated,
  });

  @override
  int get hashCode =>
      rows.hashCode ^
      live.hashCode ^
      offline.hashCode ^
      caps.hashCode ^
      truncated.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeCrazeSnapshot &&
          runtimeType == other.runtimeType &&
          rows == other.rows &&
          live == other.live &&
          offline == other.offline &&
          caps == other.caps &&
          truncated == other.truncated;
}

/// What the merge decided for one machine (mirrors
/// `shed_app::craze_rows::FoldPlan`): every roost tab it folds away, in tab id
/// order — at most one per hub row absorbed (the newest), the rest hidden. A tab
/// in this list is NOT shown as a roost row.
class BridgeFoldPlan {
  final List<BridgeFoldedTab> folded;

  const BridgeFoldPlan({required this.folded});

  @override
  int get hashCode => folded.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeFoldPlan &&
          runtimeType == other.runtimeType &&
          folded == other.folded;
}

/// One roost tab the merge folds away: ABSORBED into the hub row `host_id`
/// names (that row then carries the tab's id), or HIDDEN (`None`) — a craze tab
/// the live roster names no row for. One list rather than `FoldPlan`'s map and
/// set: FRB would have to invent a Dart shape for a map, and it carries a
/// `Vec<i64>` across as a typed list of `BigInt`s.
class BridgeFoldedTab {
  final PlatformInt64 tabId;
  final String? hostId;

  const BridgeFoldedTab({required this.tabId, this.hostId});

  @override
  int get hashCode => tabId.hashCode ^ hostId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeFoldedTab &&
          runtimeType == other.runtimeType &&
          tabId == other.tabId &&
          hostId == other.hostId;
}

/// One roost tab on the machine being folded, as the merge needs it (mirrors
/// `shed_app::craze_rows::RoostTabRef`).
///
/// `craze_owner` is `Some(X)` **only** for a tab roost reports as craze's
/// (`kind == Craze`), `X` being its ownership session id — the provider session
/// a craze TUI claimed (a roost row's `rc_id`). `None` for every other tab,
/// whatever its session id says: a tab of another source whose id happens to
/// equal `X` is never absorbed.
class BridgeRoostTabRef {
  final PlatformInt64 tabId;
  final String? crazeOwner;

  const BridgeRoostTabRef({required this.tabId, this.crazeOwner});

  @override
  int get hashCode => tabId.hashCode ^ crazeOwner.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRoostTabRef &&
          runtimeType == other.runtimeType &&
          tabId == other.tabId &&
          crazeOwner == other.crazeOwner;
}
