// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ForwardingCreateSink`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `drop`, `on_complete`, `on_error`, `on_progress`

/// Step 1: stand up the local SSE server, returning the bridge-owned opaque
/// handle (Dart holds it for cancellation). The create isn't started until
/// `create_shed_events` supplies the sink.
Future<BridgeCreateHandle> createShedStream() =>
    RustLib.instance.api.crateApiCreateStreamCreateShedStream();

/// Step 2: run `create_shed` against the handle's SSE server, forwarding progress
/// → a Dart `Stream`. FRB renders this (a `StreamSink` param) as
/// `Stream<BridgeCreateUpdate>`.
Stream<BridgeCreateUpdate> createShedEvents({
  required BridgeCreateHandle handle,
}) => RustLib.instance.api.crateApiCreateStreamCreateShedEvents(handle: handle);

/// Explicit synchronous cancel (idempotent) — belt-and-suspenders alongside Drop.
Future<void> cancelCreate({required BridgeCreateHandle handle}) =>
    RustLib.instance.api.crateApiCreateStreamCancelCreate(handle: handle);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BridgeCreateHandle>>
abstract class BridgeCreateHandle implements RustOpaqueInterface {
  /// Idempotent synchronous cancel (belt-and-suspenders alongside Drop):
  /// aborts the in-flight create + the SSE server and decrements the counter.
  Future<void> cancel();
}

/// One create-stream update marshalled to Dart. `kind` is
/// `"progress"`/`"complete"`/`"error"`.
class BridgeCreateUpdate {
  final String kind;
  final String message;
  final String name;

  const BridgeCreateUpdate({
    required this.kind,
    required this.message,
    required this.name,
  });

  @override
  int get hashCode => kind.hashCode ^ message.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeCreateUpdate &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          message == other.message &&
          name == other.name;
}
