// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.5.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'client.dart';
import 'dto.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'create_stream.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `teardown`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CreateInner`, `ForwardingCreateSink`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `drop`, `eq`, `fmt`, `from`, `on_complete`, `on_error`, `on_progress`

/// Step 1: stash the client + request, returning the bridge-owned opaque handle.
/// The create isn't started until [`create_shed_events`] supplies the sink.
Future<BridgeCreateHandle> createShedStream({
  required BridgeClient client,
  required BridgeCreateShedRequest req,
}) => RustLib.instance.api.crateApiCreateStreamCreateShedStream(
  client: client,
  req: req,
);

/// Step 2: run `create_shed` against the handle's client, forwarding progress →
/// a Dart `Stream`. Refuses to start if cancelled or already started (Codex #7).
Stream<BridgeCreateUpdate> createShedEvents({
  required BridgeCreateHandle handle,
}) => RustLib.instance.api.crateApiCreateStreamCreateShedEvents(handle: handle);

/// Explicit SYNCHRONOUS cancel (idempotent, co-primary with Drop). Dart calls
/// this from `onDispose` (Codex #9).
void cancelCreate({required BridgeCreateHandle handle}) =>
    RustLib.instance.api.crateApiCreateStreamCancelCreate(handle: handle);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BridgeCreateHandle>>
abstract class BridgeCreateHandle implements RustOpaqueInterface {}

/// The create request Dart passes (mirrors `models::CreateShedRequest`).
class BridgeCreateShedRequest {
  final String name;
  final String? repo;
  final String? localDir;
  final String? image;
  final String? backend;
  final PlatformInt64? cpus;
  final PlatformInt64? memoryMb;
  final bool? noProvision;

  const BridgeCreateShedRequest({
    required this.name,
    this.repo,
    this.localDir,
    this.image,
    this.backend,
    this.cpus,
    this.memoryMb,
    this.noProvision,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      repo.hashCode ^
      localDir.hashCode ^
      image.hashCode ^
      backend.hashCode ^
      cpus.hashCode ^
      memoryMb.hashCode ^
      noProvision.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeCreateShedRequest &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          repo == other.repo &&
          localDir == other.localDir &&
          image == other.image &&
          backend == other.backend &&
          cpus == other.cpus &&
          memoryMb == other.memoryMb &&
          noProvision == other.noProvision;
}

@freezed
sealed class BridgeCreateUpdate with _$BridgeCreateUpdate {
  const BridgeCreateUpdate._();

  const factory BridgeCreateUpdate.progress({required String message}) =
      BridgeCreateUpdate_Progress;
  const factory BridgeCreateUpdate.complete({required BridgeShed shed}) =
      BridgeCreateUpdate_Complete;
  const factory BridgeCreateUpdate.error({required String message}) =
      BridgeCreateUpdate_Error;
}
