// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.5.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'dto_rc.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

/// One image/shed/orphan disk row (mirrors `models::DiskEntry`).
class BridgeDiskEntry {
  final String name;
  final String? dockerRef;
  final BridgeDiskSize size;

  const BridgeDiskEntry({
    required this.name,
    this.dockerRef,
    required this.size,
  });

  @override
  int get hashCode => name.hashCode ^ dockerRef.hashCode ^ size.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeDiskEntry &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          dockerRef == other.dockerRef &&
          size == other.size;
}

/// A logical/physical byte pair (mirrors `models::DiskSize`).
class BridgeDiskSize {
  final PlatformInt64 logicalBytes;
  final PlatformInt64 physicalBytes;

  const BridgeDiskSize({
    required this.logicalBytes,
    required this.physicalBytes,
  });

  @override
  int get hashCode => logicalBytes.hashCode ^ physicalBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeDiskSize &&
          runtimeType == other.runtimeType &&
          logicalBytes == other.logicalBytes &&
          physicalBytes == other.physicalBytes;
}

/// The per-category totals (mirrors `models::DiskTotals`).
class BridgeDiskTotals {
  final BridgeDiskSize images;
  final BridgeDiskSize sheds;
  final BridgeDiskSize snapshots;
  final BridgeDiskSize orphans;
  final BridgeDiskSize all;

  const BridgeDiskTotals({
    required this.images,
    required this.sheds,
    required this.snapshots,
    required this.orphans,
    required this.all,
  });

  @override
  int get hashCode =>
      images.hashCode ^
      sheds.hashCode ^
      snapshots.hashCode ^
      orphans.hashCode ^
      all.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeDiskTotals &&
          runtimeType == other.runtimeType &&
          images == other.images &&
          sheds == other.sheds &&
          snapshots == other.snapshots &&
          orphans == other.orphans &&
          all == other.all;
}

/// `GET /api/overview` (mirrors `models::Overview`).
class BridgeOverview {
  final BridgeOverviewServer server;
  final BridgeSystemDiskUsage? df;
  final List<BridgeOverviewShed> sheds;
  final List<String> warnings;

  const BridgeOverview({
    required this.server,
    this.df,
    required this.sheds,
    required this.warnings,
  });

  @override
  int get hashCode =>
      server.hashCode ^ df.hashCode ^ sheds.hashCode ^ warnings.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeOverview &&
          runtimeType == other.runtimeType &&
          server == other.server &&
          df == other.df &&
          sheds == other.sheds &&
          warnings == other.warnings;
}

/// The server block of an overview (mirrors `models::OverviewServer`).
class BridgeOverviewServer {
  final String version;
  final List<String> features;

  const BridgeOverviewServer({required this.version, required this.features});

  @override
  int get hashCode => version.hashCode ^ features.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeOverviewServer &&
          runtimeType == other.runtimeType &&
          version == other.version &&
          features == other.features;
}

/// One shed-with-its-rc-sessions overview row (mirrors `models::OverviewShed`).
class BridgeOverviewShed {
  final BridgeShed shed;
  final List<BridgeRcSession> sessions;
  final BridgeRcCapabilities? capabilities;

  const BridgeOverviewShed({
    required this.shed,
    required this.sessions,
    this.capabilities,
  });

  @override
  int get hashCode => shed.hashCode ^ sessions.hashCode ^ capabilities.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeOverviewShed &&
          runtimeType == other.runtimeType &&
          shed == other.shed &&
          sessions == other.sessions &&
          capabilities == other.capabilities;
}

/// One `GET /api/sheds/{name}/sessions` row (mirrors `models::Session`).
class BridgeSession {
  final String name;
  final String shedName;
  final String? serverName;
  final String? createdAt;
  final bool attached;
  final PlatformInt64 windowCount;
  final BridgeSessionRc? rc;

  const BridgeSession({
    required this.name,
    required this.shedName,
    this.serverName,
    this.createdAt,
    required this.attached,
    required this.windowCount,
    this.rc,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      shedName.hashCode ^
      serverName.hashCode ^
      createdAt.hashCode ^
      attached.hashCode ^
      windowCount.hashCode ^
      rc.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeSession &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          shedName == other.shedName &&
          serverName == other.serverName &&
          createdAt == other.createdAt &&
          attached == other.attached &&
          windowCount == other.windowCount &&
          rc == other.rc;
}

/// The rc display subset inside a [`BridgeSession`] (mirrors `models::SessionRC`;
/// raw wire strings, not the enriched rc model).
class BridgeSessionRc {
  final String? kind;
  final String? state;
  final bool managed;
  final String? displayName;
  final String? url;
  final String? createdBy;
  final String? activity;
  final String? activityAt;
  final String? lastMessage;

  const BridgeSessionRc({
    this.kind,
    this.state,
    required this.managed,
    this.displayName,
    this.url,
    this.createdBy,
    this.activity,
    this.activityAt,
    this.lastMessage,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      state.hashCode ^
      managed.hashCode ^
      displayName.hashCode ^
      url.hashCode ^
      createdBy.hashCode ^
      activity.hashCode ^
      activityAt.hashCode ^
      lastMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeSessionRc &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          state == other.state &&
          managed == other.managed &&
          displayName == other.displayName &&
          url == other.url &&
          createdBy == other.createdBy &&
          activity == other.activity &&
          activityAt == other.activityAt &&
          lastMessage == other.lastMessage;
}

/// One shed (mirrors `models::Shed`).
class BridgeShed {
  final String host;
  final String name;
  final BridgeShedStatus status;
  final String? backend;
  final String? repo;
  final String? image;
  final String? imageDigest;
  final String? localDir;
  final String? ipAddress;
  final PlatformInt64? cpus;
  final PlatformInt64? memoryMb;
  final String? createdAt;
  final String? startedAt;
  final List<String> activeNamespaces;

  const BridgeShed({
    required this.host,
    required this.name,
    required this.status,
    this.backend,
    this.repo,
    this.image,
    this.imageDigest,
    this.localDir,
    this.ipAddress,
    this.cpus,
    this.memoryMb,
    this.createdAt,
    this.startedAt,
    required this.activeNamespaces,
  });

  @override
  int get hashCode =>
      host.hashCode ^
      name.hashCode ^
      status.hashCode ^
      backend.hashCode ^
      repo.hashCode ^
      image.hashCode ^
      imageDigest.hashCode ^
      localDir.hashCode ^
      ipAddress.hashCode ^
      cpus.hashCode ^
      memoryMb.hashCode ^
      createdAt.hashCode ^
      startedAt.hashCode ^
      activeNamespaces.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeShed &&
          runtimeType == other.runtimeType &&
          host == other.host &&
          name == other.name &&
          status == other.status &&
          backend == other.backend &&
          repo == other.repo &&
          image == other.image &&
          imageDigest == other.imageDigest &&
          localDir == other.localDir &&
          ipAddress == other.ipAddress &&
          cpus == other.cpus &&
          memoryMb == other.memoryMb &&
          createdAt == other.createdAt &&
          startedAt == other.startedAt &&
          activeNamespaces == other.activeNamespaces;
}

/// One image (mirrors `models::ShedImage`).
class BridgeShedImage {
  final String name;
  final String? dockerRef;
  final String? alias;
  final bool isDefault;
  final bool cached;
  final bool inUse;
  final String? digest;
  final String? source;
  final PlatformInt64 sizeBytes;

  const BridgeShedImage({
    required this.name,
    this.dockerRef,
    this.alias,
    required this.isDefault,
    required this.cached,
    required this.inUse,
    this.digest,
    this.source,
    required this.sizeBytes,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      dockerRef.hashCode ^
      alias.hashCode ^
      isDefault.hashCode ^
      cached.hashCode ^
      inUse.hashCode ^
      digest.hashCode ^
      source.hashCode ^
      sizeBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeShedImage &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          dockerRef == other.dockerRef &&
          alias == other.alias &&
          isDefault == other.isDefault &&
          cached == other.cached &&
          inUse == other.inUse &&
          digest == other.digest &&
          source == other.source &&
          sizeBytes == other.sizeBytes;
}

/// A shed's lifecycle status (mirrors `ShedStatus`; an unknown wire value folds
/// to `Unknown`). A plain fieldless enum → a plain Dart enum.
enum BridgeShedStatus { running, stopped, starting, error, unknown }

/// `GET /api/system/df` (mirrors `models::SystemDiskUsage`).
class BridgeSystemDiskUsage {
  final String? serverName;
  final String? backend;
  final List<BridgeDiskEntry> images;
  final List<BridgeDiskEntry> sheds;
  final List<BridgeDiskEntry> orphans;
  final BridgeDiskTotals totals;

  const BridgeSystemDiskUsage({
    this.serverName,
    this.backend,
    required this.images,
    required this.sheds,
    required this.orphans,
    required this.totals,
  });

  @override
  int get hashCode =>
      serverName.hashCode ^
      backend.hashCode ^
      images.hashCode ^
      sheds.hashCode ^
      orphans.hashCode ^
      totals.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeSystemDiskUsage &&
          runtimeType == other.runtimeType &&
          serverName == other.serverName &&
          backend == other.backend &&
          images == other.images &&
          sheds == other.sheds &&
          orphans == other.orphans &&
          totals == other.totals;
}
