// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.5.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'dto_rc.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'dto_lane.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `from_view`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

/// Whether this approval is still waiting on the human — **the only predicate a
/// client gates its answer affordance on**.
///
/// Exposed as a function rather than mirrored as a Dart `switch` because the
/// contract's answer for the case that matters is counter-intuitive:
/// [`BridgeLaneApprovalStatus::Other`] answers `false`. An unknown status is at
/// least as likely to be terminal (`cancelled`, `expired`) as live, so offering
/// buttons for it would post an answer the agent has stopped listening for. A
/// Dart re-derivation would very plausibly write `status != Resolved` and get
/// that backwards.
///
/// Sync: it is a `match` on a value Dart already holds.
bool laneStatusIsPending({required BridgeLaneApprovalStatus status}) =>
    RustLib.instance.api.crateApiDtoLaneLaneStatusIsPending(status: status);

/// The offered option a [`BridgeLaneDecision`] selects — **by
/// [`BridgeLaneApprovalOption::kind`], never by id**.
///
/// This calls [`LaneApproval::option_for`], which is the contract's ONE
/// implementation of correction 3, so gx, opencode and this phone cannot each
/// re-derive the clauses differently. The clause that makes re-derivation a real
/// hazard: a live gx leader offers FIVE permission options of which TWO declare
/// `allow_once`, so an exact-kind match that is AMBIGUOUS answers `None` rather
/// than picking — under the original "first in offered order wins" rule a human
/// tapping "Allow once" would have silently turned prompting off for the whole
/// session. The `Reject` decision alone falls back to the first option whose
/// kind starts `reject`, because a refusal broader than asked for is safe in a
/// way a broader allow is not.
///
/// `None` is not an error: it means this decision cannot name an option on this
/// approval, and the panel should post [`BridgeLaneAnswer::Choice`] with the
/// exact offered id instead — which is unambiguous by construction and what a
/// capability-driven panel already does.
///
/// Sync, and it takes the approval BY VALUE: Dart is holding the approval from
/// its last snapshot, there is no lane to look it up on, and nothing here does
/// I/O.
BridgeLaneApprovalOption? laneOptionFor({
  required BridgeLaneApproval approval,
  required BridgeLaneDecision decision,
}) => RustLib.instance.api.crateApiDtoLaneLaneOptionFor(
  approval: approval,
  decision: decision,
);

/// Where a row's agent lane is and which adapter speaks to it (mirrors
/// `roost::AgentLaneStamp`) — the whole of what [`super::lane::lane_open`]
/// needs.
///
/// **`server_url` is the REPORTED url**, never a dial url. On a remote machine
/// the phone dials its own fixed loopback port instead (plan 018 §3.10), and the
/// two are never conflated.
class BridgeAgentLaneStamp {
  /// The adapter token — `"opencode"` today. A kind this build has
  /// no adapter for is refused BY NAME
  /// ([`BridgeLaneError::UnsupportedLane`]), never silently rendered as no
  /// lane: `AgentLaneStamp`'s own doc makes that the client's obligation.
  final String kind;

  /// The AGENT's own session id — the address every lane verb takes.
  final String sessionId;
  final String serverUrl;

  const BridgeAgentLaneStamp({
    required this.kind,
    required this.sessionId,
    required this.serverUrl,
  });

  @override
  int get hashCode => kind.hashCode ^ sessionId.hashCode ^ serverUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeAgentLaneStamp &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          sessionId == other.sessionId &&
          serverUrl == other.serverUrl;
}

@freezed
sealed class BridgeLaneAnswer with _$BridgeLaneAnswer {
  const BridgeLaneAnswer._();

  const factory BridgeLaneAnswer.permission({
    required BridgeLaneDecision decision,
  }) = BridgeLaneAnswer_Permission;
  const factory BridgeLaneAnswer.choice({required String optionId}) =
      BridgeLaneAnswer_Choice;
  const factory BridgeLaneAnswer.question({
    required List<List<String>> answers,

    /// Free text per question, positional like `answers`; `None` where the
    /// human typed nothing. Empty list = no free text anywhere.
    ///
    /// A `Vec<Option<String>>` — `List<String?>` in Dart — is the one
    /// genuinely awkward shape in this mirror, and it is load-bearing: a
    /// `None` and a `Some("")` are different answers, and flattening the
    /// hole would lose which question the text was for. The adapter refuses
    /// text aimed at a question whose `custom` is false, so a panel that
    /// gates its text field on [`BridgeLaneQuestion::custom`] never sends
    /// one that will be refused.
    required List<String?> customText,
  }) = BridgeLaneAnswer_Question;

  /// Decline the whole request — distinct from a permission's
  /// [`BridgeLaneDecision::Reject`], which is one option among three.
  const factory BridgeLaneAnswer.reject() = BridgeLaneAnswer_Reject;

  /// A body the contract does not model, as raw JSON — the escape hatch for
  /// an unknown [`BridgeLaneApprovalKind`]. Note what it is NOT: an escape arm
  /// for an unknown ANSWER SHAPE. The four cases above are the whole
  /// vocabulary; this one carries a payload for a request kind, chosen
  /// deliberately by a client that read `request_json`.
  const factory BridgeLaneAnswer.raw({required String json}) =
      BridgeLaneAnswer_Raw;
}

/// One thing waiting on the human (mirrors `lane::LaneApproval`).
///
/// **Branch on `kind`, never on which list happens to be non-empty.** A
/// `Permission` puts the agent's offered options in `options` and leaves
/// `questions` empty; a `Question` puts the form in `questions` — each carrying
/// its OWN options and `custom` flag — and leaves `options` empty. Rendering the
/// wrong one yields an approval with no buttons.
class BridgeLaneApproval {
  final String id;

  /// The session this blocks. May be a DESCENDANT of the session the panel is
  /// open on — a child session's approval still blocks the parent's agent.
  final String sessionId;
  final BridgeLaneApprovalKind kind;
  final BridgeLaneApprovalStatus status;
  final String title;
  final String? detail;
  final List<BridgeLaneApprovalOption> options;
  final List<BridgeLaneQuestion> questions;

  /// The agent's own request payload, RAW JSON in a string (the FRB-mirror
  /// rule bars a `serde_json::Value`). It is what a client renders when `kind`
  /// is unknown, and the body [`BridgeLaneAnswer::Raw`] answers against.
  final String requestJson;
  final PlatformInt64? createdAtUnixMs;

  const BridgeLaneApproval({
    required this.id,
    required this.sessionId,
    required this.kind,
    required this.status,
    required this.title,
    this.detail,
    required this.options,
    required this.questions,
    required this.requestJson,
    this.createdAtUnixMs,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      sessionId.hashCode ^
      kind.hashCode ^
      status.hashCode ^
      title.hashCode ^
      detail.hashCode ^
      options.hashCode ^
      questions.hashCode ^
      requestJson.hashCode ^
      createdAtUnixMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeLaneApproval &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          sessionId == other.sessionId &&
          kind == other.kind &&
          status == other.status &&
          title == other.title &&
          detail == other.detail &&
          options == other.options &&
          questions == other.questions &&
          requestJson == other.requestJson &&
          createdAtUnixMs == other.createdAtUnixMs;
}

@freezed
sealed class BridgeLaneApprovalKind with _$BridgeLaneApprovalKind {
  const BridgeLaneApprovalKind._();

  const factory BridgeLaneApprovalKind.permission() =
      BridgeLaneApprovalKind_Permission;
  const factory BridgeLaneApprovalKind.question() =
      BridgeLaneApprovalKind_Question;
  const factory BridgeLaneApprovalKind.planApproval() =
      BridgeLaneApprovalKind_PlanApproval;
  const factory BridgeLaneApprovalKind.mcpElicitation() =
      BridgeLaneApprovalKind_McpElicitation;
  const factory BridgeLaneApprovalKind.other({required String raw}) =
      BridgeLaneApprovalKind_Other;
}

/// One selectable answer (mirrors `lane::LaneApprovalOption`).
///
/// **`id` is OPAQUE and `kind` is the semantics.** Round-trip the id; never
/// parse it. Anything that needs to know what an option MEANS reads `kind` — and
/// `kind` is a `String`, not an enum, because it is a stream value the contract
/// tolerates open: clients match the four known values
/// (`allow_once`/`allow_always`/`reject_once`/`reject_always`) and render
/// anything else as a plain button.
class BridgeLaneApprovalOption {
  final String id;
  final String label;
  final String? description;
  final String? kind;

  const BridgeLaneApprovalOption({
    required this.id,
    required this.label,
    this.description,
    this.kind,
  });

  @override
  int get hashCode =>
      id.hashCode ^ label.hashCode ^ description.hashCode ^ kind.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeLaneApprovalOption &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          description == other.description &&
          kind == other.kind;
}

@freezed
sealed class BridgeLaneApprovalStatus with _$BridgeLaneApprovalStatus {
  const BridgeLaneApprovalStatus._();

  const factory BridgeLaneApprovalStatus.pending() =
      BridgeLaneApprovalStatus_Pending;
  const factory BridgeLaneApprovalStatus.submitted() =
      BridgeLaneApprovalStatus_Submitted;
  const factory BridgeLaneApprovalStatus.resolved() =
      BridgeLaneApprovalStatus_Resolved;
  const factory BridgeLaneApprovalStatus.other({required String raw}) =
      BridgeLaneApprovalStatus_Other;
}

/// What this SESSION can do, now (mirrors `lane::LaneCapabilities`) —
/// advertised, so the panel greys out an affordance instead of discovering the
/// refusal on a tap.
///
/// **Per session, and read from the snapshot, never cached at open** (plan 025
/// §3.2.1). Capabilities ride the lane's stream (`LaneEvent::Capabilities`, in
/// every seed before its `Ready` and again on change), so a craze session's can
/// change with its incarnation; [`BridgeLaneSnapshot::capabilities`] carries
/// the live generation's. opencode answers `{kind: "opencode", interject:
/// false, cancel: true, approvals: true, history_cursor: false, settings:
/// false, stop: false}` in every seed.
///
/// `create` left this type in plan 025 — creating is a machine-level act, and
/// it is [`BridgeSourceCapabilities::create`] now.
class BridgeLaneCapabilities {
  final String kind;
  final bool interject;
  final bool cancel;
  final bool approvals;

  /// The STREAM may resume from a cursor silently: a reconnect may leave no
  /// `Reset` behind, only a stale mark that a lone `Ready` clears. Since plan
  /// 025 it speaks for the stream alone — `history`'s cursor is advisory.
  /// Dart never counts brackets anyway (the fold is Rust's); it is here so a
  /// panel can know a "reconnecting…" banner may clear without a reseed.
  final bool historyCursor;

  /// The session has settings to show and change, and its snapshots carry
  /// [`BridgeLaneSnapshot::settings`].
  final bool settings;

  /// The session can be ended from this client (a Stop button).
  final bool stop;

  const BridgeLaneCapabilities({
    required this.kind,
    required this.interject,
    required this.cancel,
    required this.approvals,
    required this.historyCursor,
    required this.settings,
    required this.stop,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      interject.hashCode ^
      cancel.hashCode ^
      approvals.hashCode ^
      historyCursor.hashCode ^
      settings.hashCode ^
      stop.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeLaneCapabilities &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          interject == other.interject &&
          cancel == other.cancel &&
          approvals == other.approvals &&
          historyCursor == other.historyCursor &&
          settings == other.settings &&
          stop == other.stop;
}

/// One selectable value — a model, a mode, or one option's value (mirrors
/// `lane::LaneChoice`). `id` is opaque and round-tripped into a
/// [`BridgeLaneSettingChange`]; `name` is what a client shows.
class BridgeLaneChoice {
  final String id;
  final String name;

  /// The agent's own ordering hint, when it gives one (lower first).
  final int? rank;
  final String? description;

  const BridgeLaneChoice({
    required this.id,
    required this.name,
    this.rank,
    this.description,
  });

  @override
  int get hashCode =>
      id.hashCode ^ name.hashCode ^ rank.hashCode ^ description.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeLaneChoice &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          rank == other.rank &&
          description == other.description;
}

/// What a create can start on a machine (mirrors `lane::LaneCreateOptions`):
/// the providers and whether each can start, the default, and the directories
/// sessions last ran in. Providers keep the agent's own order (plan 025 D5: a
/// provider that cannot start is dimmed, not hidden).
class BridgeLaneCreateOptions {
  final List<BridgeLaneProvider> providers;

  /// May name a provider that is not listed or not ready — a client
  /// preselects it only when it is listed AND `Ready`.
  final String? defaultProvider;

  /// Newest first.
  final List<String> recentDirs;

  const BridgeLaneCreateOptions({
    required this.providers,
    this.defaultProvider,
    required this.recentDirs,
  });

  @override
  int get hashCode =>
      providers.hashCode ^ defaultProvider.hashCode ^ recentDirs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeLaneCreateOptions &&
          runtimeType == other.runtimeType &&
          providers == other.providers &&
          defaultProvider == other.defaultProvider &&
          recentDirs == other.recentDirs;
}

/// A create, as the phone asks for it (mirrors `lane::LaneCreateRequest`) — a
/// provider, a directory and an optional first prompt, nothing else (plan 025
/// D6).
///
/// **Strict**: a plain struct with exactly the contract's fields, so Dart
/// cannot attach one the adapter would have to drop. `request_id` is reused
/// ONLY while the outcome of the create that carried it is unknown, and minted
/// fresh after any definite answer (plan 025 §3.8).
class BridgeLaneCreateRequest {
  /// Absolute, and existing on the machine.
  final String cwd;

  /// A [`BridgeLaneProvider::id`]; `None` for the agent's own default.
  final String? provider;

  /// The first prompt; `None` creates an idle session.
  final String? prompt;
  final String requestId;

  const BridgeLaneCreateRequest({
    required this.cwd,
    this.provider,
    this.prompt,
    required this.requestId,
  });

  @override
  int get hashCode =>
      cwd.hashCode ^ provider.hashCode ^ prompt.hashCode ^ requestId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeLaneCreateRequest &&
          runtimeType == other.runtimeType &&
          cwd == other.cwd &&
          provider == other.provider &&
          prompt == other.prompt &&
          requestId == other.requestId;
}

/// What a create answered (mirrors `lane::LaneCreated`): the new session's row
/// and what became of its first prompt. The session exists whenever this is
/// returned — a refused or lost prompt is not a failed create.
class BridgeLaneCreated {
  final BridgeLaneSession session;
  final BridgeLanePromptOutcome prompt;

  /// Why the prompt was refused, or why its answer was lost.
  final String? promptError;

  const BridgeLaneCreated({
    required this.session,
    required this.prompt,
    this.promptError,
  });

  @override
  int get hashCode => session.hashCode ^ prompt.hashCode ^ promptError.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeLaneCreated &&
          runtimeType == other.runtimeType &&
          session == other.session &&
          prompt == other.prompt &&
          promptError == other.promptError;
}

/// The three SEMANTIC decisions a permission approval accepts, independent of
/// what the agent named its options (mirrors `lane::LaneDecision`).
///
/// **Strict**: a plain enum with no escape arm, because this is a
/// client→adapter COMMAND. The adapter resolves it through
/// [`lane_option_for`]'s rule and answers `bad_request` when nothing — or
/// several things — match.
enum BridgeLaneDecision { allowOnce, allowAlways, reject }

@freezed
sealed class BridgeLaneError with _$BridgeLaneError implements FrbException {
  const BridgeLaneError._();

  /// The agent demanded a credential this build cannot supply.
  const factory BridgeLaneError.unauthorized() = BridgeLaneError_Unauthorized;

  /// The agent rejected the request and said why — ITS message, kept whole.
  const factory BridgeLaneError.badRequest({required String msg}) =
      BridgeLaneError_BadRequest;
  const factory BridgeLaneError.unknownSession() =
      BridgeLaneError_UnknownSession;
  const factory BridgeLaneError.unknownApproval() =
      BridgeLaneError_UnknownApproval;

  /// An answer is already in flight (the optimistic `Submitted` state). A
  /// double-tap, not an error to surface loudly.
  const factory BridgeLaneError.alreadySubmitted() =
      BridgeLaneError_AlreadySubmitted;
  const factory BridgeLaneError.alreadyResolved() =
      BridgeLaneError_AlreadyResolved;
  const factory BridgeLaneError.notAccepting() = BridgeLaneError_NotAccepting;

  /// Nothing to talk to: the agent is not running, the dial was refused, the
  /// tunnel is down. **Quiet** — render an unreachable row with this reason,
  /// not an error dialog. The string names what was tried.
  const factory BridgeLaneError.unavailable({required String msg}) =
      BridgeLaneError_Unavailable;

  /// Anything else that went wrong on the wire, kept whole.
  const factory BridgeLaneError.failed({required String msg}) =
      BridgeLaneError_Failed;

  /// There is no lane here: this handle is closed, or the row carries no
  /// stamp. Carries a message because the two cases read differently to a
  /// user, and neither is the adapter's.
  const factory BridgeLaneError.noLane({required String msg}) =
      BridgeLaneError_NoLane;

  /// The row DOES carry a lane and this build has no adapter for its kind.
  ///
  /// Distinct from [`BridgeLaneError::NoLane`] on purpose: `NoLane` is a
  /// permanent property of the row and a client renders no affordance for it,
  /// while this one means "there IS something here and I cannot speak to it" —
  /// which a NEWER build may well be able to. `AgentLaneStamp`'s doc makes
  /// refusing by name the client's obligation for exactly that reason.
  const factory BridgeLaneError.unsupportedLane({required String kind}) =
      BridgeLaneError_UnsupportedLane;

  /// **A craze request whose answer was lost** (plan 025 §3.3.4, §3.8) — it
  /// was written and never answered: its connection dropped while it was in
  /// flight, or its deadline passed. Whether it RAN is not known, and it is
  /// never resent.
  ///
  /// Its own variant, not [`BridgeLaneError::Failed`]'s text, because a client
  /// does something different about it than about a refusal, and must not
  /// have to read a message to know which it got:
  ///
  /// * **a create** (`craze_create`: lost twice, shed-craze's own retry under
  ///   the same request id included, or cut short by the source's close) — the
  ///   ONE refusal after which a create sheet KEEPS its request id: craze
  ///   answers a retry under that id with the session the first attempt
  ///   started, so a lost answer never makes a second session, while after any
  ///   definite refusal craze would replay that same refusal for ten minutes,
  ///   so the id must go;
  /// * **a lane verb** (`lane_send`, `lane_cancel`, `lane_answer`, `lane_stop`)
  ///   — the transcript says whether it ran; a send's text stays in the box
  ///   with the desktop's words for it (its `SEND_OUTCOME_UNKNOWN`, Dart's
  ///   `laneSendOutcomeUnknown`), and the desktop's settings sheet shows such
  ///   a change "not confirmed" until the next `Settings` says where the
  ///   session is (§3.10).
  ///
  /// The desktop's `LaneFailure::OutcomeUnknown`, for the same reasons and
  /// mapped the same way: by the one [`From<LaneError>`] every lane and create
  /// refusal goes through, recognised by `shed_craze::is_outcome_unknown` (one
  /// implementation; no client string-matches it).
  const factory BridgeLaneError.outcomeUnknown({required String msg}) =
      BridgeLaneError_OutcomeUnknown;
}

@freezed
sealed class BridgeLanePromptOutcome with _$BridgeLanePromptOutcome {
  const BridgeLanePromptOutcome._();

  const factory BridgeLanePromptOutcome.none() = BridgeLanePromptOutcome_None;
  const factory BridgeLanePromptOutcome.accepted() =
      BridgeLanePromptOutcome_Accepted;
  const factory BridgeLanePromptOutcome.unknown() =
      BridgeLanePromptOutcome_Unknown;
  const factory BridgeLanePromptOutcome.refused() =
      BridgeLanePromptOutcome_Refused;
  const factory BridgeLanePromptOutcome.other({required String raw}) =
      BridgeLanePromptOutcome_Other;
}

/// One provider a create can name (mirrors `lane::LaneProvider`).
class BridgeLaneProvider {
  /// What [`BridgeLaneCreateRequest::provider`] takes.
  final String id;
  final String label;
  final BridgeLaneProviderState state;

  /// Why it cannot start — present exactly when `state` is not `Ready`.
  final String? reason;

  /// What to do about it, one line.
  final String? fix;

  const BridgeLaneProvider({
    required this.id,
    required this.label,
    required this.state,
    this.reason,
    this.fix,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      label.hashCode ^
      state.hashCode ^
      reason.hashCode ^
      fix.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeLaneProvider &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          state == other.state &&
          reason == other.reason &&
          fix == other.fix;
}

@freezed
sealed class BridgeLaneProviderState with _$BridgeLaneProviderState {
  const BridgeLaneProviderState._();

  const factory BridgeLaneProviderState.ready() = BridgeLaneProviderState_Ready;
  const factory BridgeLaneProviderState.needsSetup() =
      BridgeLaneProviderState_NeedsSetup;
  const factory BridgeLaneProviderState.unavailable() =
      BridgeLaneProviderState_Unavailable;
  const factory BridgeLaneProviderState.other({required String raw}) =
      BridgeLaneProviderState_Other;
}

/// A structured question inside an approval (mirrors `lane::LaneQuestion`).
///
/// `custom` permits free text, which travels back positionally in
/// [`BridgeLaneAnswer::Question::custom_text`]. The adapter REFUSES text aimed
/// at a question whose `custom` is false rather than dropping it, so a panel
/// gates the text field on this flag.
class BridgeLaneQuestion {
  /// The key this question's answer is filed under, when the agent files by
  /// key. gx sets it to the question's own TEXT; opencode files positionally
  /// and leaves it `None`. It is here so the key is VISIBLE, not so a client
  /// has to use it — answers stay positional and the adapter maps them.
  final String? id;
  final String header;
  final String question;
  final List<BridgeLaneApprovalOption> options;
  final bool multiple;
  final bool custom;

  const BridgeLaneQuestion({
    this.id,
    required this.header,
    required this.question,
    required this.options,
    required this.multiple,
    required this.custom,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      header.hashCode ^
      question.hashCode ^
      options.hashCode ^
      multiple.hashCode ^
      custom.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeLaneQuestion &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          header == other.header &&
          question == other.question &&
          options == other.options &&
          multiple == other.multiple &&
          custom == other.custom;
}

/// One agent session as the contract sees it (mirrors `lane::LaneSession`).
///
/// `activity` is [`BridgeRcActivity`] rather than a parallel vocabulary, for the
/// contract's reason: a lane row has to sort into the same sessions view as an
/// RC row, and the app already renders that badge.
///
/// **Read `activity` for "is it running" and `pending_approvals` for "is it
/// blocked on me".** They are separate dimensions on purpose — the pinned
/// opencode mapping never emits `NeedsApproval`, so a client that keys its
/// blocked badge off `activity` alone misses every opencode approval.
///
/// It crosses on [`BridgeLaneSnapshot::session`] — the stream's LIVE row — and,
/// from the craze source on, as a machine's craze rows. It used to carry
/// `#[frb(unignore)]` because nothing returned one: before plan 025 the fold
/// projected only the session's `activity`. `shed_app::lane_view` now projects
/// the whole row, so the codegen reaches it through the snapshot.
///
/// The fields after `last_change_unix_ms` are plan 025's: what a craze roster
/// row says about a session beyond its activity. Every one is optional and
/// `None` on a row from an adapter that knows none of them (opencode's), and
/// each is the contract's own field, mirrored as it stands
/// (`shed_core::lane::LaneSession`).
class BridgeLaneSession {
  final String id;
  final String title;
  final String cwd;
  final BridgeRcActivity activity;
  final int pendingApprovals;

  /// `true` when the adapter derived this ROW from a cheap or stale source (a
  /// roster poll rather than a live fold). Per-ROW, not per-producer
  /// (`lane`'s correction 7): opencode answers `true` from its roster and
  /// `false` from its watcher.
  final bool approximate;
  final String? parentId;
  final PlatformInt64? lastChangeUnixMs;

  /// The agent provider driving the session (craze's `cursor`, `grok`, …);
  /// `None` where the adapter IS the provider (opencode).
  final String? provider;

  /// The model the session runs, as the agent names it.
  final String? model;

  /// What the session is doing right now, one line.
  final String? doing;

  /// The oldest open approval's one-line summary — what the session is
  /// blocked on, for a row with no room for the approval itself.
  final String? headAskSummary;

  /// The head of the agent's last reply, one line.
  final String? lastReply;

  /// Unix epoch milliseconds since the session has been in its current state.
  final PlatformInt64? sinceUnixMs;

  /// How many clients are attached to the session right now.
  final int? attached;

  /// Why the session failed to start, when it did — shown as it is.
  final String? startError;

  /// The PROVIDER's own session id behind this row — the key a roost tab
  /// running the same session carries, and so the key a client folds that
  /// tab into this row by (plan 025 D4). Never an address any verb takes.
  final String? providerSessionId;

  /// The agent's permission posture (craze's `"bypass"` | `"prompt"`) for the
  /// transcript header. An open string: a newer agent's posture renders as
  /// its own word.
  final String? permissionMode;

  /// The roost tab this row was merged with — set ONLY by the client-side
  /// merge (plan 025 §3.6.3), never by a source or a lane.
  final PlatformInt64? tabId;

  const BridgeLaneSession({
    required this.id,
    required this.title,
    required this.cwd,
    required this.activity,
    required this.pendingApprovals,
    required this.approximate,
    this.parentId,
    this.lastChangeUnixMs,
    this.provider,
    this.model,
    this.doing,
    this.headAskSummary,
    this.lastReply,
    this.sinceUnixMs,
    this.attached,
    this.startError,
    this.providerSessionId,
    this.permissionMode,
    this.tabId,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      cwd.hashCode ^
      activity.hashCode ^
      pendingApprovals.hashCode ^
      approximate.hashCode ^
      parentId.hashCode ^
      lastChangeUnixMs.hashCode ^
      provider.hashCode ^
      model.hashCode ^
      doing.hashCode ^
      headAskSummary.hashCode ^
      lastReply.hashCode ^
      sinceUnixMs.hashCode ^
      attached.hashCode ^
      startError.hashCode ^
      providerSessionId.hashCode ^
      permissionMode.hashCode ^
      tabId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeLaneSession &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          cwd == other.cwd &&
          activity == other.activity &&
          pendingApprovals == other.pendingApprovals &&
          approximate == other.approximate &&
          parentId == other.parentId &&
          lastChangeUnixMs == other.lastChangeUnixMs &&
          provider == other.provider &&
          model == other.model &&
          doing == other.doing &&
          headAskSummary == other.headAskSummary &&
          lastReply == other.lastReply &&
          sinceUnixMs == other.sinceUnixMs &&
          attached == other.attached &&
          startError == other.startError &&
          providerSessionId == other.providerSessionId &&
          permissionMode == other.permissionMode &&
          tabId == other.tabId;
}

/// One of a model's options (mirrors `lane::LaneSetting`). `current` and each
/// value are strings, and `category` an open string, exactly as the contract
/// has them.
class BridgeLaneSetting {
  /// What [`BridgeLaneSettingChange::Config`]'s `id` names.
  final String id;
  final String name;
  final String category;
  final String current;
  final List<BridgeLaneChoice> values;

  const BridgeLaneSetting({
    required this.id,
    required this.name,
    required this.category,
    required this.current,
    required this.values,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      category.hashCode ^
      current.hashCode ^
      values.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeLaneSetting &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          category == other.category &&
          current == other.current &&
          values == other.values;
}

@freezed
sealed class BridgeLaneSettingChange with _$BridgeLaneSettingChange {
  const BridgeLaneSettingChange._();

  /// Move to the model with this [`BridgeLaneChoice::id`].
  const factory BridgeLaneSettingChange.model({required String id}) =
      BridgeLaneSettingChange_Model;

  /// Move to the mode with this [`BridgeLaneChoice::id`].
  const factory BridgeLaneSettingChange.mode({required String id}) =
      BridgeLaneSettingChange_Mode;

  /// Set the option [`BridgeLaneSetting::id`] to the value
  /// [`BridgeLaneChoice::id`].
  const factory BridgeLaneSettingChange.config({
    required String id,
    required String value,
    String? forModel,
  }) = BridgeLaneSettingChange_Config;
}

/// A session's settings, rendered generically (mirrors `lane::LaneSettings`):
/// the model and the models it can move to, the mode and the modes, the
/// model's own options, and how full its context is. Inbound.
class BridgeLaneSettings {
  /// The current model's id.
  final String? model;

  /// The models a [`BridgeLaneSettingChange::Model`] can name, in the order a
  /// client shows them.
  final List<BridgeLaneChoice> models;

  /// The current mode's id.
  final String? mode;
  final List<BridgeLaneChoice> modes;

  /// The current model's own options (an effort level, a fast mode, …).
  final List<BridgeLaneSetting> options;
  final BridgeLaneUsage? usage;

  const BridgeLaneSettings({
    this.model,
    required this.models,
    this.mode,
    required this.modes,
    required this.options,
    this.usage,
  });

  @override
  int get hashCode =>
      model.hashCode ^
      models.hashCode ^
      mode.hashCode ^
      modes.hashCode ^
      options.hashCode ^
      usage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeLaneSettings &&
          runtimeType == other.runtimeType &&
          model == other.model &&
          models == other.models &&
          mode == other.mode &&
          modes == other.modes &&
          options == other.options &&
          usage == other.usage;
}

/// **The one thing Dart reads after a nudge** — a projection of
/// [`shed_app::lane_view::LaneViewSnapshot`], taken under ONE lock.
///
/// One value rather than two calls, because two reads would TEAR: a frame can
/// land between "give me the messages" and "give me the approvals", and the
/// panel would render a transcript and an approval set from different instants.
/// Reading it is also the NUDGE ACKNOWLEDGEMENT — it clears the dirty bit, which
/// is what makes a burst of a hundred frames one nudge rather than a hundred.
/// See [`super::lane::lane_snapshot`].
///
/// **`stale` is not `ended`** (plan 025 §3.2.4). `stale` is the banner: the
/// stream behind these rows is not live, for a reason. `ended` is the
/// lifecycle: the subscription ENDED, and it is the only thing Dart re-opens a
/// lane on. A silent resume sets `stale` and clears it again without ever
/// setting `ended`, and a client that re-opened on `stale` would throw away the
/// cursor that resume exists to keep.
class BridgeLaneSnapshot {
  /// Every row of the current generation, or just the rows after the cursor
  /// that was asked for. `full` says which.
  final List<BridgeRcFeedMessage> messages;

  /// `true` when `messages` is the WHOLE current generation and the reader
  /// should REPLACE what it holds; `false` when it is a delta to append.
  final bool full;
  final BridgeRcActivity activity;

  /// The session ROW as of the live generation — the stream's latest
  /// `Session`, `None` until a seed carrying one has completed. **This, not
  /// the row a lane was opened from, is the session's current state**: for a
  /// session opened the moment it was created, the open's row carries none
  /// of what the live stream says (its permission posture, plan 025 §3.6.5),
  /// so a header reads its facts from here once it is `Some`.
  final BridgeLaneSession? session;

  /// The generation `messages` belong to — Rust's own counter, monotonic, and
  /// it moves only when a seed COMPLETES. A number that moved when one
  /// started would tell a client to discard the generation still on its
  /// screen.
  final BigInt generation;

  /// The banner: `Some(reason)` when the stream behind these rows is not live
  /// — the transport is gone and the adapter is retrying (a `Stale`), or the
  /// subscription ended (a `Down`). Cleared by the `Ready` that brings it
  /// back. **Not** a cue to re-open: see [`Self::ended`].
  final String? stale;

  /// The lifecycle: `true` once the subscription ENDED (a `Down`), and only
  /// then. **"Ended, re-open me"** — the controller's cue to call
  /// [`super::lane::lane_open`] again (plan 018 §3.11), and the ONLY
  /// reconnect job Dart has: Rust owns every other retry, a silent resume
  /// included.
  final bool ended;

  /// What the session can do, as of the live generation — `None` until a
  /// seed carrying them has completed. A panel gates its affordances on this
  /// and on nothing it cached at open.
  final BridgeLaneCapabilities? capabilities;

  /// The session's settings, as of the live generation; `None` when it has
  /// none to show (its capabilities say `settings: false`).
  final BridgeLaneSettings? settings;

  /// The asks still waiting on the human, oldest first, id as the tiebreak.
  /// Pending only, by [`lane_status_is_pending`]'s rule.
  final List<BridgeLaneApproval> approvals;

  const BridgeLaneSnapshot({
    required this.messages,
    required this.full,
    required this.activity,
    this.session,
    required this.generation,
    this.stale,
    required this.ended,
    this.capabilities,
    this.settings,
    required this.approvals,
  });

  @override
  int get hashCode =>
      messages.hashCode ^
      full.hashCode ^
      activity.hashCode ^
      session.hashCode ^
      generation.hashCode ^
      stale.hashCode ^
      ended.hashCode ^
      capabilities.hashCode ^
      settings.hashCode ^
      approvals.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeLaneSnapshot &&
          runtimeType == other.runtimeType &&
          messages == other.messages &&
          full == other.full &&
          activity == other.activity &&
          session == other.session &&
          generation == other.generation &&
          stale == other.stale &&
          ended == other.ended &&
          capabilities == other.capabilities &&
          settings == other.settings &&
          approvals == other.approvals;
}

/// How full the session's context is, when the agent says (mirrors
/// `lane::LaneUsage`). `u64`s, so Dart `BigInt`s.
class BridgeLaneUsage {
  final BigInt? contextTokens;
  final BigInt? contextWindow;

  const BridgeLaneUsage({this.contextTokens, this.contextWindow});

  @override
  int get hashCode => contextTokens.hashCode ^ contextWindow.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeLaneUsage &&
          runtimeType == other.runtimeType &&
          contextTokens == other.contextTokens &&
          contextWindow == other.contextWindow;
}

/// How a [`super::lane::lane_send`] is meant to land (mirrors `lane::SendMode`).
///
/// **Strict**, a plain enum: a send mode is a command, and degrading an unknown
/// one to a default would deliver the message with semantics the caller did not
/// ask for. Gate `Interject` on [`BridgeLaneCapabilities::interject`] — an
/// adapter that cannot do it answers `not_accepting`.
enum BridgeSendMode {
  /// "Accepted, and ordered after whatever is in flight." **Not a queue
  /// position** — the contract promises acceptance and ordering, nothing about
  /// where in a backlog the text sits.
  queue,
  interject,
}

/// What a source can do (mirrors `lane::SourceCapabilities`) — the
/// machine-level half of the capabilities: whether a create, and its options,
/// will be honoured on THIS source. A client hides the create sheet on a source
/// that says no rather than discovering the refusal on a tap.
class BridgeSourceCapabilities {
  /// The same agent token [`BridgeLaneCapabilities::kind`] carries.
  final String kind;
  final bool create;
  final bool createOptions;

  const BridgeSourceCapabilities({
    required this.kind,
    required this.create,
    required this.createOptions,
  });

  @override
  int get hashCode => kind.hashCode ^ create.hashCode ^ createOptions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeSourceCapabilities &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          create == other.create &&
          createOptions == other.createOptions;
}

@freezed
sealed class BridgeSourceOffline with _$BridgeSourceOffline {
  const BridgeSourceOffline._();

  const factory BridgeSourceOffline.notInstalled() =
      BridgeSourceOffline_NotInstalled;
  const factory BridgeSourceOffline.tooOld() = BridgeSourceOffline_TooOld;
  const factory BridgeSourceOffline.unreachable() =
      BridgeSourceOffline_Unreachable;
  const factory BridgeSourceOffline.failed() = BridgeSourceOffline_Failed;
  const factory BridgeSourceOffline.other({required String raw}) =
      BridgeSourceOffline_Other;
}
