// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.5.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'dto_rc.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

/// A session's live work dimension (mirrors `rc::RcActivity`). Plain enum;
/// an unknown wire token folds to `Unknown` (no `Other` arm, by design).
enum BridgeRcActivity { working, needsInput, idle, unknown }

/// One agent's install-probe result (mirrors `rc::RcAgentInfo`).
class BridgeRcAgentInfo {
  final bool installed;
  final String? version;

  const BridgeRcAgentInfo({required this.installed, this.version});

  @override
  int get hashCode => installed.hashCode ^ version.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRcAgentInfo &&
          runtimeType == other.runtimeType &&
          installed == other.installed &&
          version == other.version;
}

/// The `capabilities` payload (mirrors `rc::RcCapabilities`).
class BridgeRcCapabilities {
  final PlatformInt64 rcVersion;
  final List<BridgeRcKind> kinds;
  final Map<String, BridgeRcAgentInfo> agents;
  final List<String> features;
  final Map<String, BridgeRcKindFeatures> kindFeatures;

  const BridgeRcCapabilities({
    required this.rcVersion,
    required this.kinds,
    required this.agents,
    required this.features,
    required this.kindFeatures,
  });

  @override
  int get hashCode =>
      rcVersion.hashCode ^
      kinds.hashCode ^
      agents.hashCode ^
      features.hashCode ^
      kindFeatures.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRcCapabilities &&
          runtimeType == other.runtimeType &&
          rcVersion == other.rcVersion &&
          kinds == other.kinds &&
          agents == other.agents &&
          features == other.features &&
          kindFeatures == other.kindFeatures;
}

@freezed
sealed class BridgeRcEvent with _$BridgeRcEvent {
  const BridgeRcEvent._();

  const factory BridgeRcEvent.activityChanged({
    required String shed,
    required String slug,
    BridgeRcActivity? activity,
    String? activityAt,
    BridgeRcState? state,
    String? lastMessage,
  }) = BridgeRcEvent_ActivityChanged;
  const factory BridgeRcEvent.sessionUpdated({
    required String shed,
    required String slug,
    BridgeRcActivity? activity,
    BridgeRcState? state,
    String? lastMessage,
    required bool removed,
  }) = BridgeRcEvent_SessionUpdated;
  const factory BridgeRcEvent.messageAppended({
    required String shed,
    required String slug,
    required BigInt seq,
  }) = BridgeRcEvent_MessageAppended;
  const factory BridgeRcEvent.hubUnavailable({required String shed}) =
      BridgeRcEvent_HubUnavailable;
  const factory BridgeRcEvent.shedStopped({required String shed}) =
      BridgeRcEvent_ShedStopped;
}

/// One normalized feed message (mirrors `rc::RcFeedMessage`). `seq` is `u64`
/// (an FRB numeric edge — it marshals as Dart `BigInt`).
class BridgeRcFeedMessage {
  final BigInt seq;
  final String? ts;
  final String role;
  final String msgType;
  final String? text;
  final BridgeRcFeedTool? tool;

  const BridgeRcFeedMessage({
    required this.seq,
    this.ts,
    required this.role,
    required this.msgType,
    this.text,
    this.tool,
  });

  @override
  int get hashCode =>
      seq.hashCode ^
      ts.hashCode ^
      role.hashCode ^
      msgType.hashCode ^
      text.hashCode ^
      tool.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRcFeedMessage &&
          runtimeType == other.runtimeType &&
          seq == other.seq &&
          ts == other.ts &&
          role == other.role &&
          msgType == other.msgType &&
          text == other.text &&
          tool == other.tool;
}

/// A feed message's tool block (mirrors `rc::RcFeedTool`).
class BridgeRcFeedTool {
  final String? name;
  final String? detail;

  const BridgeRcFeedTool({this.name, this.detail});

  @override
  int get hashCode => name.hashCode ^ detail.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRcFeedTool &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          detail == other.detail;
}

@freezed
sealed class BridgeRcKind with _$BridgeRcKind {
  const BridgeRcKind._();

  const factory BridgeRcKind.claudeRc() = BridgeRcKind_ClaudeRc;
  const factory BridgeRcKind.claudeBroker() = BridgeRcKind_ClaudeBroker;
  const factory BridgeRcKind.codex() = BridgeRcKind_Codex;
  const factory BridgeRcKind.opencode() = BridgeRcKind_Opencode;
  const factory BridgeRcKind.cursor() = BridgeRcKind_Cursor;
  const factory BridgeRcKind.shell() = BridgeRcKind_Shell;

  /// An unrecognized wire kind, raw string preserved.
  const factory BridgeRcKind.other({required String raw}) = BridgeRcKind_Other;
}

/// Per-kind UI hints (mirrors `rc::RcKindFeatures`).
class BridgeRcKindFeatures {
  final bool postInput;
  final String approvals;
  final bool watch;
  final String input;

  const BridgeRcKindFeatures({
    required this.postInput,
    required this.approvals,
    required this.watch,
    required this.input,
  });

  @override
  int get hashCode =>
      postInput.hashCode ^ approvals.hashCode ^ watch.hashCode ^ input.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRcKindFeatures &&
          runtimeType == other.runtimeType &&
          postInput == other.postInput &&
          approvals == other.approvals &&
          watch == other.watch &&
          input == other.input;
}

/// A page of the feed (mirrors `rc::RcMessagesPage`).
class BridgeRcMessagesPage {
  final List<BridgeRcFeedMessage> messages;
  final bool truncated;

  const BridgeRcMessagesPage({required this.messages, required this.truncated});

  @override
  int get hashCode => messages.hashCode ^ truncated.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRcMessagesPage &&
          runtimeType == other.runtimeType &&
          messages == other.messages &&
          truncated == other.truncated;
}

/// The enriched session the app renders (mirrors `rc::RcSession`).
class BridgeRcSession {
  final String host;
  final String shed;
  final String slug;
  final String tmuxSession;
  final String displayName;
  final String? workdir;
  final BridgeRcKind kind;
  final BridgeRcState state;
  final String? url;
  final String? rcId;
  final String? createdBy;
  final String? createdAt;
  final String? targetLabel;
  final BridgeRcActivity? activity;
  final String? activityAt;
  final String? lastMessage;
  final bool managed;

  const BridgeRcSession({
    required this.host,
    required this.shed,
    required this.slug,
    required this.tmuxSession,
    required this.displayName,
    this.workdir,
    required this.kind,
    required this.state,
    this.url,
    this.rcId,
    this.createdBy,
    this.createdAt,
    this.targetLabel,
    this.activity,
    this.activityAt,
    this.lastMessage,
    required this.managed,
  });

  @override
  int get hashCode =>
      host.hashCode ^
      shed.hashCode ^
      slug.hashCode ^
      tmuxSession.hashCode ^
      displayName.hashCode ^
      workdir.hashCode ^
      kind.hashCode ^
      state.hashCode ^
      url.hashCode ^
      rcId.hashCode ^
      createdBy.hashCode ^
      createdAt.hashCode ^
      targetLabel.hashCode ^
      activity.hashCode ^
      activityAt.hashCode ^
      lastMessage.hashCode ^
      managed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRcSession &&
          runtimeType == other.runtimeType &&
          host == other.host &&
          shed == other.shed &&
          slug == other.slug &&
          tmuxSession == other.tmuxSession &&
          displayName == other.displayName &&
          workdir == other.workdir &&
          kind == other.kind &&
          state == other.state &&
          url == other.url &&
          rcId == other.rcId &&
          createdBy == other.createdBy &&
          createdAt == other.createdAt &&
          targetLabel == other.targetLabel &&
          activity == other.activity &&
          activityAt == other.activityAt &&
          lastMessage == other.lastMessage &&
          managed == other.managed;
}

/// The neutral `shed-ext-rc list` row (mirrors `rc::RcSessionDto`). Distinct
/// from [`BridgeRcSession`] — this is the pre-enrichment binary output the Dart
/// runner captures then hands back to the bridge decoder.
class BridgeRcSessionDto {
  final String slug;
  final String tmuxSession;
  final BridgeRcKind kind;
  final BridgeRcState state;
  final bool managed;
  final String? displayName;
  final String? workdir;
  final String? url;
  final String? id;
  final String? createdBy;
  final String? createdAt;
  final String? targetLabel;
  final BridgeRcActivity? activity;
  final String? activityAt;
  final String? lastMessage;

  const BridgeRcSessionDto({
    required this.slug,
    required this.tmuxSession,
    required this.kind,
    required this.state,
    required this.managed,
    this.displayName,
    this.workdir,
    this.url,
    this.id,
    this.createdBy,
    this.createdAt,
    this.targetLabel,
    this.activity,
    this.activityAt,
    this.lastMessage,
  });

  @override
  int get hashCode =>
      slug.hashCode ^
      tmuxSession.hashCode ^
      kind.hashCode ^
      state.hashCode ^
      managed.hashCode ^
      displayName.hashCode ^
      workdir.hashCode ^
      url.hashCode ^
      id.hashCode ^
      createdBy.hashCode ^
      createdAt.hashCode ^
      targetLabel.hashCode ^
      activity.hashCode ^
      activityAt.hashCode ^
      lastMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRcSessionDto &&
          runtimeType == other.runtimeType &&
          slug == other.slug &&
          tmuxSession == other.tmuxSession &&
          kind == other.kind &&
          state == other.state &&
          managed == other.managed &&
          displayName == other.displayName &&
          workdir == other.workdir &&
          url == other.url &&
          id == other.id &&
          createdBy == other.createdBy &&
          createdAt == other.createdAt &&
          targetLabel == other.targetLabel &&
          activity == other.activity &&
          activityAt == other.activityAt &&
          lastMessage == other.lastMessage;
}

/// A pane-derived lifecycle state (mirrors `rc::RcState`). Plain enum.
enum BridgeRcState {
  starting,
  ready,
  reconnecting,
  needsTrust,
  needsAuth,
  dead,
}
