// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.5.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'dto_lane.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'dto_rc.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `from_roost_dto`, `from_roost`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `BridgeRcSessionDto`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

/// A session's live work dimension (mirrors `rc::RcActivity`). Plain enum;
/// an unknown wire token folds to `Unknown` (no `Other` arm, by design).
enum BridgeRcActivity {
  working,
  needsInput,

  /// The session is blocked on an approval (contract v2). Distinct from
  /// `NeedsInput`: the agent is not waiting for a prompt, it is waiting for a
  /// DECISION — and whether the phone can make that decision depends on the
  /// kind's `approvals` capability (`remote` = steerable here, `tui` =
  /// informational, open the TUI). Rendering must key on `kind_features`,
  /// never on the kind.
  needsApproval,
  idle,
  unknown,
}

/// One agent's install-probe result (mirrors `rc::RcAgentInfo`).
class BridgeRcAgentInfo {
  final bool installed;
  final String? version;

  const BridgeRcAgentInfo({required this.installed, this.version});

  @override
  int get hashCode => installed.hashCode ^ version.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRcAgentInfo &&
          runtimeType == other.runtimeType &&
          installed == other.installed &&
          version == other.version;
}

/// The `capabilities` payload (mirrors `rc::RcCapabilities`).
class BridgeRcCapabilities {
  final PlatformInt64 rcVersion;
  final List<BridgeRcKind> kinds;
  final Map<String, BridgeRcAgentInfo> agents;
  final List<String> features;
  final Map<String, BridgeRcKindFeatures> kindFeatures;

  const BridgeRcCapabilities({
    required this.rcVersion,
    required this.kinds,
    required this.agents,
    required this.features,
    required this.kindFeatures,
  });

  @override
  int get hashCode =>
      rcVersion.hashCode ^
      kinds.hashCode ^
      agents.hashCode ^
      features.hashCode ^
      kindFeatures.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRcCapabilities &&
          runtimeType == other.runtimeType &&
          rcVersion == other.rcVersion &&
          kinds == other.kinds &&
          agents == other.agents &&
          features == other.features &&
          kindFeatures == other.kindFeatures;
}

@freezed
sealed class BridgeRcEvent with _$BridgeRcEvent {
  const BridgeRcEvent._();

  const factory BridgeRcEvent.activityChanged({
    required String shed,
    required String slug,
    BridgeRcActivity? activity,
    String? activityAt,
    BridgeRcState? state,
    String? lastMessage,
  }) = BridgeRcEvent_ActivityChanged;
  const factory BridgeRcEvent.sessionUpdated({
    required String shed,
    required String slug,
    BridgeRcActivity? activity,
    BridgeRcState? state,
    String? lastMessage,

    /// The session's lane (contract v2), carried verbatim when the hub sends
    /// one. `None` on a removal, and on a hub that predates the field.
    /// Additive: a consumer that ignores it behaves exactly as before.
    String? lane,
    required bool removed,
  }) = BridgeRcEvent_SessionUpdated;
  const factory BridgeRcEvent.messageAppended({
    required String shed,
    required String slug,
    required BigInt seq,
  }) = BridgeRcEvent_MessageAppended;
  const factory BridgeRcEvent.hubUnavailable({required String shed}) =
      BridgeRcEvent_HubUnavailable;
  const factory BridgeRcEvent.shedStopped({required String shed}) =
      BridgeRcEvent_ShedStopped;
}

/// One normalized feed message (mirrors `rc::RcFeedMessage`). `seq` is `u64`
/// (an FRB numeric edge — it marshals as Dart `BigInt`).
class BridgeRcFeedMessage {
  final BigInt seq;
  final String? ts;
  final String role;
  final String msgType;
  final String? text;
  final BridgeRcFeedTool? tool;

  const BridgeRcFeedMessage({
    required this.seq,
    this.ts,
    required this.role,
    required this.msgType,
    this.text,
    this.tool,
  });

  @override
  int get hashCode =>
      seq.hashCode ^
      ts.hashCode ^
      role.hashCode ^
      msgType.hashCode ^
      text.hashCode ^
      tool.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRcFeedMessage &&
          runtimeType == other.runtimeType &&
          seq == other.seq &&
          ts == other.ts &&
          role == other.role &&
          msgType == other.msgType &&
          text == other.text &&
          tool == other.tool;
}

/// A feed message's tool block (mirrors `rc::RcFeedTool`).
class BridgeRcFeedTool {
  final String? name;
  final String? detail;

  const BridgeRcFeedTool({this.name, this.detail});

  @override
  int get hashCode => name.hashCode ^ detail.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRcFeedTool &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          detail == other.detail;
}

@freezed
sealed class BridgeRcKind with _$BridgeRcKind {
  const BridgeRcKind._();

  const factory BridgeRcKind.claudeRc() = BridgeRcKind_ClaudeRc;
  const factory BridgeRcKind.claudeBroker() = BridgeRcKind_ClaudeBroker;
  const factory BridgeRcKind.codex() = BridgeRcKind_Codex;
  const factory BridgeRcKind.opencode() = BridgeRcKind_Opencode;
  const factory BridgeRcKind.cursor() = BridgeRcKind_Cursor;

  /// grok's `gx` agent **with a remote lane bound** — the row shed promotes
  /// once a roost tab's `gx.remote` metadata key appears (plan 017). roost
  /// never says `gx`; its adapter reports `source: "grok"` either way.
  const factory BridgeRcKind.gx() = BridgeRcKind_Gx;

  /// grok's `gx` agent with **no** lane: status through roost, no transcript.
  /// Lane-less by design, not a degraded `Gx`.
  const factory BridgeRcKind.grok() = BridgeRcKind_Grok;
  const factory BridgeRcKind.shell() = BridgeRcKind_Shell;

  /// An unrecognized wire kind, raw string preserved.
  const factory BridgeRcKind.other({required String raw}) = BridgeRcKind_Other;
}

/// Per-kind UI hints (mirrors `rc::RcKindFeatures`).
class BridgeRcKindFeatures {
  final bool postInput;

  /// `"remote"` = the hub can RESOLVE an approval from here; `"tui"` = the
  /// rows are informational and the decision must be made in the session's
  /// terminal; `"none"` = there is no approval surface a shed client can
  /// reach at all (every roost kind, which answers approvals inside its own
  /// tab). A client that offers an approve button for a `"tui"` kind produces
  /// a `409 not_supported` the user cannot act on — this field is the whole
  /// reason the contract carries capabilities. Branch on `== "remote"`; the
  /// other two are equally "don't offer it".
  final String approvals;
  final bool watch;

  /// `"turn"` = accepts a structured turn; `"gated"`/`"line"` = keystrokes
  /// only.
  final String input;

  /// contract v2: which feed this kind carries — `"messages"` (a normalized
  /// message feed), `"activity"` (an activity dimension and no message feed:
  /// every roost kind), or `"none"` (no signal at all: the guest hub's codex
  /// and cursor rows). Empty means the producer predates v2.
  ///
  /// It describes the MESSAGE feed only. No client gates its activity chip on
  /// it — the chip reads the row's own `activity` — which is why the same two
  /// kinds answer `"none"` through the guest hub and `"activity"` through
  /// roost.
  final String feed;

  /// contract v2: whether a running turn can be interrupted.
  final bool interrupt;

  /// contract v2: how the session is attachable — `"tmux"` (attach a pane) or
  /// `"native-remote"` (the terminal belongs to roost; a client reaches it
  /// with its own affordance, here the read-only `tab.dump` peek, or not at
  /// all). Empty means pre-v2, which means `"tmux"`.
  final String attach;

  const BridgeRcKindFeatures({
    required this.postInput,
    required this.approvals,
    required this.watch,
    required this.input,
    required this.feed,
    required this.interrupt,
    required this.attach,
  });

  @override
  int get hashCode =>
      postInput.hashCode ^
      approvals.hashCode ^
      watch.hashCode ^
      input.hashCode ^
      feed.hashCode ^
      interrupt.hashCode ^
      attach.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRcKindFeatures &&
          runtimeType == other.runtimeType &&
          postInput == other.postInput &&
          approvals == other.approvals &&
          watch == other.watch &&
          input == other.input &&
          feed == other.feed &&
          interrupt == other.interrupt &&
          attach == other.attach;
}

/// A page of the feed (mirrors `rc::RcMessagesPage`).
class BridgeRcMessagesPage {
  final List<BridgeRcFeedMessage> messages;
  final bool truncated;

  const BridgeRcMessagesPage({required this.messages, required this.truncated});

  @override
  int get hashCode => messages.hashCode ^ truncated.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRcMessagesPage &&
          runtimeType == other.runtimeType &&
          messages == other.messages &&
          truncated == other.truncated;
}

/// The enriched session the app renders (mirrors `rc::RcSession`).
///
/// **No `tmux_session`** (plan 013 S3m). It was the pane handle the terminal
/// attached to, and roost owns the terminal now: a roost row has no tmux session
/// to name, and the attach affordance is gated on `kind_features.attach`
/// (`native-remote` → the read-only `tab.dump` peek) rather than on the presence
/// of a tmux name. The field still exists on the WIRE — `shed-ext-rc list` emits
/// it unconditionally and shed-core's `RcSessionDto` still parses it — it simply
/// stops crossing into Dart.
///
/// The two roost-only fields ([`attention`](Self::attention),
/// [`tab_id`](Self::tab_id)) do not exist on `RcSessionDto` and are stamped here
/// instead: the shared wire DTO gains no field for roost (plan 013 §3.2), so the
/// ~11 struct-literal sites and the Go↔Rust parity goldens stay untouched.
class BridgeRcSession {
  final String host;
  final String shed;
  final String slug;
  final String displayName;
  final String? workdir;
  final BridgeRcKind kind;
  final BridgeRcState state;
  final String? url;
  final String? rcId;
  final String? createdBy;
  final String? createdAt;
  final String? targetLabel;
  final BridgeRcActivity? activity;
  final String? activityAt;
  final String? lastMessage;
  final bool managed;

  /// roost's `has_notification`, for a roost-sourced row; `false` for every
  /// shed row.
  ///
  /// **Sticky, and therefore its own affordance** — roost clears it on UI
  /// focus or an explicit `tab.clear_notification`, and shed never clears it.
  /// It is an attention *dot* on the card, NOT an activity state: folding it
  /// into "needs you" would leave a card asking for attention long after the
  /// thing that asked for it was dealt with.
  final bool attention;

  /// roost's tab id, for a roost-sourced row; `None` for every shed row.
  ///
  /// The handle `tab.close` / `tab.dump` address the tab by. It is also the
  /// row's [`slug`](Self::slug) rendered as a string — carried separately and
  /// typed so a caller never has to parse one back out.
  final PlatformInt64? tabId;

  /// **The agent lane on this row, if it has one** (plan 018 §3.9) — derived
  /// by `RoostSession::agent_lane()` and stamped here the way
  /// [`attention`](Self::attention) and [`tab_id`](Self::tab_id) are, for the
  /// same reason: the shared `RcSessionDto` gains no field for roost.
  ///
  /// `Some` requires all three of the stamp's conditions to hold — a kind an
  /// adapter exists for, a loopback control-surface URL the agent announced,
  /// and the agent's OWN session id — so a `Some` here is a lane
  /// [`super::lane::lane_open`] can actually be called with, not merely a
  /// row that looks agentic. `None` is "there is no transcript to show", and a
  /// client renders no lane affordance for it at all.
  ///
  /// It is the FULL stamp rather than a bare flag because §3.11 reconciles a
  /// live lane against the whole of it: a tab that restarted as a different
  /// agent, or the same agent on a new ephemeral port, is a DIFFERENT lane,
  /// and row-presence alone cannot say so.
  final BridgeAgentLaneStamp? agentLane;

  const BridgeRcSession({
    required this.host,
    required this.shed,
    required this.slug,
    required this.displayName,
    this.workdir,
    required this.kind,
    required this.state,
    this.url,
    this.rcId,
    this.createdBy,
    this.createdAt,
    this.targetLabel,
    this.activity,
    this.activityAt,
    this.lastMessage,
    required this.managed,
    required this.attention,
    this.tabId,
    this.agentLane,
  });

  @override
  int get hashCode =>
      host.hashCode ^
      shed.hashCode ^
      slug.hashCode ^
      displayName.hashCode ^
      workdir.hashCode ^
      kind.hashCode ^
      state.hashCode ^
      url.hashCode ^
      rcId.hashCode ^
      createdBy.hashCode ^
      createdAt.hashCode ^
      targetLabel.hashCode ^
      activity.hashCode ^
      activityAt.hashCode ^
      lastMessage.hashCode ^
      managed.hashCode ^
      attention.hashCode ^
      tabId.hashCode ^
      agentLane.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRcSession &&
          runtimeType == other.runtimeType &&
          host == other.host &&
          shed == other.shed &&
          slug == other.slug &&
          displayName == other.displayName &&
          workdir == other.workdir &&
          kind == other.kind &&
          state == other.state &&
          url == other.url &&
          rcId == other.rcId &&
          createdBy == other.createdBy &&
          createdAt == other.createdAt &&
          targetLabel == other.targetLabel &&
          activity == other.activity &&
          activityAt == other.activityAt &&
          lastMessage == other.lastMessage &&
          managed == other.managed &&
          attention == other.attention &&
          tabId == other.tabId &&
          agentLane == other.agentLane;
}

/// A pane-derived lifecycle state (mirrors `rc::RcState`). Plain enum.
enum BridgeRcState {
  starting,
  ready,
  reconnecting,
  needsTrust,
  needsAuth,
  dead,
}
