// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.5.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'dto_rc.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'dto_lane.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `from_view`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

/// Whether this approval is still waiting on the human — **the only predicate a
/// client gates its answer affordance on**.
///
/// Exposed as a function rather than mirrored as a Dart `switch` because the
/// contract's answer for the case that matters is counter-intuitive:
/// [`BridgeLaneApprovalStatus::Other`] answers `false`. An unknown status is at
/// least as likely to be terminal (`cancelled`, `expired`) as live, so offering
/// buttons for it would post an answer the agent has stopped listening for. A
/// Dart re-derivation would very plausibly write `status != Resolved` and get
/// that backwards.
///
/// Sync: it is a `match` on a value Dart already holds.
bool laneStatusIsPending({required BridgeLaneApprovalStatus status}) =>
    RustLib.instance.api.crateApiDtoLaneLaneStatusIsPending(status: status);

/// The offered option a [`BridgeLaneDecision`] selects — **by
/// [`BridgeLaneApprovalOption::kind`], never by id**.
///
/// This calls [`LaneApproval::option_for`], which is the contract's ONE
/// implementation of correction 3, so gx, opencode and this phone cannot each
/// re-derive the clauses differently. The clause that makes re-derivation a real
/// hazard: a live gx leader offers FIVE permission options of which TWO declare
/// `allow_once`, so an exact-kind match that is AMBIGUOUS answers `None` rather
/// than picking — under the original "first in offered order wins" rule a human
/// tapping "Allow once" would have silently turned prompting off for the whole
/// session. The `Reject` decision alone falls back to the first option whose
/// kind starts `reject`, because a refusal broader than asked for is safe in a
/// way a broader allow is not.
///
/// `None` is not an error: it means this decision cannot name an option on this
/// approval, and the panel should post [`BridgeLaneAnswer::Choice`] with the
/// exact offered id instead — which is unambiguous by construction and what a
/// capability-driven panel already does.
///
/// Sync, and it takes the approval BY VALUE: Dart is holding the approval from
/// its last snapshot, there is no lane to look it up on, and nothing here does
/// I/O.
BridgeLaneApprovalOption? laneOptionFor({
  required BridgeLaneApproval approval,
  required BridgeLaneDecision decision,
}) => RustLib.instance.api.crateApiDtoLaneLaneOptionFor(
  approval: approval,
  decision: decision,
);

/// Where a row's agent lane is and which adapter speaks to it (mirrors
/// `roost::AgentLaneStamp`) — the whole of what [`super::lane::lane_open`]
/// needs.
///
/// **`server_url` is the REPORTED url**, never a dial url. On a remote machine
/// the phone dials its own fixed loopback port instead (plan 018 §3.10), and the
/// two are never conflated: a gx discovery record is matched against THIS one.
class BridgeAgentLaneStamp {
  /// The adapter token — `"opencode"` or `"gx"` today. A kind this build has
  /// no adapter for is refused BY NAME
  /// ([`BridgeLaneError::UnsupportedLane`]), never silently rendered as no
  /// lane: `AgentLaneStamp`'s own doc makes that the client's obligation.
  final String kind;

  /// The AGENT's own session id — the address every lane verb takes.
  final String sessionId;
  final String serverUrl;

  const BridgeAgentLaneStamp({
    required this.kind,
    required this.sessionId,
    required this.serverUrl,
  });

  @override
  int get hashCode => kind.hashCode ^ sessionId.hashCode ^ serverUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeAgentLaneStamp &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          sessionId == other.sessionId &&
          serverUrl == other.serverUrl;
}

@freezed
sealed class BridgeLaneAnswer with _$BridgeLaneAnswer {
  const BridgeLaneAnswer._();

  const factory BridgeLaneAnswer.permission({
    required BridgeLaneDecision decision,
  }) = BridgeLaneAnswer_Permission;
  const factory BridgeLaneAnswer.choice({required String optionId}) =
      BridgeLaneAnswer_Choice;
  const factory BridgeLaneAnswer.question({
    required List<List<String>> answers,

    /// Free text per question, positional like `answers`; `None` where the
    /// human typed nothing. Empty list = no free text anywhere.
    ///
    /// A `Vec<Option<String>>` — `List<String?>` in Dart — is the one
    /// genuinely awkward shape in this mirror, and it is load-bearing: a
    /// `None` and a `Some("")` are different answers, and flattening the
    /// hole would lose which question the text was for. The adapter refuses
    /// text aimed at a question whose `custom` is false, so a panel that
    /// gates its text field on [`BridgeLaneQuestion::custom`] never sends
    /// one that will be refused.
    required List<String?> customText,
  }) = BridgeLaneAnswer_Question;

  /// Decline the whole request — distinct from a permission's
  /// [`BridgeLaneDecision::Reject`], which is one option among three.
  const factory BridgeLaneAnswer.reject() = BridgeLaneAnswer_Reject;

  /// A body the contract does not model, as raw JSON — the escape hatch for
  /// an unknown [`BridgeLaneApprovalKind`]. Note what it is NOT: an escape arm
  /// for an unknown ANSWER SHAPE. The four cases above are the whole
  /// vocabulary; this one carries a payload for a request kind, chosen
  /// deliberately by a client that read `request_json`.
  const factory BridgeLaneAnswer.raw({required String json}) =
      BridgeLaneAnswer_Raw;
}

/// One thing waiting on the human (mirrors `lane::LaneApproval`).
///
/// **Branch on `kind`, never on which list happens to be non-empty.** A
/// `Permission` puts the agent's offered options in `options` and leaves
/// `questions` empty; a `Question` puts the form in `questions` — each carrying
/// its OWN options and `custom` flag — and leaves `options` empty. Rendering the
/// wrong one yields an approval with no buttons.
class BridgeLaneApproval {
  final String id;

  /// The session this blocks. May be a DESCENDANT of the session the panel is
  /// open on — a child session's approval still blocks the parent's agent.
  final String sessionId;
  final BridgeLaneApprovalKind kind;
  final BridgeLaneApprovalStatus status;
  final String title;
  final String? detail;
  final List<BridgeLaneApprovalOption> options;
  final List<BridgeLaneQuestion> questions;

  /// The agent's own request payload, RAW JSON in a string (the FRB-mirror
  /// rule bars a `serde_json::Value`). It is what a client renders when `kind`
  /// is unknown, and the body [`BridgeLaneAnswer::Raw`] answers against.
  final String requestJson;
  final PlatformInt64? createdAtUnixMs;

  const BridgeLaneApproval({
    required this.id,
    required this.sessionId,
    required this.kind,
    required this.status,
    required this.title,
    this.detail,
    required this.options,
    required this.questions,
    required this.requestJson,
    this.createdAtUnixMs,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      sessionId.hashCode ^
      kind.hashCode ^
      status.hashCode ^
      title.hashCode ^
      detail.hashCode ^
      options.hashCode ^
      questions.hashCode ^
      requestJson.hashCode ^
      createdAtUnixMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeLaneApproval &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          sessionId == other.sessionId &&
          kind == other.kind &&
          status == other.status &&
          title == other.title &&
          detail == other.detail &&
          options == other.options &&
          questions == other.questions &&
          requestJson == other.requestJson &&
          createdAtUnixMs == other.createdAtUnixMs;
}

@freezed
sealed class BridgeLaneApprovalKind with _$BridgeLaneApprovalKind {
  const BridgeLaneApprovalKind._();

  const factory BridgeLaneApprovalKind.permission() =
      BridgeLaneApprovalKind_Permission;
  const factory BridgeLaneApprovalKind.question() =
      BridgeLaneApprovalKind_Question;
  const factory BridgeLaneApprovalKind.planApproval() =
      BridgeLaneApprovalKind_PlanApproval;
  const factory BridgeLaneApprovalKind.mcpElicitation() =
      BridgeLaneApprovalKind_McpElicitation;
  const factory BridgeLaneApprovalKind.other({required String raw}) =
      BridgeLaneApprovalKind_Other;
}

/// One selectable answer (mirrors `lane::LaneApprovalOption`).
///
/// **`id` is OPAQUE and `kind` is the semantics.** Round-trip the id; never
/// parse it. Anything that needs to know what an option MEANS reads `kind` — and
/// `kind` is a `String`, not an enum, because it is a stream value the contract
/// tolerates open: clients match the four known values
/// (`allow_once`/`allow_always`/`reject_once`/`reject_always`) and render
/// anything else as a plain button.
class BridgeLaneApprovalOption {
  final String id;
  final String label;
  final String? description;
  final String? kind;

  const BridgeLaneApprovalOption({
    required this.id,
    required this.label,
    this.description,
    this.kind,
  });

  @override
  int get hashCode =>
      id.hashCode ^ label.hashCode ^ description.hashCode ^ kind.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeLaneApprovalOption &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          description == other.description &&
          kind == other.kind;
}

@freezed
sealed class BridgeLaneApprovalStatus with _$BridgeLaneApprovalStatus {
  const BridgeLaneApprovalStatus._();

  const factory BridgeLaneApprovalStatus.pending() =
      BridgeLaneApprovalStatus_Pending;
  const factory BridgeLaneApprovalStatus.submitted() =
      BridgeLaneApprovalStatus_Submitted;
  const factory BridgeLaneApprovalStatus.resolved() =
      BridgeLaneApprovalStatus_Resolved;
  const factory BridgeLaneApprovalStatus.other({required String raw}) =
      BridgeLaneApprovalStatus_Other;
}

/// What this adapter can actually do (mirrors `lane::LaneCapabilities`) —
/// advertised, so the panel greys out an affordance instead of discovering the
/// refusal on a tap.
///
/// opencode answers
/// `{kind: "opencode", interject: false, create: true, cancel: true, approvals: true, history_cursor: false}`;
/// gx answers the same with `interject` and `history_cursor` true. Those are
/// exactly the two flags a UI branches on, which is why the flags exist.
class BridgeLaneCapabilities {
  final String kind;
  final bool interject;
  final bool create;
  final bool cancel;
  final bool approvals;

  /// The adapter honors a history cursor — and therefore a **silent resume**
  /// is possible on its stream: a reconnect may leave no trace at all. It is
  /// why Dart must not count brackets to count connections; it never sees them
  /// anyway (the fold is Rust's).
  final bool historyCursor;

  const BridgeLaneCapabilities({
    required this.kind,
    required this.interject,
    required this.create,
    required this.cancel,
    required this.approvals,
    required this.historyCursor,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      interject.hashCode ^
      create.hashCode ^
      cancel.hashCode ^
      approvals.hashCode ^
      historyCursor.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeLaneCapabilities &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          interject == other.interject &&
          create == other.create &&
          cancel == other.cancel &&
          approvals == other.approvals &&
          historyCursor == other.historyCursor;
}

/// The three SEMANTIC decisions a permission approval accepts, independent of
/// what the agent named its options (mirrors `lane::LaneDecision`).
///
/// **Strict**: a plain enum with no escape arm, because this is a
/// client→adapter COMMAND. The adapter resolves it through
/// [`lane_option_for`]'s rule and answers `bad_request` when nothing — or
/// several things — match.
enum BridgeLaneDecision { allowOnce, allowAlways, reject }

@freezed
sealed class BridgeLaneError with _$BridgeLaneError implements FrbException {
  const BridgeLaneError._();

  /// The agent demanded a credential this build cannot supply.
  const factory BridgeLaneError.unauthorized() = BridgeLaneError_Unauthorized;

  /// The agent rejected the request and said why — ITS message, kept whole.
  const factory BridgeLaneError.badRequest({required String msg}) =
      BridgeLaneError_BadRequest;
  const factory BridgeLaneError.unknownSession() =
      BridgeLaneError_UnknownSession;
  const factory BridgeLaneError.unknownApproval() =
      BridgeLaneError_UnknownApproval;

  /// An answer is already in flight (the optimistic `Submitted` state). A
  /// double-tap, not an error to surface loudly.
  const factory BridgeLaneError.alreadySubmitted() =
      BridgeLaneError_AlreadySubmitted;
  const factory BridgeLaneError.alreadyResolved() =
      BridgeLaneError_AlreadyResolved;
  const factory BridgeLaneError.notAccepting() = BridgeLaneError_NotAccepting;

  /// Nothing to talk to: the agent is not running, the dial was refused, the
  /// tunnel is down. **Quiet** — render an unreachable row with this reason,
  /// not an error dialog. The string names what was tried.
  const factory BridgeLaneError.unavailable({required String msg}) =
      BridgeLaneError_Unavailable;

  /// Anything else that went wrong on the wire, kept whole.
  const factory BridgeLaneError.failed({required String msg}) =
      BridgeLaneError_Failed;

  /// There is no lane here: this handle is closed, or the row carries no
  /// stamp. Carries a message because the two cases read differently to a
  /// user, and neither is the adapter's.
  const factory BridgeLaneError.noLane({required String msg}) =
      BridgeLaneError_NoLane;

  /// The row DOES carry a lane and this build has no adapter for its kind.
  ///
  /// Distinct from [`BridgeLaneError::NoLane`] on purpose: `NoLane` is a
  /// permanent property of the row and a client renders no affordance for it,
  /// while this one means "there IS something here and I cannot speak to it" —
  /// which a NEWER build may well be able to. `AgentLaneStamp`'s doc makes
  /// refusing by name the client's obligation for exactly that reason.
  const factory BridgeLaneError.unsupportedLane({required String kind}) =
      BridgeLaneError_UnsupportedLane;
}

/// A structured question inside an approval (mirrors `lane::LaneQuestion`).
///
/// `custom` permits free text, which travels back positionally in
/// [`BridgeLaneAnswer::Question::custom_text`]. The adapter REFUSES text aimed
/// at a question whose `custom` is false rather than dropping it, so a panel
/// gates the text field on this flag.
class BridgeLaneQuestion {
  /// The key this question's answer is filed under, when the agent files by
  /// key. gx sets it to the question's own TEXT; opencode files positionally
  /// and leaves it `None`. It is here so the key is VISIBLE, not so a client
  /// has to use it — answers stay positional and the adapter maps them.
  final String? id;
  final String header;
  final String question;
  final List<BridgeLaneApprovalOption> options;
  final bool multiple;
  final bool custom;

  const BridgeLaneQuestion({
    this.id,
    required this.header,
    required this.question,
    required this.options,
    required this.multiple,
    required this.custom,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      header.hashCode ^
      question.hashCode ^
      options.hashCode ^
      multiple.hashCode ^
      custom.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeLaneQuestion &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          header == other.header &&
          question == other.question &&
          options == other.options &&
          multiple == other.multiple &&
          custom == other.custom;
}

/// One agent session as the contract sees it (mirrors `lane::LaneSession`).
///
/// `activity` is [`BridgeRcActivity`] rather than a parallel vocabulary, for the
/// contract's reason: a lane row has to sort into the same sessions view as an
/// RC row, and the app already renders that badge.
///
/// **Read `activity` for "is it running" and `pending_approvals` for "is it
/// blocked on me".** They are separate dimensions on purpose — the pinned
/// opencode mapping never emits `NeedsApproval`, so a client that keys its
/// blocked badge off `activity` alone misses every opencode approval.
///
/// `#[frb(unignore)]` because **no `pub` bridge function takes or returns one
/// yet**, and the codegen prunes an unreferenced type. It is mirrored anyway
/// because it is part of the contract §3.9 pins, and because the reason nothing
/// returns one is a property of the FOLD, not a decision about the row:
/// `shed_app::lane_view::LaneViewSnapshot` projects only the session's
/// `activity`, so the phone's snapshot has nowhere to carry the rest. Marking it
/// keeps the Dart mirror complete for the row-level verbs that follow instead of
/// making the next slice a codegen change as well as a feature.
class BridgeLaneSession {
  final String id;
  final String title;
  final String cwd;
  final BridgeRcActivity activity;
  final int pendingApprovals;

  /// `true` when the adapter derived this ROW from a cheap or stale source (a
  /// roster poll rather than a live fold). Per-ROW, not per-producer
  /// (`lane`'s correction 7): opencode answers `true` from its roster and
  /// `false` from its watcher.
  final bool approximate;
  final String? parentId;
  final PlatformInt64? lastChangeUnixMs;

  const BridgeLaneSession({
    required this.id,
    required this.title,
    required this.cwd,
    required this.activity,
    required this.pendingApprovals,
    required this.approximate,
    this.parentId,
    this.lastChangeUnixMs,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      cwd.hashCode ^
      activity.hashCode ^
      pendingApprovals.hashCode ^
      approximate.hashCode ^
      parentId.hashCode ^
      lastChangeUnixMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeLaneSession &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          cwd == other.cwd &&
          activity == other.activity &&
          pendingApprovals == other.pendingApprovals &&
          approximate == other.approximate &&
          parentId == other.parentId &&
          lastChangeUnixMs == other.lastChangeUnixMs;
}

/// **The one thing Dart reads after a nudge** — a projection of
/// [`shed_app::lane_view::LaneViewSnapshot`] plus the two bridge-level flags,
/// taken under ONE lock.
///
/// One value rather than two calls, because two reads would TEAR: a frame can
/// land between "give me the messages" and "give me the approvals", and the
/// panel would render a transcript and an approval set from different instants.
/// Reading it is also the NUDGE ACKNOWLEDGEMENT — it clears the dirty bit, which
/// is what makes a burst of a hundred frames one nudge rather than a hundred.
/// See [`super::lane::lane_snapshot`].
class BridgeLaneSnapshot {
  /// Every row of the current generation, or just the rows after the cursor
  /// that was asked for. `full` says which.
  final List<BridgeRcFeedMessage> messages;

  /// `true` when `messages` is the WHOLE current generation and the reader
  /// should REPLACE what it holds; `false` when it is a delta to append.
  final bool full;
  final BridgeRcActivity activity;

  /// The generation `messages` belong to — Rust's own counter, monotonic, and
  /// it moves only when a seed COMPLETES. A number that moved when one
  /// started would tell a client to discard the generation still on its
  /// screen.
  final BigInt generation;

  /// `Some(reason)` when the transport is gone and these rows are the last
  /// complete generation. **"Stale, re-open me"** — the controller's cue to
  /// call [`super::lane::lane_open`] again (plan 018 §3.11), and the ONLY
  /// reconnect job Dart has: Rust owns every other retry.
  final String? stale;

  /// The asks still waiting on the human, oldest first, id as the tiebreak.
  /// Pending only, by [`lane_status_is_pending`]'s rule.
  final List<BridgeLaneApproval> approvals;

  /// **The gx credential ask.** `true` when a leader restarted mid-pin and the
  /// adapter needs a FRESH discovery to continue: the controller re-runs
  /// [`super::lane::gx_probe_remote_command`] over the machine's SSH client
  /// and hands the bytes to
  /// [`super::lane::lane_refresh_credentials`]. Pinning then resumes in place
  /// — no `Down`, no re-open, generation and ring intact.
  final bool needsCredentials;

  const BridgeLaneSnapshot({
    required this.messages,
    required this.full,
    required this.activity,
    required this.generation,
    this.stale,
    required this.approvals,
    required this.needsCredentials,
  });

  @override
  int get hashCode =>
      messages.hashCode ^
      full.hashCode ^
      activity.hashCode ^
      generation.hashCode ^
      stale.hashCode ^
      approvals.hashCode ^
      needsCredentials.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeLaneSnapshot &&
          runtimeType == other.runtimeType &&
          messages == other.messages &&
          full == other.full &&
          activity == other.activity &&
          generation == other.generation &&
          stale == other.stale &&
          approvals == other.approvals &&
          needsCredentials == other.needsCredentials;
}

/// How a [`super::lane::lane_send`] is meant to land (mirrors `lane::SendMode`).
///
/// **Strict**, a plain enum: a send mode is a command, and degrading an unknown
/// one to a default would deliver the message with semantics the caller did not
/// ask for. Gate `Interject` on [`BridgeLaneCapabilities::interject`] — an
/// adapter that cannot do it answers `not_accepting`.
enum BridgeSendMode {
  /// "Accepted, and ordered after whatever is in flight." **Not a queue
  /// position** — the contract promises acceptance and ordering, nothing about
  /// where in a backlog the text sits.
  queue,
  interject,
}
