// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.5.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'error.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `encode_token_err`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`, `fmt`, `from`, `from`, `from`

@freezed
sealed class BridgeError with _$BridgeError implements FrbException {
  const BridgeError._();

  /// shed-server returned a non-2xx HTTP status. `code` is preserved so the
  /// app can distinguish 404 (`OverviewUnsupported` / `RC_SESSION_GONE`).
  const factory BridgeError.badStatus({required int code}) =
      BridgeError_BadStatus;

  /// A transport-layer failure (connect/TLS/timeout) — no HTTP status.
  const factory BridgeError.transport({required String msg}) =
      BridgeError_Transport;

  /// A response body failed to decode.
  const factory BridgeError.decode({required String msg}) = BridgeError_Decode;

  /// A `create_shed` stream ended in failure.
  const factory BridgeError.create({required String msg}) = BridgeError_Create;

  /// A client-construction / configuration refusal (e.g. a TLS pin on a
  /// non-https URL).
  const factory BridgeError.config({required String msg}) = BridgeError_Config;

  /// `shed-ext-rc` reported the slug already exists (exit 3).
  const factory BridgeError.rcSlugTaken({required String detail}) =
      BridgeError_RcSlugTaken;

  /// `shed-ext-rc` reported the session was not found (exit 4).
  const factory BridgeError.rcNotFound({required String detail}) =
      BridgeError_RcNotFound;

  /// `shed-ext-rc` rejected the request (exit 2 / validation gate).
  const factory BridgeError.rcBadRequest({required String detail}) =
      BridgeError_RcBadRequest;

  /// `shed-ext-rc` is not installed on the shed (exit 127).
  const factory BridgeError.rcMissingBinary() = BridgeError_RcMissingBinary;

  /// Any other rc binary / transport failure.
  const factory BridgeError.rcFailed({required String detail}) =
      BridgeError_RcFailed;

  /// The control bundle is expired or malformed (`SHED_AUTH_EXPIRED`).
  const factory BridgeError.tokenAuthExpired() = BridgeError_TokenAuthExpired;

  /// The bundle's TLS fingerprint differs from the configured pin
  /// (`SHED_TLS_PIN_MISMATCH`).
  const factory BridgeError.tokenPinMismatch() = BridgeError_TokenPinMismatch;

  /// The bundle omits a required TLS fingerprint (`SHED_TLS_PIN_MISSING`).
  const factory BridgeError.tokenPinMissing() = BridgeError_TokenPinMissing;
}
