// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.5.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'dto_lane.dart';
import 'dto_rc.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `apply`, `ask_for_a_refresh`, `begin_pin`, `bind`, `build_client`, `clear_credentials_ask`, `client`, `deliver`, `discovery_from_probe`, `forward_loop`, `lock`, `new`, `new`, `next_backoff`, `note_down`, `on_bridge_rt`, `open_inner`, `refreshed_since`, `reported_url`, `request_credentials`, `spawn_forwarder`, `spawn_pump`, `teardown`, `timed_out`, `unavailable`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `BridgeGxCredentials`, `GxCredState`, `LaneInner`, `LaneState`, `LaneTasks`, `PinnedDial`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `dial`, `discover`, `drop`

/// Open a live lane on one agent session: dispatch on `kind`, fetch the roster
/// row, and start the pump.
///
/// **Dispatch is the desktop `Lanes::open`'s, arm for arm**: `"opencode"` →
/// [`OpencodeClient`] on the dial URL with no credential source (opencode needs
/// none — a password-protected server answers 401, which surfaces as
/// [`BridgeLaneError::Unauthorized`] and a status-only panel); `"gx"` →
/// [`GxClient`] on the REPORTED url with a [`FixedDial`] transport and the
/// probe's discovery; anything else → [`BridgeLaneError::UnsupportedLane`]
/// **before any I/O**, because a kind with no adapter is a permanent property of
/// the row and there is no reason to spend a round trip discovering it.
///
/// The roster row is fetched BEFORE the subscription starts, for the desktop's
/// reason: a 404 here is an honest `unknown_session` the caller can render,
/// where the same failure inside the pump would be a `Down` the panel has to
/// wait for. It is also the call that fails on a password-protected agent and,
/// on gx, the one that discovers and pins the credential.
///
/// Everything runs on [`bridge_rt`] — not tidiness: the pump and the adapter's
/// held HTTP connections OUTLIVE this call, so they must be created on a runtime
/// that outlives it. FRB's per-call executor goes away when the call returns.
Future<BridgeLane> laneOpen({required BridgeLaneSpec spec}) =>
    RustLib.instance.api.crateApiLaneLaneOpen(spec: spec);

/// Stream this lane's nudges. **One claim**: a second call on the same handle is
/// a no-op rather than a silent split of the nudges between two consumers.
///
/// Dart gets a `true` and nothing else — the payload is "something changed, take
/// a snapshot". The stream stays open until [`lane_close`], INCLUDING after a
/// terminal `Down`: that is how Dart distinguishes "stale, re-open me" (the
/// snapshot says `stale`) from "closed by me" (it called `lane_close`). A stream
/// that ended on `Down` would make those two indistinguishable.
Stream<bool> laneNudges({required BridgeLane lane}) =>
    RustLib.instance.api.crateApiLaneLaneNudges(lane: lane);

/// What this lane's adapter can do. Cached at open (the contract states these
/// are static for the life of the adapter), so it is a lock-free read that keeps
/// answering after [`lane_close`] — a panel unwinding does not need its buttons
/// to start throwing.
BridgeLaneCapabilities laneCapabilities({required BridgeLane lane}) =>
    RustLib.instance.api.crateApiLaneLaneCapabilities(lane: lane);

/// **The one read**, and the nudge acknowledgement: the staged view projected,
/// the pending approvals, the credential flag — under ONE lock — and the dirty
/// bit cleared.
///
/// `since_seq` is `None` for everything (`full: true`) and `Some(s)` for the
/// rows after `s`. The cursor is honored only when it lands inside the current
/// generation's seq window; outside it the answer is every row with
/// `full: true`, which is what makes a generation change, a resubscription and a
/// cursor evicted by the 500-row cap all answer "replace what you hold" instead
/// of a delta with a hole in it. That rule is
/// [`shed_app::lane_view::LaneView::snapshot`]'s and is not restated here.
///
/// Sync: it is a memory read behind a mutex. Making Dart await it would add a
/// microtask to the one call it makes on every nudge.
BridgeLaneSnapshot laneSnapshot({required BridgeLane lane, BigInt? sinceSeq}) =>
    RustLib.instance.api.crateApiLaneLaneSnapshot(
      lane: lane,
      sinceSeq: sinceSeq,
    );

/// Send `text` to the session. [`BridgeSendMode::Interject`] needs
/// [`BridgeLaneCapabilities::interject`]; an adapter that cannot do it answers
/// [`BridgeLaneError::NotAccepting`].
Future<void> laneSend({
  required BridgeLane lane,
  required String text,
  required BridgeSendMode mode,
}) => RustLib.instance.api.crateApiLaneLaneSend(
  lane: lane,
  text: text,
  mode: mode,
);

/// Stop the turn in flight.
///
/// An adapter whose agent refuses a cancel with nothing to cancel surfaces
/// [`BridgeLaneError::NotAccepting`] rather than swallowing it — a hidden
/// refusal is indistinguishable from a cancel that worked. Gate the affordance
/// on the row's `Working` activity so the refusal is rare and explicable (the
/// turn ended between the render and the tap).
Future<void> laneCancel({required BridgeLane lane}) =>
    RustLib.instance.api.crateApiLaneLaneCancel(lane: lane);

/// Answer one approval.
///
/// A second answer to the same approval is refused with
/// [`BridgeLaneError::AlreadySubmitted`] or
/// [`BridgeLaneError::AlreadyResolved`] — a double-tap, not a bug. A
/// [`BridgeLaneAnswer::Choice`] naming an id the approval did not offer, and a
/// [`BridgeLaneAnswer::Permission`] whose decision matches no offered option
/// kind (or SEVERAL of them), are [`BridgeLaneError::BadRequest`]: the adapter
/// never picks the nearest option, and never breaks a tie only the human can
/// break. [`super::dto_lane::lane_option_for`] is how a panel finds out in
/// advance.
Future<void> laneAnswer({
  required BridgeLane lane,
  required String approvalId,
  required BridgeLaneAnswer answer,
}) => RustLib.instance.api.crateApiLaneLaneAnswer(
  lane: lane,
  approvalId: approvalId,
  answer: answer,
);

/// Answer a pending gx credential ask: parse a FRESH probe and hand it to the
/// waiting discovery.
///
/// The controller calls it when a snapshot reports
/// [`BridgeLaneSnapshot::needs_credentials`]. Pinning then resumes **in place** —
/// no `Down`, no re-open, the generation and the ring intact — which is the
/// whole point of asking rather than failing: a leader restart is recoverable
/// without the panel flickering.
///
/// Calling it with nothing waiting is fine and cheap: the value is held for the
/// next epoch's ask. Calling it on a lane that needs no credentials is a
/// [`BridgeLaneError::BadRequest`], because a client that ran an SSH probe for
/// an opencode lane has a bug worth hearing about.
Future<void> laneRefreshCredentials({
  required BridgeLane lane,
  required List<int> gxProbeStdout,
}) => RustLib.instance.api.crateApiLaneLaneRefreshCredentials(
  lane: lane,
  gxProbeStdout: gxProbeStdout,
);

/// End the lane — the SYNCHRONOUS co-primary teardown (a Riverpod `onDispose`
/// calls this). Idempotent; `Drop` is the backstop.
///
/// It aborts the pump and the forwarder and drops the adapter, which closes the
/// connections it holds. The nudge stream ends here and only here.
void laneClose({required BridgeLane lane}) =>
    RustLib.instance.api.crateApiLaneLaneClose(lane: lane);

/// The command Dart execs on the far side to read gx's discovery, verbatim.
///
/// **Dart composes no part of it**, and that is the whole point: SSH has no argv
/// API, so this multi-line script crosses as ONE string the far side re-parses,
/// and every transport that composes it has to compose it identically. It is
/// [`shed_core::machine::display_line`] over `["sh", "-c", PROBE_SCRIPT]` — the
/// same quoter [`shed_app::machine::exec`] hands `ssh`, so the phone's
/// `dartssh2` and the desktop's `ssh` binary put the same bytes on the wire.
/// shed's `tests/machine-transport` owns that contract as its `gx-probe`
/// scenario; a Rust test in this module pins the exact line against that
/// scenario's golden.
///
/// Sync because it is a constant, and a `String` rather than an argv list
/// because an argv list is precisely what Dart must not be given: it would then
/// own the quoting.
String gxProbeRemoteCommand() =>
    RustLib.instance.api.crateApiLaneGxProbeRemoteCommand();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BridgeLane>>
abstract class BridgeLane implements RustOpaqueInterface {}

/// Everything [`lane_open`] needs to build one lane — the row's stamp plus the
/// two things only the phone's transport knows.
///
/// **`reported_url` and `dial_url` are different values and are never
/// conflated.** `reported_url` is the loopback URL the agent announced on ITS
/// host, and it is what a gx discovery record is matched against;
/// `dial_url` is where this phone actually reaches it — the near end of the
/// `RoostTunnel`-shaped forward Dart already holds, or the same address again
/// when the agent is on this device. The contract is explicit that an
/// implementation which dialled the reported URL would be wrong over SSH.
class BridgeLaneSpec {
  /// `"opencode"` or `"gx"`. Anything else is
  /// [`BridgeLaneError::UnsupportedLane`], refused before any I/O.
  final String kind;
  final String sessionId;
  final String reportedUrl;
  final String dialUrl;

  /// The raw stdout of [`gx_probe_remote_command`], run by Dart over the
  /// machine's SSH client. Required for a `"gx"` lane and ignored for every
  /// other kind.
  ///
  /// **These bytes are one `cat` away from being a bearer token.** They are
  /// parsed inside [`discovery_from_probe`] and dropped there; nothing in this
  /// module logs them, stores them past the parse, or puts any part of them in
  /// an error string.
  final Uint8List? gxProbeStdout;

  const BridgeLaneSpec({
    required this.kind,
    required this.sessionId,
    required this.reportedUrl,
    required this.dialUrl,
    this.gxProbeStdout,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      sessionId.hashCode ^
      reportedUrl.hashCode ^
      dialUrl.hashCode ^
      gxProbeStdout.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeLaneSpec &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          sessionId == other.sessionId &&
          reportedUrl == other.reportedUrl &&
          dialUrl == other.dialUrl &&
          gxProbeStdout == other.gxProbeStdout;
}
