// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.5.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'dto_lane.dart';
import 'dto_rc.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `apply`, `build_client`, `client`, `forward_loop`, `lock`, `next_backoff`, `note_down`, `on_bridge_rt`, `open_inner`, `spawn_forwarder`, `spawn_pump`, `teardown`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `LaneInner`, `LaneState`, `LaneTasks`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `drop`

/// Open a live lane on one agent session: dispatch on `kind`, fetch the roster
/// row, and start the pump.
///
/// **Dispatch is the desktop `Lanes::open`'s, arm for arm**: `"opencode"` →
/// an [`OpencodeSource`] on the dial URL with no credential source (opencode
/// needs none — a password-protected server answers 401, which surfaces as
/// [`BridgeLaneError::Unauthorized`] and a status-only panel), and the
/// session-scoped lane it opens for the row's id (plan 025 §3.2.6); anything
/// else → [`BridgeLaneError::UnsupportedLane`] **before any I/O**, because a
/// kind with no adapter is a permanent property of the row and there is no
/// reason to spend a round trip discovering it.
///
/// The roster row is fetched BEFORE the subscription starts, for the desktop's
/// reason: a 404 here is an honest `unknown_session` the caller can render,
/// where the same failure inside the pump would be a `Down` the panel has to
/// wait for. It is also the call that fails on a password-protected agent.
///
/// Everything runs on [`bridge_rt`] — not tidiness: the pump and the adapter's
/// held HTTP connections OUTLIVE this call, so they must be created on a runtime
/// that outlives it. FRB's per-call executor goes away when the call returns.
Future<BridgeLane> laneOpen({required BridgeLaneSpec spec}) =>
    RustLib.instance.api.crateApiLaneLaneOpen(spec: spec);

/// Stream this lane's nudges. **One claim**: a second call on the same handle is
/// a no-op rather than a silent split of the nudges between two consumers.
///
/// Dart gets a `true` and nothing else — the payload is "something changed, take
/// a snapshot". The stream stays open until [`lane_close`], INCLUDING after a
/// terminal `Down`: that is how Dart distinguishes "ended, re-open me" (the
/// snapshot says `ended`) from "closed by me" (it called `lane_close`). A stream
/// that ended on `Down` would make those two indistinguishable.
Stream<bool> laneNudges({required BridgeLane lane}) =>
    RustLib.instance.api.crateApiLaneLaneNudges(lane: lane);

/// **The one read**, and the nudge acknowledgement: the staged view projected
/// — the transcript, the pending approvals, and the session's live row,
/// capabilities and settings — under ONE lock, and the dirty bit cleared.
///
/// It is also where a panel reads what the session can do. There is no
/// `lane_capabilities` getter (plan 025 §3.2.1): capabilities are per session
/// and ride the stream, so a getter cached at open would be stale by
/// construction before the first seed. A closed lane still projects its last
/// view, capabilities included, so a panel unwinding keeps its buttons.
///
/// `since_seq` is `None` for everything (`full: true`) and `Some(s)` for the
/// rows after `s`. The cursor is honored only when it lands inside the current
/// generation's seq window; outside it the answer is every row with
/// `full: true`, which is what makes a generation change, a resubscription and a
/// cursor evicted by the 500-row cap all answer "replace what you hold" instead
/// of a delta with a hole in it. That rule is
/// [`shed_app::lane_view::LaneView::snapshot`]'s and is not restated here.
///
/// Sync: it is a memory read behind a mutex. Making Dart await it would add a
/// microtask to the one call it makes on every nudge.
BridgeLaneSnapshot laneSnapshot({required BridgeLane lane, BigInt? sinceSeq}) =>
    RustLib.instance.api.crateApiLaneLaneSnapshot(
      lane: lane,
      sinceSeq: sinceSeq,
    );

/// Send `text` to the session. [`BridgeSendMode::Interject`] needs the
/// snapshot's [`super::dto_lane::BridgeLaneCapabilities::interject`]; an adapter
/// that cannot do it answers [`BridgeLaneError::NotAccepting`].
Future<void> laneSend({
  required BridgeLane lane,
  required String text,
  required BridgeSendMode mode,
}) => RustLib.instance.api.crateApiLaneLaneSend(
  lane: lane,
  text: text,
  mode: mode,
);

/// Stop the turn in flight.
///
/// An adapter whose agent refuses a cancel with nothing to cancel surfaces
/// [`BridgeLaneError::NotAccepting`] rather than swallowing it — a hidden
/// refusal is indistinguishable from a cancel that worked. Gate the affordance
/// on the row's `Working` activity so the refusal is rare and explicable (the
/// turn ended between the render and the tap).
Future<void> laneCancel({required BridgeLane lane}) =>
    RustLib.instance.api.crateApiLaneLaneCancel(lane: lane);

/// Answer one approval.
///
/// A second answer to the same approval is refused with
/// [`BridgeLaneError::AlreadySubmitted`] or
/// [`BridgeLaneError::AlreadyResolved`] — a double-tap, not a bug. A
/// [`BridgeLaneAnswer::Choice`] naming an id the approval did not offer, and a
/// [`BridgeLaneAnswer::Permission`] whose decision matches no offered option
/// kind (or SEVERAL of them), are [`BridgeLaneError::BadRequest`]: the adapter
/// never picks the nearest option, and never breaks a tie only the human can
/// break. [`super::dto_lane::lane_option_for`] is how a panel finds out in
/// advance.
Future<void> laneAnswer({
  required BridgeLane lane,
  required String approvalId,
  required BridgeLaneAnswer answer,
}) => RustLib.instance.api.crateApiLaneLaneAnswer(
  lane: lane,
  approvalId: approvalId,
  answer: answer,
);

/// End the lane — the SYNCHRONOUS co-primary teardown (a Riverpod `onDispose`
/// calls this). Idempotent; `Drop` is the backstop.
///
/// It aborts the pump and the forwarder and drops the adapter, which closes the
/// connections it holds. The nudge stream ends here and only here.
void laneClose({required BridgeLane lane}) =>
    RustLib.instance.api.crateApiLaneLaneClose(lane: lane);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BridgeLane>>
abstract class BridgeLane implements RustOpaqueInterface {}

/// Everything [`lane_open`] needs to build one lane — the row's stamp plus the
/// two things only the phone's transport knows.
///
/// **`reported_url` and `dial_url` are different values and are never
/// conflated.** `reported_url` is the loopback URL the agent announced on ITS
/// host; `dial_url` is where this phone actually reaches it — the near end of the
/// `RoostTunnel`-shaped forward Dart already holds, or the same address again
/// when the agent is on this device. The contract is explicit that an
/// implementation which dialled the reported URL would be wrong over SSH.
class BridgeLaneSpec {
  /// `"opencode"`. Anything else is
  /// [`BridgeLaneError::UnsupportedLane`], refused before any I/O.
  final String kind;
  final String sessionId;
  final String reportedUrl;
  final String dialUrl;

  const BridgeLaneSpec({
    required this.kind,
    required this.sessionId,
    required this.reportedUrl,
    required this.dialUrl,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      sessionId.hashCode ^
      reportedUrl.hashCode ^
      dialUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeLaneSpec &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          sessionId == other.sessionId &&
          reportedUrl == other.reportedUrl &&
          dialUrl == other.dialUrl;
}
