// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.5.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `bytes`, `spawn`, `sse`, `status`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Response`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `drop`

/// Stand up the hermetic rc-events SSE server. Test-support only.
Future<BridgeTestSse> spawnWatcherTestSse() =>
    RustLib.instance.api.crateApiLocalSseSpawnWatcherTestSse();

/// Stand up the hermetic create SSE server. Test-support only.
Future<BridgeTestSse> spawnCreateTestSse() =>
    RustLib.instance.api.crateApiLocalSseSpawnCreateTestSse();

/// Stand up a server that answers every request with a fixed HTTP `status` and a
/// tiny JSON body — for the create-stream one-shot-on-error proof (Codex #8).
/// Test-support only.
Future<BridgeTestSse> spawnStatusTestSse({required int status}) =>
    RustLib.instance.api.crateApiLocalSseSpawnStatusTestSse(status: status);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BridgeTestSse>>
abstract class BridgeTestSse implements RustOpaqueInterface {
  /// The `http://127.0.0.1:<port>` an OPEN-mode `BridgeClient` is built against.
  String baseUrl();

  /// Idempotent synchronous stop: abort the accept loop, decrement the counter.
  void stop();
}
