// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.5.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'dto_rc.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'machine.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `client`, `forward_loop`, `machine_argv`, `teardown`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `WatcherInner`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `drop`, `eq`, `fmt`

/// Start watching the hub reachable on `127.0.0.1:<local_port>`.
///
/// `local_port` is the Dart-side tunnel's listening port (see the module doc).
/// `machine` names the machine for diagnostics only — nothing is keyed off it
/// here, because one watcher serves exactly one machine.
///
/// Does NOT dial anything itself: the watcher connects on its own schedule and
/// reports [`BridgeMachineUpdate::Down`] until it can, so a machine that is
/// asleep costs a caller nothing at construction time.
Future<BridgeMachineWatcher> createMachineWatcher({
  required String machine,
  required int localPort,
}) => RustLib.instance.api.crateApiMachineCreateMachineWatcher(
  machine: machine,
  localPort: localPort,
);

/// Stream this machine's updates. Claims the receiver, so a second call on the
/// same handle is a no-op rather than a silent split of the stream.
Stream<BridgeMachineUpdate> machineWatcherEvents({
  required BridgeMachineWatcher handle,
}) => RustLib.instance.api.crateApiMachineMachineWatcherEvents(handle: handle);

/// Stop watching — the SYNCHRONOUS co-primary teardown (a Riverpod `onDispose`
/// calls this). `Drop` is the backstop.
Future<void> stopMachineWatcher({required BridgeMachineWatcher handle}) =>
    RustLib.instance.api.crateApiMachineStopMachineWatcher(handle: handle);

/// Start a turn on a machine session. Returns the turn id.
Future<String> machineTurn({
  required int localPort,
  required String slug,
  required String text,
}) => RustLib.instance.api.crateApiMachineMachineTurn(
  localPort: localPort,
  slug: slug,
  text: text,
);

/// Interrupt the running turn. `false` means nothing was running — a legitimate
/// answer, not a failure.
Future<bool> machineInterrupt({required int localPort, required String slug}) =>
    RustLib.instance.api.crateApiMachineMachineInterrupt(
      localPort: localPort,
      slug: slug,
    );

/// Send a line of input to a TUI-laned session (the keystroke path).
Future<void> machineInput({
  required int localPort,
  required String slug,
  required String text,
}) => RustLib.instance.api.crateApiMachineMachineInput(
  localPort: localPort,
  slug: slug,
  text: text,
);

/// Answer a pending approval. `decision` is `allow` / `allow_always` / `deny`.
///
/// Only for a kind whose `approvals` capability is `"remote"`; a `"tui"` kind
/// reports approvals for INFORMATION only and must be answered in its terminal.
Future<String> machineApprove({
  required int localPort,
  required String slug,
  required String id,
  required String decision,
}) => RustLib.instance.api.crateApiMachineMachineApprove(
  localPort: localPort,
  slug: slug,
  id: id,
  decision: decision,
);

/// Kill a session on a machine.
///
/// The one verb that does NOT go over the hub: the hub observes and steers, it
/// does not remove. A kill is the one-shot engine's `rc kill`, which the Dart
/// side runs over SSH exactly as it runs `list`/`create` for a shed — so it
/// takes the composed argv, not a port.
Future<List<String>> machineKillArgv({
  required String rcBin,
  required String slug,
}) => RustLib.instance.api.crateApiMachineMachineKillArgv(
  rcBin: rcBin,
  slug: slug,
);

/// `<rc_bin> rc list` on a machine — the CAPABILITY probe.
///
/// The list response carries the engine's capability envelope, and those
/// `kind_features` are what gate every control the UI offers. Without this the
/// probe runs the guest binary name, exits non-zero, and the client degrades to
/// observe-only — correct, safe, and completely invisible, which is why it went
/// unnoticed until a live machine had a steerable session on it.
Future<List<String>> machineListArgv({required String rcBin}) =>
    RustLib.instance.api.crateApiMachineMachineListArgv(rcBin: rcBin);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BridgeMachineWatcher>>
abstract class BridgeMachineWatcher implements RustOpaqueInterface {}

@freezed
sealed class BridgeMachineUpdate with _$BridgeMachineUpdate {
  const BridgeMachineUpdate._();

  /// The machine's full session list, as of this connection. Replaces
  /// whatever the consumer held; arrives on EVERY successful connect, and
  /// again whenever the feed mentions a session the snapshot did not cover.
  const factory BridgeMachineUpdate.snapshot({
    required List<BridgeRcSession> sessions,
  }) = BridgeMachineUpdate_Snapshot;

  /// A live feed event.
  const factory BridgeMachineUpdate.event({required BridgeRcEvent event}) =
      BridgeMachineUpdate_Event;

  /// The feed is not up: the tunnel is not there, the hub did not answer, or
  /// the stream ended. The watcher backs off and retries.
  ///
  /// **A normal state, not an error.** A machine that is asleep, off-network,
  /// or simply has no hub running is the everyday case; the UI renders its
  /// rows as last-known with a reason rather than failing.
  const factory BridgeMachineUpdate.down({required String reason}) =
      BridgeMachineUpdate_Down;
}
