// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.5.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'dto_rc.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'machine.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `forward_loop`, `teardown`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `WatcherInner`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `drop`, `eq`, `fmt`

/// Start watching the hub reachable on `127.0.0.1:<local_port>`.
///
/// `local_port` is the Dart-side tunnel's listening port (see the module doc).
/// `machine` names the machine for diagnostics only — nothing is keyed off it
/// here, because one watcher serves exactly one machine.
///
/// Does NOT dial anything itself: the watcher connects on its own schedule and
/// reports [`BridgeMachineUpdate::Down`] until it can, so a machine that is
/// asleep costs a caller nothing at construction time.
Future<BridgeMachineWatcher> createMachineWatcher({
  required String machine,
  required int localPort,
}) => RustLib.instance.api.crateApiMachineCreateMachineWatcher(
  machine: machine,
  localPort: localPort,
);

/// Stream this machine's updates. Claims the receiver, so a second call on the
/// same handle is a no-op rather than a silent split of the stream.
Stream<BridgeMachineUpdate> machineWatcherEvents({
  required BridgeMachineWatcher handle,
}) => RustLib.instance.api.crateApiMachineMachineWatcherEvents(handle: handle);

/// Stop watching — the SYNCHRONOUS co-primary teardown (a Riverpod `onDispose`
/// calls this). `Drop` is the backstop.
Future<void> stopMachineWatcher({required BridgeMachineWatcher handle}) =>
    RustLib.instance.api.crateApiMachineStopMachineWatcher(handle: handle);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BridgeMachineWatcher>>
abstract class BridgeMachineWatcher implements RustOpaqueInterface {}

@freezed
sealed class BridgeMachineUpdate with _$BridgeMachineUpdate {
  const BridgeMachineUpdate._();

  /// The machine's full session list, as of this connection. Replaces
  /// whatever the consumer held; arrives on EVERY successful connect, and
  /// again whenever the feed mentions a session the snapshot did not cover.
  const factory BridgeMachineUpdate.snapshot({
    required List<BridgeRcSession> sessions,
  }) = BridgeMachineUpdate_Snapshot;

  /// A live feed event.
  const factory BridgeMachineUpdate.event({required BridgeRcEvent event}) =
      BridgeMachineUpdate_Event;

  /// The feed is not up: the tunnel is not there, the hub did not answer, or
  /// the stream ended. The watcher backs off and retries.
  ///
  /// **A normal state, not an error.** A machine that is asleep, off-network,
  /// or simply has no hub running is the everyday case; the UI renders its
  /// rows as last-known with a reason rather than failing.
  const factory BridgeMachineUpdate.down({required String reason}) =
      BridgeMachineUpdate_Down;
}
