// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.5.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'mint.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `drain_pending_on_shutdown`, `pending`, `run_mint`, `shutdown_cell`, `sink_cell`, `take_pending`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `BridgeMinter`, `MintResolution`, `PendingGuard`, `RunMintError`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `drop`, `mint`

/// Register the app-scoped mint StreamSink and stay alive until
/// [`shutdown_mint_sink`] fires (keeping the FRB stream open for the app's
/// lifetime). Dart listens BEFORE any `BridgeClient` is constructed
/// (listener-before-client); a `mint` emitted with no sink fails fast.
///
/// Generation-guarded (Codex review #1): each registration takes a fresh
/// generation and, if a prior sink is live, evicts it FIRST (fires its shutdown
/// + drains its pending). When this task's await returns, it clears the slot
/// ONLY if it still owns the generation — so a later sink B installed while A's
/// task was parked is never clobbered by A.
Stream<BridgeMintRequest> setMintSink() =>
    RustLib.instance.api.crateApiMintSetMintSink();

/// End the mint sink fn cleanly (Dart calls this in `onDispose` before
/// unsubscribing). Idempotent. Resolves EVERY parked mint immediately with a
/// non-secret `SinkShutdown` (Codex review #2 — no more 45 s strand), then fires
/// the sink's shutdown signal. Synchronous so Riverpod `onDispose` can call it
/// without an unawaitable future (Codex review #9).
void shutdownMintSink() => RustLib.instance.api.crateApiMintShutdownMintSink();

/// The direct integration proof of the full inversion (retained from B1): emit →
/// await Dart's submit → parse in Rust → return the NON-SECRET fields (token
/// length only). The real app never calls this; `BridgeClient` mints via the
/// provider path. Kept because it exercises the inversion end-to-end from Dart
/// without needing a live shed-server.
Future<BridgeControlBundle> demoMint({
  required String host,
  required int sshPort,
  required String baseUrl,
  String? expectedTlsPin,
  required BigInt timeoutMs,
}) => RustLib.instance.api.crateApiMintDemoMint(
  host: host,
  sshPort: sshPort,
  baseUrl: baseUrl,
  expectedTlsPin: expectedTlsPin,
  timeoutMs: timeoutMs,
);

/// Dart submits its mint result here. Benign no-op ("rejected") for an unknown /
/// late / duplicate `request_id` — never a panic. Single-resume via remove.
Future<String> submitMintResult({
  required String requestId,
  required BridgeMintOutcome outcome,
}) => RustLib.instance.api.crateApiMintSubmitMintResult(
  requestId: requestId,
  outcome: outcome,
);

/// AC#5 helper: proves the request DTO carries no token field (there is nothing
/// token-bearing to leak on the Rust→Dart request). The real enforcement is the
/// unit test below.
bool mintRequestIsTokenFree({required BridgeMintRequest req}) =>
    RustLib.instance.api.crateApiMintMintRequestIsTokenFree(req: req);

/// The parsed control bundle returned to Dart from [`demo_mint`] — TOKEN OMITTED
/// (only its length crosses back; AC#5).
class BridgeControlBundle {
  final bool tokenPresent;
  final int tokenLen;
  final BigInt expiresAtUnix;
  final String tlsCertFingerprint;
  final int httpsPort;

  const BridgeControlBundle({
    required this.tokenPresent,
    required this.tokenLen,
    required this.expiresAtUnix,
    required this.tlsCertFingerprint,
    required this.httpsPort,
  });

  @override
  int get hashCode =>
      tokenPresent.hashCode ^
      tokenLen.hashCode ^
      expiresAtUnix.hashCode ^
      tlsCertFingerprint.hashCode ^
      httpsPort.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeControlBundle &&
          runtimeType == other.runtimeType &&
          tokenPresent == other.tokenPresent &&
          tokenLen == other.tokenLen &&
          expiresAtUnix == other.expiresAtUnix &&
          tlsCertFingerprint == other.tlsCertFingerprint &&
          httpsPort == other.httpsPort;
}

@freezed
sealed class BridgeMintOutcome with _$BridgeMintOutcome {
  const BridgeMintOutcome._();

  const factory BridgeMintOutcome.success({required String rawStdout}) =
      BridgeMintOutcome_Success;
  const factory BridgeMintOutcome.failure({required String code}) =
      BridgeMintOutcome_Failure;
}

/// The need-token request Rust emits to Dart. Carries the IMMUTABLE transport
/// identity (plan §3.2) — not a mutable server-name to be looked up at submit
/// time.
class BridgeMintRequest {
  final String requestId;
  final String host;
  final int sshPort;
  final String baseUrl;
  final String? expectedTlsPin;

  const BridgeMintRequest({
    required this.requestId,
    required this.host,
    required this.sshPort,
    required this.baseUrl,
    this.expectedTlsPin,
  });

  @override
  int get hashCode =>
      requestId.hashCode ^
      host.hashCode ^
      sshPort.hashCode ^
      baseUrl.hashCode ^
      expectedTlsPin.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeMintRequest &&
          runtimeType == other.runtimeType &&
          requestId == other.requestId &&
          host == other.host &&
          sshPort == other.sshPort &&
          baseUrl == other.baseUrl &&
          expectedTlsPin == other.expectedTlsPin;
}
