// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `pending`, `shutdown_cell`, `sink_cell`, `take_pending`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `MintResolution`, `PendingGuard`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `drop`

/// Register the app-scoped mint StreamSink and stay alive until `shutdown_mint_sink`
/// fires, keeping the FRB stream open for the app's lifetime. A stream fn that
/// returned immediately would have FRB close the sink, invalidating the stored
/// handle; awaiting a shutdown signal keeps it live AND lets Dart tear it down
/// cleanly (a bare park would deadlock the unsubscribe). Dart calls this
/// (listens) BEFORE any mint is requested (listener-before-client).
Stream<BridgeMintRequest> setMintSink() =>
    RustLib.instance.api.crateApiMintSetMintSink();

/// End the mint sink fn cleanly (Dart calls this before unsubscribing). Idempotent.
Future<void> shutdownMintSink() =>
    RustLib.instance.api.crateApiMintShutdownMintSink();

/// Demo of the full inversion: emit a need-token request → await Dart's submit
/// (bounded by `timeout_ms`) → parse the bundle in Rust with the expected pin →
/// return the non-secret fields. Fails fast if no sink is registered.
///
/// Runtime note: the await is a plain oneshot channel (safe on FRB's executor,
/// which lacks a tokio TIME driver); the timeout is driven by a separate sleep
/// task on `bridge_rt` (which has one), which resolves the same oneshot.
Future<BridgeControlBundle> demoMint({
  required String host,
  required int sshPort,
  required String baseUrl,
  String? expectedTlsPin,
  required BigInt timeoutMs,
}) => RustLib.instance.api.crateApiMintDemoMint(
  host: host,
  sshPort: sshPort,
  baseUrl: baseUrl,
  expectedTlsPin: expectedTlsPin,
  timeoutMs: timeoutMs,
);

/// Dart submits its mint result here. Benign no-op ("rejected") for an unknown /
/// late / duplicate `request_id` — never a panic. Single-resume via remove.
Future<String> submitMintResult({
  required String requestId,
  required BridgeMintOutcome outcome,
}) => RustLib.instance.api.crateApiMintSubmitMintResult(
  requestId: requestId,
  outcome: outcome,
);

/// AC#5 guard exposed for a Dart-visible assertion: neither the request nor the
/// outcome types leak token bytes under Debug/Display. (The real enforcement is
/// the Rust unit test below; this just proves the types carry no token to Dart.)
bool mintRequestIsTokenFree({required BridgeMintRequest req}) =>
    RustLib.instance.api.crateApiMintMintRequestIsTokenFree(req: req);

/// The parsed control bundle returned to Dart — TOKEN OMITTED (only its length
/// crosses back; AC#5).
class BridgeControlBundle {
  final bool tokenPresent;
  final int tokenLen;
  final BigInt expiresAtUnix;
  final String tlsCertFingerprint;
  final int httpsPort;

  const BridgeControlBundle({
    required this.tokenPresent,
    required this.tokenLen,
    required this.expiresAtUnix,
    required this.tlsCertFingerprint,
    required this.httpsPort,
  });

  @override
  int get hashCode =>
      tokenPresent.hashCode ^
      tokenLen.hashCode ^
      expiresAtUnix.hashCode ^
      tlsCertFingerprint.hashCode ^
      httpsPort.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeControlBundle &&
          runtimeType == other.runtimeType &&
          tokenPresent == other.tokenPresent &&
          tokenLen == other.tokenLen &&
          expiresAtUnix == other.expiresAtUnix &&
          tlsCertFingerprint == other.tlsCertFingerprint &&
          httpsPort == other.httpsPort;
}

/// Dart's answer to a mint request. When `success`, `raw_stdout` carries the
/// raw `shed-ext-rc`-style bundle (the token-bearing payload); otherwise
/// `failure_code` carries a non-secret code.
///
/// NOTE (FRB friction, D2): this would ideally be a fielded enum
/// (`Success{raw_stdout}|Failure{code}`), but FRB 2.12 renders fielded enums via
/// `freezed`, and freezed 2.x won't resolve on this repo's Dart SDK (^3.12) while
/// FRB 2.12's codegen rejects freezed 3.x. A tagged struct sidesteps freezed
/// entirely and proves the same inversion; the real migration must resolve the
/// freezed pin (or move to FRB 2.13) before using sealed-class DTOs.
class BridgeMintOutcome {
  final bool success;
  final String rawStdout;
  final String failureCode;

  const BridgeMintOutcome({
    required this.success,
    required this.rawStdout,
    required this.failureCode,
  });

  @override
  int get hashCode =>
      success.hashCode ^ rawStdout.hashCode ^ failureCode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeMintOutcome &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          rawStdout == other.rawStdout &&
          failureCode == other.failureCode;
}

/// The need-token request Rust emits to Dart. Carries the IMMUTABLE transport
/// identity (plan §3.2) — not a mutable server-name to be looked up at submit
/// time.
class BridgeMintRequest {
  final String requestId;
  final String host;
  final int sshPort;
  final String baseUrl;
  final String? expectedTlsPin;

  const BridgeMintRequest({
    required this.requestId,
    required this.host,
    required this.sshPort,
    required this.baseUrl,
    this.expectedTlsPin,
  });

  @override
  int get hashCode =>
      requestId.hashCode ^
      host.hashCode ^
      sshPort.hashCode ^
      baseUrl.hashCode ^
      expectedTlsPin.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeMintRequest &&
          runtimeType == other.runtimeType &&
          requestId == other.requestId &&
          host == other.host &&
          sshPort == other.sshPort &&
          baseUrl == other.baseUrl &&
          expectedTlsPin == other.expectedTlsPin;
}
