// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.5.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `acquire`, `csr_base64`, `generate`, `sanitize`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `EphemeralEnrollment`, `PreviewSlot`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `drop`, `drop`, `fmt`

/// Preview a server the app has never talked to: enroll, parse, sanitize, dispose.
///
/// `timeout_ms` bounds the whole SSH round-trip (Dart dial + remote exec +
/// submit). The add-server screen is interactive, so keep it in the same family
/// as Dart's own SSH timeout (15 s) rather than the background mint's 45 s —
/// §7 P8's budget alignment.
///
/// ONE preview at a time, process-wide: a second concurrent call is refused with
/// [`BridgeError::Config`] rather than queued, because two outstanding requests
/// are two answers that could be transposed — see [`PreviewSlot`]. The refusal
/// clears as soon as the first preview settles, by any exit.
///
/// Errors are the typed [`BridgeError`] the app already switches on: a bundle
/// with no usable TLS pin is `TokenPinMissing`, an expired/malformed one is
/// `TokenAuthExpired`, and everything else (no listener, decline, timeout,
/// oversized response, a second concurrent preview) is a `Transport`/`Config`
/// message. None of them carry credential bytes.
Future<BridgeAddServerPreview> previewAddServer({
  required String host,
  required int sshPort,
  required BigInt timeoutMs,
}) => RustLib.instance.api.crateApiPreviewPreviewAddServer(
  host: host,
  sshPort: sshPort,
  timeoutMs: timeoutMs,
);

/// What the add-server flow shows the user, and everything Dart needs to persist
/// a `ServerRecord` — with NOTHING it does not need.
///
/// Deliberately absent: the client certificate, its serial, and above all the
/// private key (which never leaves the [`preview_add_server`] frame). The SSH
/// host-key fingerprint is absent too, for a different reason — Dart learns it
/// from the TOFU store during the connection this preview drove, so Rust would
/// only be echoing it back.
class BridgeAddServerPreview {
  /// `"token"` or `"mtls"` — the shape the server issued, normalized through
  /// `AuthMode::from_wire` (so a bundle's legacy `"secure"`, or no `auth_mode`
  /// key at all, reads as `"token"`).
  final String authMode;

  /// Canonical `sha256:<hex>` pin of the server's TLS leaf, delivered over the
  /// host-key-pinned SSH channel. The user confirms this.
  final String tlsCertFingerprint;
  final int httpsPort;

  /// The seed bearer token — **token mode only**, `None` in mtls mode.
  final String? token;

  /// Expiry of [`Self::token`] in unix seconds; `None` whenever `token` is.
  final BigInt? tokenExpiresAtUnix;

  const BridgeAddServerPreview({
    required this.authMode,
    required this.tlsCertFingerprint,
    required this.httpsPort,
    this.token,
    this.tokenExpiresAtUnix,
  });

  @override
  int get hashCode =>
      authMode.hashCode ^
      tlsCertFingerprint.hashCode ^
      httpsPort.hashCode ^
      token.hashCode ^
      tokenExpiresAtUnix.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeAddServerPreview &&
          runtimeType == other.runtimeType &&
          authMode == other.authMode &&
          tlsCertFingerprint == other.tlsCertFingerprint &&
          httpsPort == other.httpsPort &&
          token == other.token &&
          tokenExpiresAtUnix == other.tokenExpiresAtUnix;
}
