// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.5.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'dto_rc.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`

/// `shed-ext-rc list` argv (pure builder).
Future<List<String>> rcListArgv() =>
    RustLib.instance.api.crateApiRcRunnerRcListArgv();

/// `shed-ext-rc kill --slug <slug>` argv (pure builder).
Future<List<String>> rcKillArgv({required String slug}) =>
    RustLib.instance.api.crateApiRcRunnerRcKillArgv(slug: slug);

/// `shed-ext-rc prompt --slug <slug> [--session-id <id>]` argv (the B0 builder).
Future<List<String>> rcPromptArgv({required String slug, String? sessionId}) =>
    RustLib.instance.api.crateApiRcRunnerRcPromptArgv(
      slug: slug,
      sessionId: sessionId,
    );

/// The validating create gate: builds the `create --wait` argv + stdin, running
/// `permission_mode` through `validate_permission_mode`. An invalid mode for the
/// kind is an [`BridgeError::RcBadRequest`] (no argv built). `kind` is the wire
/// string (`claude-rc`/`shell`/…); mobile owns `created_by`.
Future<BridgeRcInvocation> rcCreateInvocation({
  required String kind,
  required String name,
  required String slug,
  required String target,
  String? workdir,
  String? permissionMode,
  String? prompt,
}) => RustLib.instance.api.crateApiRcRunnerRcCreateInvocation(
  kind: kind,
  name: name,
  slug: slug,
  target: target,
  workdir: workdir,
  permissionMode: permissionMode,
  prompt: prompt,
);

/// Decode a `shed-ext-rc list` stdout (what the Dart runner captured) into the
/// neutral session DTOs — the "decode-in" half of the round-trip.
Future<List<BridgeRcSessionDto>> rcDecodeList({required String stdout}) =>
    RustLib.instance.api.crateApiRcRunnerRcDecodeList(stdout: stdout);

/// Map a non-zero exit from the Dart runner to a typed [`BridgeError`] (exit 3 →
/// `RcSlugTaken`, 4 → `RcNotFound`, 2 → `RcBadRequest`, 127 → `RcMissingBinary`,
/// … ). Returns the error value (not a `Result`) — the caller already knows the
/// run failed.
Future<BridgeError> rcErrorFromExit({
  required int exitCode,
  required String stderr,
  required String stdout,
}) => RustLib.instance.api.crateApiRcRunnerRcErrorFromExit(
  exitCode: exitCode,
  stderr: stderr,
  stdout: stdout,
);

/// argv + optional stdin, marshalled to Dart. The Dart runner executes `argv`
/// over dartssh2, writing `stdin` (the initial prompt) to the process stdin.
class BridgeRcInvocation {
  final List<String> argv;
  final String? stdin;

  const BridgeRcInvocation({required this.argv, this.stdin});

  @override
  int get hashCode => argv.hashCode ^ stdin.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRcInvocation &&
          runtimeType == other.runtimeType &&
          argv == other.argv &&
          stdin == other.stdin;
}
