// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `wire_of`

/// `shed-ext-rc list` argv (pure builder).
Future<List<String>> rcListArgv() =>
    RustLib.instance.api.crateApiRcRunnerRcListArgv();

/// `shed-ext-rc kill --slug <slug>` argv (pure builder).
Future<List<String>> rcKillArgv({required String slug}) =>
    RustLib.instance.api.crateApiRcRunnerRcKillArgv(slug: slug);

/// `shed-ext-rc prompt --slug <slug> [--session-id <id>]` argv (added in the
/// merged shed rev — the B0 `prompt_argv` gap is already closed here).
Future<List<String>> rcPromptArgv({required String slug, String? sessionId}) =>
    RustLib.instance.api.crateApiRcRunnerRcPromptArgv(
      slug: slug,
      sessionId: sessionId,
    );

/// The validating create gate: builds the `create --wait` argv + stdin, running
/// `permission_mode` through `validate_permission_mode`. An invalid mode for the
/// kind returns an error (no argv built). `kind` is the wire string
/// (`claude`/`shell`/…); mobile owns `created_by`.
Future<BridgeRcInvocation> rcCreateInvocation({
  required String kind,
  required String name,
  required String slug,
  required String target,
  String? workdir,
  String? permissionMode,
  String? prompt,
}) => RustLib.instance.api.crateApiRcRunnerRcCreateInvocation(
  kind: kind,
  name: name,
  slug: slug,
  target: target,
  workdir: workdir,
  permissionMode: permissionMode,
  prompt: prompt,
);

/// Decode a `shed-ext-rc list` stdout (what the Dart runner captured) into the
/// session DTOs. This is the "decode-in" half of the round-trip.
Future<List<BridgeRcSession>> rcDecodeList({required String stdout}) =>
    RustLib.instance.api.crateApiRcRunnerRcDecodeList(stdout: stdout);

/// Map a non-zero exit from the Dart runner to a stable error string (proves the
/// typed-error path: exit 3 → SlugTaken, 4 → NotFound, 127 → MissingBinary, …).
Future<String> rcErrorFromExit({
  required int exitCode,
  required String stderr,
  required String stdout,
}) => RustLib.instance.api.crateApiRcRunnerRcErrorFromExit(
  exitCode: exitCode,
  stderr: stderr,
  stdout: stdout,
);

/// argv + optional stdin, marshalled to Dart.
class BridgeRcInvocation {
  final List<String> argv;

  /// The stdin payload (e.g. the initial prompt), if any.
  final String? stdin;

  const BridgeRcInvocation({required this.argv, this.stdin});

  @override
  int get hashCode => argv.hashCode ^ stdin.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRcInvocation &&
          runtimeType == other.runtimeType &&
          argv == other.argv &&
          stdin == other.stdin;
}

/// A decoded session row (the small DTO the app renders).
class BridgeRcSession {
  final String slug;
  final String kind;
  final String state;
  final bool managed;
  final String? displayName;

  const BridgeRcSession({
    required this.slug,
    required this.kind,
    required this.state,
    required this.managed,
    this.displayName,
  });

  @override
  int get hashCode =>
      slug.hashCode ^
      kind.hashCode ^
      state.hashCode ^
      managed.hashCode ^
      displayName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRcSession &&
          runtimeType == other.runtimeType &&
          slug == other.slug &&
          kind == other.kind &&
          state == other.state &&
          managed == other.managed &&
          displayName == other.displayName;
}
