// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.5.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`

/// A secret on its way across the bridge: a bearer token, or the raw
/// `_bootstrap` stdout that in token mode IS a bearer plus its envelope.
///
/// It exists because of what the codegen does with a bare `String`. FRB renders
/// every fielded Rust enum as a Dart `@freezed` sealed class, and freezed
/// generates a `toString()` that prints every field. So a `String` secret on a
/// variant (`BridgeCredentialEvent::Adopted.token`,
/// `BridgeMintOutcome::Success.raw_stdout`) was printed whole by any `'$event'`
/// interpolation, log line or error message that rendered the variant
/// (shed-mobile#30).
///
/// FRB renders a plain struct like this one as a plain Dart class with `==` and
/// `hashCode` and NO `toString()`, so freezed's rendering of the enclosing
/// variant prints `Instance of 'BridgeSecret'` and never the value. Reading the
/// secret takes an explicit `.value`.
///
/// On the Rust side `Debug` is implemented by hand, to redact, so a future
/// `derive(Debug)` on an enclosing type cannot print the value there either. A
/// trait impl is not carried to Dart by the codegen.
///
/// The field is NAMED so Dart reads `.value` rather than a positional
/// `.field0`.
class BridgeSecret {
  final String value;

  const BridgeSecret({required this.value});

  @override
  int get hashCode => value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeSecret &&
          runtimeType == other.runtimeType &&
          value == other.value;
}
