// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Async round-trip through `shed_core::ping` (exercises the async bridge path
/// + pulls in tokio), plus two synchronous pure-Rust probes:
///   * `shed_core::token::name_jitter` — pure, deterministic-shape token helper.
///   * `shed_core::http::Client::new`  — CONSTRUCTS a reqwest client, which is
///     what forces reqwest + rustls (ring) to link. We use a bogus https URL so
///     no network I/O happens; we only care that the client builds.
Future<String> shedCoreProbe({required String echo}) =>
    RustLib.instance.api.crateApiShedShedCoreProbe(echo: echo);

/// Proves `shed-app` (default features) also links — constructs an in-memory
/// `AuditStore` (a display-free app-logic type) and reports its empty tail.
/// This is the "shed-app is reachable, no `rc` feature needed" check.
Future<String> shedAppProbe() =>
    RustLib.instance.api.crateApiShedShedAppProbe();
