// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `slug_of`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `drop`

/// Step 1: stand up a local SSE server + a real `RcEventsWatcher` against it,
/// returning the bridge-owned opaque handle (Dart holds it for teardown). The
/// mpsc is parked inside the handle until `rc_watcher_events` drains it.
Future<BridgeWatcherHandle> createRcWatcher() =>
    RustLib.instance.api.crateApiWatcherCreateRcWatcher();

/// Step 2: drain the handle's watcher mpsc into a Dart `Stream`, folding
/// `Resynced` onto the next `Event`. FRB renders this (a `StreamSink` param) as
/// `Stream<BridgeWatcherUpdate>`. The forwarder exits when the sink closes
/// (Dart cancelled the subscription) or the mpsc ends.
Stream<BridgeWatcherUpdate> rcWatcherEvents({
  required BridgeWatcherHandle handle,
}) => RustLib.instance.api.crateApiWatcherRcWatcherEvents(handle: handle);

/// Explicit synchronous stop (idempotent) — belt-and-suspenders alongside the
/// handle's Drop. Dart calls this from `onDispose`.
Future<void> stopRcEvents({required BridgeWatcherHandle handle}) =>
    RustLib.instance.api.crateApiWatcherStopRcEvents(handle: handle);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BridgeWatcherHandle>>
abstract class BridgeWatcherHandle implements RustOpaqueInterface {
  /// Idempotent synchronous teardown (belt-and-suspenders alongside Drop):
  /// aborts the forwarder + SSE server, drops the watcher (aborting its loop),
  /// and decrements the leak counters exactly once.
  Future<void> stop();
}

/// One decoded watcher update marshalled to Dart. `kind` is `"event"` or
/// `"down"`. On an `"event"`, `resync` is set if a `Resynced` preceded it (the
/// consumer then invalidates its overview). Each event carries the full folded
/// snapshot in the real app; here we surface just shed/slug for the proof.
class BridgeWatcherUpdate {
  final String kind;
  final String shed;
  final String slug;
  final bool resync;
  final String reason;

  const BridgeWatcherUpdate({
    required this.kind,
    required this.shed,
    required this.slug,
    required this.resync,
    required this.reason,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      shed.hashCode ^
      slug.hashCode ^
      resync.hashCode ^
      reason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeWatcherUpdate &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          shed == other.shed &&
          slug == other.slug &&
          resync == other.resync &&
          reason == other.reason;
}
