// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.5.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'client.dart';
import 'dto_rc.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'watcher.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `event_session_key`, `forward_loop`, `from_live`, `teardown`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `WatcherInner`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `drop`, `eq`, `fmt`

/// Step 1: spawn a real `RcEventsWatcher` against `client` on `bridge_rt`,
/// returning the bridge-owned opaque handle. The mpsc is parked inside the handle
/// until [`rc_watcher_events`] drains it.
Future<BridgeWatcherHandle> createRcWatcher({
  required BridgeClient client,
  required String serverName,
}) => RustLib.instance.api.crateApiWatcherCreateRcWatcher(
  client: client,
  serverName: serverName,
);

/// Step 2: drain the handle's watcher mpsc into a Dart `Stream`, folding
/// `Resynced` onto the next `Event` and reconstructing the enumerable overlay
/// snapshot per event.
Stream<BridgeWatcherUpdate> rcWatcherEvents({
  required BridgeWatcherHandle handle,
}) => RustLib.instance.api.crateApiWatcherRcWatcherEvents(handle: handle);

/// Explicit SYNCHRONOUS stop (idempotent, co-primary with Drop). Dart calls this
/// from `onDispose`; it aborts a parked forwarder immediately (Codex #5/#9).
void stopRcEvents({required BridgeWatcherHandle handle}) =>
    RustLib.instance.api.crateApiWatcherStopRcEvents(handle: handle);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BridgeWatcherHandle>>
abstract class BridgeWatcherHandle implements RustOpaqueInterface {}

/// One folded live-activity patch, keyed by `(shed, slug)` — the enumerable
/// mirror of one `ActivityOverlay` entry.
class BridgeOverlayEntry {
  final String shed;
  final String slug;
  final BridgeRcActivity? activity;
  final BridgeRcState? state;
  final String? lastMessage;
  final BigInt? lastSeq;

  const BridgeOverlayEntry({
    required this.shed,
    required this.slug,
    this.activity,
    this.state,
    this.lastMessage,
    this.lastSeq,
  });

  @override
  int get hashCode =>
      shed.hashCode ^
      slug.hashCode ^
      activity.hashCode ^
      state.hashCode ^
      lastMessage.hashCode ^
      lastSeq.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeOverlayEntry &&
          runtimeType == other.runtimeType &&
          shed == other.shed &&
          slug == other.slug &&
          activity == other.activity &&
          state == other.state &&
          lastMessage == other.lastMessage &&
          lastSeq == other.lastSeq;
}

@freezed
sealed class BridgeWatcherUpdate with _$BridgeWatcherUpdate {
  const BridgeWatcherUpdate._();

  const factory BridgeWatcherUpdate.event({
    required BridgeRcEvent event,
    required List<BridgeOverlayEntry> overlay,
    required bool resync,
  }) = BridgeWatcherUpdate_Event;

  /// The connection ended; the watcher backs off and reconnects.
  const factory BridgeWatcherUpdate.down({required String reason}) =
      BridgeWatcherUpdate_Down;
}
