default_platform(:android)

platform :android do
  desc "Upload AAB to Play Store"
  lane :deploy do
    upload_to_play_store(
      track: ENV.fetch("PLAY_STORE_TRACK", "internal"),
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      json_key: ENV.fetch("PLAY_STORE_JSON_KEY_PATH"),
      package_name: "ai.stridelabs.shed",
      version_name: ENV["RELEASE_NAME"],
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      skip_upload_changelogs: false,
      release_status: ENV.fetch("RELEASE_STATUS", "draft"),
    )
  end
end
